// Code generated by gen-server-stub (go/ast + text/template); DO NOT EDIT.

package account

import (
	"net/http"
)

// serverStub implements every ServerInterface method, returning HTTP 501
// for endpoints that are not overridden by the fake-data implementation.
// Embedding this gives a clean 501 (not a nil-interface panic) for
// any endpoint the client reaches that the fake does not explicitly serve.
type serverStub struct{}

func (serverStub) DeleteApiAccount(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccount(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PatchApiAccount(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountAvatar(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountAvatar(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingBalance(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingCancel(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingCancelAbort(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingChangePlan(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingCheckoutSessionSessionIdStatus(w http.ResponseWriter, r *http.Request, sessionId string, params GetApiAccountBillingCheckoutSessionSessionIdStatusParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingCheckoutUiPlanId(w http.ResponseWriter, r *http.Request, planId string, params GetApiAccountBillingCheckoutUiPlanIdParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingCredits(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingCustomerPortal(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingManagement(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingManagementCapabilities(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingPause(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingResume(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingSubscription(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountBillingSubscriptionEvents(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountBillingWebhooksGatewayType(w http.ResponseWriter, r *http.Request, gatewayType string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountKeys(w http.ResponseWriter, r *http.Request, params GetApiAccountKeysParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountKeys(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiAccountKeysKeyID(w http.ResponseWriter, r *http.Request, keyID StringUUIDSchema) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountPasswordResetConfirm(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountPasswordResetRequest(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountPermissions(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountQuota(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAccountQuotaHistory(w http.ResponseWriter, r *http.Request, params GetApiAccountQuotaHistoryParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountUpdateEmail(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountUpdatePassword(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountVerifyEmail(w http.ResponseWriter, r *http.Request, params PostApiAccountVerifyEmailParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAccountVerifyEmailResend(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthKey(w http.ResponseWriter, r *http.Request, params PostApiAuthKeyParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthKeyChallenge(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthKeyConnectChallenge(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthKeyConnectVerify(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiAuthKeyIdentities(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthKeyVerify(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiAuthKeyTypeKey(w http.ResponseWriter, r *http.Request, pType string, key string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthLogin(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthLogout(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthOtpDisable(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthOtpGenerate(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthOtpValidate(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthOtpVerify(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthPing(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiAuthRegister(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiBillingCreditsPurchase(w http.ResponseWriter, r *http.Request, params PostApiBillingCreditsPurchaseParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiBillingGateways(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiBillingGatewaysIdLogo(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiBillingPlans(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiOperations(w http.ResponseWriter, r *http.Request, params GetApiOperationsParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiOperationsFilters(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiOperationsId(w http.ResponseWriter, r *http.Request, id int) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiUploadLimit(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}
