// Code generated by gen-server-stub (go/ast + text/template); DO NOT EDIT.

package ipfs

import (
	"net/http"
)

// serverStub implements every ServerInterface method, returning HTTP 501
// for endpoints that are not overridden by the fake-data implementation.
// Embedding this gives a clean 501 (not a nil-interface panic) for
// any endpoint the client reaches that the fake does not explicitly serve.
type serverStub struct{}

func (serverStub) PostApiBlockMetaBatch(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiBlockMetaCid(w http.ResponseWriter, r *http.Request, cid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiDagCid(w http.ResponseWriter, r *http.Request, cid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiDnsZones(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiDnsZones(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiDnsZonesId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiDnsZonesId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PutApiDnsZonesId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiDnsZonesIdRecords(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiDnsZonesIdRecords(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiDnsZonesIdRecordsBulk(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiDnsZonesIdRecordsBulkDelete(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiDnsZonesIdRecordsNameType(w http.ResponseWriter, r *http.Request, id string, name string, pType string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiDnsZonesIdRecordsNameType(w http.ResponseWriter, r *http.Request, id string, name string, pType string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PutApiDnsZonesIdRecordsNameType(w http.ResponseWriter, r *http.Request, id string, name string, pType string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiDnsZonesIdStatus(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiDnsZonesIdValidate(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiFiles(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiFilesBreadcrumbs(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiFilesDirectory(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiInfo(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiIpnsKeys(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiIpnsKeys(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiIpnsKeysId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiIpnsKeysId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiIpnsKeysIdRepublish(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiIpnsPublish(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiIpnsResolveName(w http.ResponseWriter, r *http.Request, name string, params GetApiIpnsResolveNameParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiUpload(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiUploadResultIdentifier(w http.ResponseWriter, r *http.Request, identifier string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) OptionsApiUploadTus(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiUploadTus(w http.ResponseWriter, r *http.Request, params PostApiUploadTusParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiUploadTusId(w http.ResponseWriter, r *http.Request, id string, params DeleteApiUploadTusIdParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) HeadApiUploadTusId(w http.ResponseWriter, r *http.Request, id string, params HeadApiUploadTusIdParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) OptionsApiUploadTusId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PatchApiUploadTusId(w http.ResponseWriter, r *http.Request, id string, params PatchApiUploadTusIdParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsites(w http.ResponseWriter, r *http.Request, params GetApiWebsitesParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiWebsites(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesConfig(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesPlatformDomains(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesPlatformDomainsAvailability(w http.ResponseWriter, r *http.Request, params GetApiWebsitesPlatformDomainsAvailabilityParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesDomainSslStatus(w http.ResponseWriter, r *http.Request, domain string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiWebsitesId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PutApiWebsitesId(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesIdDomains(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiWebsitesIdDomains(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeleteApiWebsitesIdDomainsDomainId(w http.ResponseWriter, r *http.Request, id string, domainId string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PatchApiWebsitesIdDomainsDomainId(w http.ResponseWriter, r *http.Request, id string, domainId string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiWebsitesIdDomainsDomainIdDaneRepublish(w http.ResponseWriter, r *http.Request, id string, domainId string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetApiWebsitesIdDomainsDomainIdDnsRequirements(w http.ResponseWriter, r *http.Request, id string, domainId string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiWebsitesIdDomainsDomainIdOnchain(w http.ResponseWriter, r *http.Request, id string, domainId string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiWebsitesIdDomainsDomainIdVerify(w http.ResponseWriter, r *http.Request, id string, domainId string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostApiWebsitesIdValidate(w http.ResponseWriter, r *http.Request, id string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostInternalDnsCert(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetInternalDnsCertDomain(w http.ResponseWriter, r *http.Request, domain string, params GetInternalDnsCertDomainParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostInternalDnsTlsa(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetInternalPing(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetInternalWebsitesChanges(w http.ResponseWriter, r *http.Request, params GetInternalWebsitesChangesParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetInternalWebsitesEvents(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetInternalWebsitesDomain(w http.ResponseWriter, r *http.Request, domain string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostInternalWebsitesDomainSslStatus(w http.ResponseWriter, r *http.Request, domain string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetInternalWebsitesDomainStatus(w http.ResponseWriter, r *http.Request, domain string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetIpfsCid(w http.ResponseWriter, r *http.Request, cid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) HeadIpfsCid(w http.ResponseWriter, r *http.Request, cid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) OptionsIpfsCid(w http.ResponseWriter, r *http.Request, cid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetPins(w http.ResponseWriter, r *http.Request, params GetPinsParams) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) OptionsPins(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostPins(w http.ResponseWriter, r *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) DeletePinsRequestid(w http.ResponseWriter, r *http.Request, requestid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetPinsRequestid(w http.ResponseWriter, r *http.Request, requestid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) OptionsPinsRequestid(w http.ResponseWriter, r *http.Request, requestid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) PostPinsRequestid(w http.ResponseWriter, r *http.Request, requestid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetRoutingV1IpnsName(w http.ResponseWriter, r *http.Request, name string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}

func (serverStub) GetRoutingV1ProvidersCid(w http.ResponseWriter, r *http.Request, cid string) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}
