package mcpapp

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"io"
	"io/fs"
	"slices"
	"testing"

	"go.lumeweb.com/mcpcanvas"
)

// The app asset manifest (generated by build/genappmanifest, wired into the
// jsbuild Makefile target) must satisfy the mcpcanvas AssetSource contract:
// mcpcanvas.NewEmbedSource accepts our appsassets root as-is, every view in
// bundleNames has a manifest entry, and each manifest hash matches the actual
// embedded bundle bytes. These tests pin that contract against drift in
// either direction (manifest regeneration vs. bundleNames changes).
func TestAppsManifestValidMcpcanvasScheme(t *testing.T) {
	data, err := fs.ReadFile(AppsAssets, "appsassets/manifest.json")
	if err != nil {
		t.Fatalf("read embedded manifest: %v (run `make jsbuild` / `go run ./build/genappmanifest` first)", err)
	}
	var manifest mcpcanvas.Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("parse manifest.json: %v", err)
	}
	if err := manifest.Validate(); err != nil {
		t.Fatalf("manifest fails mcpcanvas.Manifest.Validate: %v", err)
	}
	if manifest.SchemaVersion != mcpcanvas.ManifestSchemaVersion {
		t.Fatalf("schema version %d, want %d", manifest.SchemaVersion, mcpcanvas.ManifestSchemaVersion)
	}
}

func TestAppsManifestCoversBundleNames(t *testing.T) {
	data, err := fs.ReadFile(AppsAssets, "appsassets/manifest.json")
	if err != nil {
		t.Fatalf("read embedded manifest: %v", err)
	}
	var manifest mcpcanvas.Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("parse manifest.json: %v", err)
	}

	views := make(map[string]bool, len(manifest.Bundles))
	for _, b := range manifest.Bundles {
		if views[b.View] {
			t.Errorf("duplicate view %q in manifest", b.View)
		}
		views[b.View] = true
	}
	for view := range bundleNames {
		if !views[view] {
			t.Errorf("bundleNames view %q missing from manifest", view)
		}
	}
	if len(manifest.Bundles) != len(bundleNames) {
		t.Errorf("manifest has %d bundles, bundleNames has %d keys", len(manifest.Bundles), len(bundleNames))
	}
}

func TestAppsManifestBundleHashes(t *testing.T) {
	data, err := fs.ReadFile(AppsAssets, "appsassets/manifest.json")
	if err != nil {
		t.Fatalf("read embedded manifest: %v", err)
	}
	var manifest mcpcanvas.Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("parse manifest.json: %v", err)
	}
	for _, b := range manifest.Bundles {
		// File paths are relative to the asset source root, i.e. the
		// appsassets dir itself ("dist/<view>.js"); the embed FS root is the
		// mcpapp package dir, hence the "appsassets/" prefix here.
		content, err := fs.ReadFile(AppsAssets, "appsassets/"+b.File)
		if err != nil {
			t.Fatalf("view %q: read bundle %s from embed FS: %v", b.View, b.File, err)
		}
		sum := sha256.Sum256(content)
		if got := hex.EncodeToString(sum[:]); got != b.Hash {
			t.Errorf("view %q (%s): manifest hash %s, embedded bytes hash %s", b.View, b.File, b.Hash, got)
		}
	}
}

// TestAppsManifestEmbedSourceAcceptsRoot proves the appsassets FS — with the
// generated manifest at its root — satisfies mcpcanvas.NewEmbedSource exactly
// as the eventual canvas renderer (canvas.NewRenderer(src mcpcanvas.AssetSource,
// themeCSS)) would consume it, and that every bundleNames view resolves with
// verified, seekable content.
func TestAppsManifestEmbedSourceAcceptsRoot(t *testing.T) {
	root, err := fs.Sub(AppsAssets, "appsassets")
	if err != nil {
		t.Fatalf("sub appsassets root: %v", err)
	}
	src, err := mcpcanvas.NewEmbedSource(root)
	if err != nil {
		t.Fatalf("mcpcanvas.NewEmbedSource(appsassets): %v", err)
	}
	ctx := t.Context()
	manifest, err := src.Manifest(ctx)
	if err != nil {
		t.Fatalf("src.Manifest: %v", err)
	}
	gotViews := make([]string, 0, len(manifest.Bundles))
	for _, b := range manifest.Bundles {
		gotViews = append(gotViews, b.View)
	}
	for view := range bundleNames {
		if !slices.Contains(gotViews, view) {
			t.Errorf("EmbedSource manifest missing view %q", view)
			continue
		}
		r, err := src.Open(ctx, view)
		if err != nil {
			t.Errorf("open view %q: %v", view, err)
			continue
		}
		if seeker, ok := r.(interface {
			Seek(int64, int) (int64, error)
		}); !ok {
			t.Errorf("view %q: content is not seekable", view)
		} else {
			if _, err := seeker.Seek(0, 0); err != nil {
				t.Errorf("view %q: seek to start: %v", view, err)
			}
		}
		if c, ok := r.(io.Closer); ok {
			c.Close()
		}
	}
}
