package mcpapp

import (
	"context"
	"io/fs"
	"sync"

	"go.lumeweb.com/mcpcanvas"
	"go.lumeweb.com/pinner/canvas"

	"go.lumeweb.com/pinner-cli/build"
)

// The MCP Apps rendering seam now delegates to the go.lumeweb.com/pinner/canvas
// module: every ui:// app document is assembled by canvas.Renderer (which in
// turn uses mcpcanvas.RenderAppDoc for the shell and mcpcanvas.ModuleJS for the
// manifest-verified, version-stamped module script), so the CLI keeps only the
// asset provider role: the appsassets embed FS (bundles + generated manifest)
// and the compiled Tailwind theme (McpAppThemeCSS).

// canvasRenderer lazily builds the single shared canvas.Renderer exactly once,
// from the CLI's embedded asset source (appsassets root: dist bundles +
// appsassets/manifest.json) and the CLI's compiled Tailwind theme.
//
// Concurrency: sync.OnceValue guarantees the constructor runs exactly once and
// every caller observes the same *canvas.Renderer; concurrent first callers
// block until initialization completes. The constructor cannot fail on a
// correctly built tree (the embedded manifest is generated by
// `make mcpembed`), so an error is a build/programming error and panics —
// failing loudly on a broken tree instead of serving blank apps. Because OnceValue
// caches the result, a panic is re-raised on every subsequent call rather than
// retried, so a broken tree fails loudly instead of partially.
var canvasRenderer = sync.OnceValue(func() *canvas.Renderer {
	root, err := fs.Sub(AppsAssets, "appsassets")
	if err != nil {
		panic("mcpapp: sub appsassets from embedded FS: " + err.Error())
	}
	src, err := mcpcanvas.NewEmbedSource(root)
	if err != nil {
		panic("mcpapp: build mcpcanvas.EmbedSource from appsassets (run `make mcpembed`): " + err.Error())
	}
	r, err := canvas.NewRenderer(src, McpAppThemeCSS)
	if err != nil {
		panic("mcpapp: build canvas renderer: " + err.Error())
	}
	return r
})

// canvasBody maps a canvas view to the go.lumeweb.com/pinner/canvas templ
// body component for that view's screen. The module bodies are pure static
// markup (no parameters), ported verbatim from the CLI bodies in this
// package, so the mapping is total over AllViews and needs no per-view
// arguments.
func canvasBody(view canvas.View) mcpcanvas.BodyComponent {
	switch view {
	case canvas.ViewPin:
		return canvas.PinCreateAppForm()
	case canvas.ViewPinList:
		return canvas.PinListAppForm()
	case canvas.ViewVaultBrowser:
		return canvas.VaultBrowserAppForm()
	case canvas.ViewVaultCreate:
		return canvas.VaultCreateAppForm()
	case canvas.ViewVaultRestore:
		return canvas.VaultRestoreAppForm()
	case canvas.ViewVaultUpload:
		return canvas.VaultUploadAppForm()
	case canvas.ViewVaultDownload:
		return canvas.VaultDownloadAppForm()
	case canvas.ViewIPFSUpload:
		return canvas.IPFSUploadAppForm()
	case canvas.ViewIPFSDownload:
		return canvas.IPFSDownloadAppForm()
	case canvas.ViewAuthSSO:
		return canvas.AuthSSOAppForm()
	case canvas.ViewAuthStatus:
		return canvas.AuthStatusAppForm()
	case canvas.ViewAccountPassword:
		return canvas.AccountPasswordAppForm()
	case canvas.ViewAccountEmail:
		return canvas.AccountEmailAppForm()
	}
	return nil
}

// RenderAppDoc renders the complete, self-contained ui:// MCP App document
// for view, delegating to the shared canvas.Renderer: the <title>, the inline
// McpAppThemeCSS theme, the view's static templ body from
// go.lumeweb.com/pinner/canvas, and the view's ESM bundle resolved (and
// sha256-verified) through the CLI's embedded appsassets manifest, prefixed
// with the version handshake global. The version is the CLI's build version
// (build.Default.GetVersion, "develop" when unstamped); mcpcanvas normalizes
// non-semver values to "1.0.0".
//
// Unknown views wrap canvas.ErrUnknownView and bundle/manifest problems wrap
// the mcpcanvas sentinels; these are build/programming errors, so they panic
// rather than leak an error into
// every internal/mcp render function's string-returning signature.
func RenderAppDoc(view canvas.View, title string) string {
	body := canvasBody(view)
	if body == nil {
		panic("mcpapp: no canvas body for view " + string(view))
	}
	doc, err := canvasRenderer().RenderDoc(context.Background(), view, title, body, build.Default.GetVersion())
	if err != nil {
		panic("mcpapp: render app doc for view " + string(view) + ": " + err.Error())
	}
	return doc
}
