// Package mcpapp is the importable, versioned asset and render seam for ui://
// MCP Apps (ext-apps), shared between the pinner-cli CLI and hosted composition
// roots such as the Portal MCP plugin.
//
// It is the published artifact behind the MCP Apps surface:
//
//   - AppsAssets is an embed.FS carrying each app's fully self-contained ESM
//     bundle (mcpapp/appsassets/dist/<app>.js) plus the generated
//     mcpcanvas AssetSource manifest (mcpapp/appsassets/manifest.json).
//   - McpAppThemeCSS is the compiled (tree-shaken) Tailwind v4 theme.
//   - canvasRenderer is a sync.OnceValue canvas.Renderer built over
//     AppsAssets + McpAppThemeCSS, and RenderAppDoc renders any canvas.View
//     through it (mcpcanvas.ModuleJS manifest-verified bundle resolution and
//     version handshake).
//
// A hosted root embeds this package (go:embed) and builds a
// canvas.Renderer-backed RenderFunc over it, without importing any
// pinner-cli internal package. The embedded assets are regenerated by the
// `make assets` pipeline (pnpm build + genappmanifest + Tailwind) and are
// committed/released so the version consumers pin tracks develop.
package mcpapp
