package mcp

import (
	"context"
	"fmt"

	"go.lumeweb.com/pinner-cli/internal/mcp/core/model"
)

// Prompt name constants.
const (
	PromptWebsiteOnboarding = "website-onboarding"
	PromptWebsiteUpdate     = "website-update"
	PromptSetup             = "setup"
	PromptENSPublish        = "ens-publish"
)

// Prompt argument names.
const (
	ArgDomain        = "domain"
	ArgContentSource = "content_source"
	ArgTargetType    = "target_type"
	ArgDNSMode       = "dns_mode"

	// website-update prompt arguments.
	ArgWebsite     = "website"
	ArgCID         = "cid"
	ArgCurrentType = "current_type"

	// ens-publish prompt arguments.
	ArgENSName = "name"
)

// PromptDescriptors builds the SDK-neutral prompt descriptors for the
// website-onboarding and setup workflows. Each prompt returns a sequence of
// messages that instruct the agent to drive the corresponding wizard workflow
// deterministically, using the wizard tools and pinner:// resources. The
// message prose is rendered from embedded text/templates (prompttemplates/).
func PromptDescriptors() []model.PromptDescriptor {
	return PromptDescriptorsForSurface(FullSurface)
}

// PromptDescriptorsForSurface returns the prompt descriptors enabled for the
// given surface. Each prompt maps to a domain flag: website onboarding/update
// need the websites surface, setup needs the account surface, and ENS publish
// needs the ENS surface. A restricted surface (e.g. hosted) omits the prompts
// whose underlying tools are not registered.
func PromptDescriptorsForSurface(surface Surface) []model.PromptDescriptor {
	all := []model.PromptDescriptor{
		{
			Name:        PromptWebsiteOnboarding,
			Title:       "Website Onboarding Wizard",
			Description: "Guides the agent through the website creation wizard workflow step by step using the websites_wizard_start and websites_wizard_step tools. Covers binding a plain domain OR claiming a free platform subdomain (auto-generated by default, or an explicit label when the user requests one) under a platform root. Custom domains default to namespace icann; Handshake (hns) alt-root names are supported via the namespace field. Embeds references to pinner:// resources for platform domains, DNS requirements and validation status. Optional arguments pre-fill wizard choices.",
			Arguments: []model.PromptArgumentDescriptor{
				{Name: ArgDomain, Description: `Domain name for the website (e.g. example.com). If omitted, the website uses a platform (free) subdomain auto-generated by default. Only supply a label when the user explicitly requests one. For a Handshake (alt-root) name (e.g. acme/), pass the name here and set namespace=hns. Do not invent a domain.`},
				{Name: ArgContentSource, Description: `Content source: "cid" (already have a CID) or "upload" (need to upload first). Default: cid.`},
				{Name: ArgTargetType, Description: `Content addressing type: "ipfs" or "ipns". Default: ipfs.`},
				{Name: ArgDNSMode, Description: `DNS mode: "managed" (Pinner handles DNS) or "self_managed". Default: managed.`},
			},
			Handler: websiteOnboardingHandler,
		},
		{
			Name:        PromptWebsiteUpdate,
			Title:       "Website Update Workflow",
			Description: "Guides the agent through updating an existing website's content: resolve current state first, ensure the new CID is pinned, perform the update while preserving the current target type, handle DNS per mode (managed vs self-managed), then verify.",
			Arguments: []model.PromptArgumentDescriptor{
				{Name: ArgWebsite, Description: "Website domain or ID to update."},
				{Name: ArgCID, Description: "New IPFS CID to serve."},
				{Name: ArgCurrentType, Description: `Current target type ("ipfs" or "ipns"). If omitted, the agent must fetch the website first so the type is preserved, never guessed.`},
			},
			Handler: websiteUpdateHandler,
		},
		{
			Name:        PromptSetup,
			Title:       "Setup Wizard",
			Description: "Guides the agent through the initial pinner setup wizard workflow step by step using the setup_wizard_start and setup_wizard_step tools. Covers authentication, configuration, shell completion, and a quick tutorial. Embeds a reference to the pinner://account/status resource.",
			Handler:     setupHandler,
		},
		{
			Name:        PromptENSPublish,
			Title:       "Point an ENS Name at Content",
			Description: "Guides the agent through pointing an ENS/onchain name (e.g. vitalik.eth) at IPFS content: upload the content to get a CID, call ens_point to publish it under the name's IPNS key and obtain the contenthash, then guide the user to set the ENS resolver contenthash onchain from their own wallet/ENS manager (without assuming a specific wallet) and verify via the returned gateway URL. ENS names do not use the website/DNS system.",
			Arguments: []model.PromptArgumentDescriptor{
				{Name: ArgENSName, Description: `The ENS/onchain domain to point (e.g. vitalik.eth). Required. Do not invent one; use the name the user provided.`},
				{Name: ArgCID, Description: `IPFS CID of the content to serve. If omitted, the flow first uploads the content to obtain a CID.`},
			},
			Handler: ensPublishHandler,
		},
	}

	var out []model.PromptDescriptor
	for _, p := range all {
		var on bool
		switch p.Name {
		case PromptWebsiteOnboarding, PromptWebsiteUpdate:
			on = surface.WebsitesOn()
		case PromptSetup:
			on = surface.AccountOn()
		case PromptENSPublish:
			on = surface.ENSOn()
		default:
			on = true
		}
		if on {
			out = append(out, p)
		}
	}
	return out
}

// websiteOnboardingHandler is the prompts/get handler for the
// website-onboarding prompt. It renders a sequence of messages — from the
// embedded website_onboarding.tmpl templates — that instruct the agent to
// execute the websites wizard workflow.
func websiteOnboardingHandler(ctx context.Context, req model.PromptRequest) (model.PromptResult, error) {
	args := req.Arguments
	domain := args[ArgDomain]
	contentSource := args[ArgContentSource]
	targetType := args[ArgTargetType]
	dnsMode := args[ArgDNSMode]

	// Validate optional arguments if provided.
	if contentSource != "" && contentSource != "cid" && contentSource != "upload" {
		return model.PromptResult{}, fmt.Errorf("invalid content_source %q: expected \"cid\" or \"upload\"", contentSource)
	}
	if targetType != "" && targetType != "ipfs" && targetType != "ipns" {
		return model.PromptResult{}, fmt.Errorf("invalid target_type %q: expected \"ipfs\" or \"ipns\"", targetType)
	}
	if dnsMode != "" && dnsMode != "managed" && dnsMode != "self_managed" {
		return model.PromptResult{}, fmt.Errorf("invalid dns_mode %q: expected \"managed\" or \"self_managed\"", dnsMode)
	}

	data := sitePromptData{
		Domain:        domain,
		ContentSource: contentSource,
		TargetType:    targetType,
		DNSMode:       dnsMode,
	}

	var messages []model.PromptMessage

	// Step 0: Overview and prerequisites.
	messages = append(messages, textMsg(renderPromptTemplate("website_overview", data)))

	// Step 1: Read account status resource to verify authentication.
	messages = append(messages, embeddedMsg(AccountStatusURI))
	messages = append(messages, textMsg(renderPromptTemplate("website_auth_status", data)))

	// Step 2: Start the wizard.
	messages = append(messages, textMsg(renderPromptTemplate("website_start", data)))

	// Step 3: Auth check step.
	messages = append(messages, textMsg(renderPromptTemplate("website_step_auth_check", data)))

	// Step 4: Content source step.
	var contentStep string
	switch contentSource {
	case "upload":
		contentStep = "website_step_content_source_upload"
	case "cid":
		contentStep = "website_step_content_source_cid"
	default:
		contentStep = "website_step_content_source_ask"
	}
	messages = append(messages, textMsg(renderPromptTemplate(contentStep, data)))

	// Step 5: Target type step.
	if targetType != "" {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_target_type_filled", data)))
	} else {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_target_type_ask", data)))
	}

	// Step 6: Domain step. Embed the platform-domains resource so the agent can
	// see the enabled free-subdomain roots before choosing a domain path.
	messages = append(messages, embeddedMsg(PlatformDomainsURI))
	if domain != "" {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_domain_filled", data)))
	} else {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_domain_ask", data)))
	}

	// Step 7: DNS mode step.
	if dnsMode != "" {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_dns_mode_filled", data)))
	} else {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_dns_mode_ask", data)))
	}

	// Step 8: Create step.
	messages = append(messages, textMsg(renderPromptTemplate("website_step_create", data)))

	// Step 9: DNS setup step: embed the resource reference.
	if domain != "" {
		messages = append(messages, embeddedMsg(fmt.Sprintf("pinner://websites/%s/dns-requirements", domain)))
		messages = append(messages, textMsg(renderPromptTemplate("website_step_dns_setup_filled", data)))
	} else {
		messages = append(messages, textMsg(renderPromptTemplate("website_step_dns_setup_ask", data)))
	}

	// Step 10: Validate step.
	validateURI := ValidationStatusTmpl
	if domain != "" {
		// We don't have the website ID at prompt time, but the agent will
		// resolve it from the wizard's create response.
		validateURI = "pinner://websites/{id}/validation-status"
	}
	messages = append(messages, embeddedMsg(validateURI))
	messages = append(messages, textMsg(renderPromptTemplate("website_step_validate", data)))

	// Step 11: Completion.
	messages = append(messages, textMsg(renderPromptTemplate("website_step_complete", data)))

	return model.PromptResult{
		Description: "Website onboarding wizard workflow with embedded resource references",
		Messages:    messages,
	}, nil
}

// websiteUpdateHandler is the prompts/get handler for the website-update
// prompt. It renders a sequence of messages that instruct the agent through
// the update flow: resolve current state, pin the new CID, update while
// preserving the target type, handle DNS per mode, then verify. The update
// path is tool-driven (websites_get / websites_update / websites_validate) and
// uses the pinner:// resources for live DNS/validation data.
func websiteUpdateHandler(ctx context.Context, req model.PromptRequest) (model.PromptResult, error) {
	args := req.Arguments
	website := args[ArgWebsite]
	cid := args[ArgCID]
	currentType := args[ArgCurrentType]

	if website == "" {
		return model.PromptResult{}, fmt.Errorf("website-update: website is required")
	}
	if cid == "" {
		return model.PromptResult{}, fmt.Errorf("website-update: cid is required")
	}

	data := sitePromptData{
		WebsiteArg:  website,
		CID:         cid,
		CurrentType: currentType,
	}
	var messages []model.PromptMessage

	messages = append(messages, textMsg(renderPromptTemplate("website_update_overview", data)))
	messages = append(messages, textMsg(renderPromptTemplate("website_update_step_resolve", data)))
	messages = append(messages, textMsg(renderPromptTemplate("website_update_step_pin", data)))
	messages = append(messages, textMsg(renderPromptTemplate("website_update_step_update", data)))
	messages = append(messages, textMsg(renderPromptTemplate("website_update_step_dns", data)))
	messages = append(messages, embeddedMsg(ValidationStatusTmpl))
	messages = append(messages, textMsg(renderPromptTemplate("website_update_step_validate", data)))
	messages = append(messages, textMsg(renderPromptTemplate("website_update_step_complete", data)))

	return model.PromptResult{
		Description: "Website update workflow with target-type preservation and DNS-mode handling",
		Messages:    messages,
	}, nil
}

// ensPublishHandler is the prompts/get handler for the ens-publish prompt. It
// renders a sequence of messages that drive the agent through the ENS publish
// flow: upload (when no CID is given), ens_point to publish + obtain the
// contenthash, onchain contenthash set (wallet guidance, without assuming a
// wallet), and verification.
func ensPublishHandler(ctx context.Context, req model.PromptRequest) (model.PromptResult, error) {
	args := req.Arguments
	name := args[ArgENSName]
	cid := args[ArgCID]

	if name == "" {
		return model.PromptResult{}, fmt.Errorf("ens-publish: name is required")
	}

	data := sitePromptData{ENSName: name, CID: cid}
	var messages []model.PromptMessage

	// Step 0: Overview.
	messages = append(messages, textMsg(renderPromptTemplate("ens_publish_overview", data)))

	// Step 1: Auth check via the account status resource.
	messages = append(messages, embeddedMsg(AccountStatusURI))
	messages = append(messages, textMsg(renderPromptTemplate("ens_publish_auth_status", data)))

	// Step 2: Content — upload first only if no CID was supplied.
	if cid == "" {
		messages = append(messages, textMsg(renderPromptTemplate("ens_publish_content_upload", data)))
	} else {
		messages = append(messages, textMsg(renderPromptTemplate("ens_publish_content_cid", data)))
	}

	// Step 3: Point the name (ens_point, discovered via search_tools).
	messages = append(messages, textMsg(renderPromptTemplate("ens_publish_point", data)))

	// Step 4: Wallet/onchain contenthash guidance.
	messages = append(messages, textMsg(renderPromptTemplate("ens_publish_wallet", data)))

	// Step 5: Verify via the returned gateway URL.
	messages = append(messages, textMsg(renderPromptTemplate("ens_publish_verify", data)))

	// Step 6: Completion summary.
	messages = append(messages, textMsg(renderPromptTemplate("ens_publish_complete", data)))

	return model.PromptResult{
		Description: "ENS publish workflow: upload -> ens_point -> set onchain contenthash -> verify",
		Messages:    messages,
	}, nil
}

// setupHandler is the prompts/get handler for the setup prompt. It renders the
// message sequence from the embedded setup.tmpl templates.
func setupHandler(ctx context.Context, req model.PromptRequest) (model.PromptResult, error) {
	data := sitePromptData{}
	var messages []model.PromptMessage

	// Step 0: Overview.
	messages = append(messages, textMsg(renderPromptTemplate("setup_overview", data)))

	// Step 1: Read account status to check current auth state.
	messages = append(messages, embeddedMsg(AccountStatusURI))
	messages = append(messages, textMsg(renderPromptTemplate("setup_auth_status_check", data)))

	// Step 2: Start the setup wizard.
	messages = append(messages, textMsg(renderPromptTemplate("setup_start", data)))

	// Step 3: Auth step.
	messages = append(messages, textMsg(renderPromptTemplate("setup_step_auth", data)))

	// Step 4: Config step.
	messages = append(messages, textMsg(renderPromptTemplate("setup_step_config", data)))

	// Step 5: Shell completion step.
	messages = append(messages, textMsg(renderPromptTemplate("setup_step_completion", data)))

	// Step 6: Tutorial step.
	messages = append(messages, textMsg(renderPromptTemplate("setup_step_tutorial", data)))

	// Step 7: Completion.
	messages = append(messages, embeddedMsg(AccountStatusURI))
	messages = append(messages, textMsg(renderPromptTemplate("setup_step_complete", data)))

	return model.PromptResult{
		Description: "Setup wizard workflow with embedded resource references",
		Messages:    messages,
	}, nil
}

// --- Prompt message helpers ---

// textMsg builds a user-role text message.
func textMsg(text string) model.PromptMessage {
	return model.PromptMessage{Role: "user", Text: text}
}

// embeddedMsg builds a user-role embedded-resource message that instructs the
// agent to read the resource at runtime.
func embeddedMsg(uri string) model.PromptMessage {
	return model.PromptMessage{
		Role: "user",
		EmbeddedResource: &model.ResourceResult{
			URI:      uri,
			MIMEType: "application/json",
			Text:     "Read this resource at runtime to get live data.",
		},
	}
}
