// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthPrompter creates a new instance of MockAuthPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthPrompter {
	mock := &MockAuthPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthPrompter is an autogenerated mock type for the AuthPrompter type
type MockAuthPrompter struct {
	mock.Mock
}

type MockAuthPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthPrompter) EXPECT() *MockAuthPrompter_Expecter {
	return &MockAuthPrompter_Expecter{mock: &_m.Mock}
}

// Password provides a mock function for the type MockAuthPrompter
func (_mock *MockAuthPrompter) Password(label string) (string, error) {
	ret := _mock.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(label)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(label)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthPrompter_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type MockAuthPrompter_Password_Call struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
//   - label string
func (_e *MockAuthPrompter_Expecter) Password(label interface{}) *MockAuthPrompter_Password_Call {
	return &MockAuthPrompter_Password_Call{Call: _e.mock.On("Password", label)}
}

func (_c *MockAuthPrompter_Password_Call) Run(run func(label string)) *MockAuthPrompter_Password_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthPrompter_Password_Call) Return(s string, err error) *MockAuthPrompter_Password_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthPrompter_Password_Call) RunAndReturn(run func(label string) (string, error)) *MockAuthPrompter_Password_Call {
	_c.Call.Return(run)
	return _c
}

// PromptEmail provides a mock function for the type MockAuthPrompter
func (_mock *MockAuthPrompter) PromptEmail() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PromptEmail")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthPrompter_PromptEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptEmail'
type MockAuthPrompter_PromptEmail_Call struct {
	*mock.Call
}

// PromptEmail is a helper method to define mock.On call
func (_e *MockAuthPrompter_Expecter) PromptEmail() *MockAuthPrompter_PromptEmail_Call {
	return &MockAuthPrompter_PromptEmail_Call{Call: _e.mock.On("PromptEmail")}
}

func (_c *MockAuthPrompter_PromptEmail_Call) Run(run func()) *MockAuthPrompter_PromptEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthPrompter_PromptEmail_Call) Return(s string, err error) *MockAuthPrompter_PromptEmail_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthPrompter_PromptEmail_Call) RunAndReturn(run func() (string, error)) *MockAuthPrompter_PromptEmail_Call {
	_c.Call.Return(run)
	return _c
}

// PromptOTP provides a mock function for the type MockAuthPrompter
func (_mock *MockAuthPrompter) PromptOTP() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PromptOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthPrompter_PromptOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptOTP'
type MockAuthPrompter_PromptOTP_Call struct {
	*mock.Call
}

// PromptOTP is a helper method to define mock.On call
func (_e *MockAuthPrompter_Expecter) PromptOTP() *MockAuthPrompter_PromptOTP_Call {
	return &MockAuthPrompter_PromptOTP_Call{Call: _e.mock.On("PromptOTP")}
}

func (_c *MockAuthPrompter_PromptOTP_Call) Run(run func()) *MockAuthPrompter_PromptOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthPrompter_PromptOTP_Call) Return(s string, err error) *MockAuthPrompter_PromptOTP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthPrompter_PromptOTP_Call) RunAndReturn(run func() (string, error)) *MockAuthPrompter_PromptOTP_Call {
	_c.Call.Return(run)
	return _c
}

// PromptPassword provides a mock function for the type MockAuthPrompter
func (_mock *MockAuthPrompter) PromptPassword() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PromptPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthPrompter_PromptPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptPassword'
type MockAuthPrompter_PromptPassword_Call struct {
	*mock.Call
}

// PromptPassword is a helper method to define mock.On call
func (_e *MockAuthPrompter_Expecter) PromptPassword() *MockAuthPrompter_PromptPassword_Call {
	return &MockAuthPrompter_PromptPassword_Call{Call: _e.mock.On("PromptPassword")}
}

func (_c *MockAuthPrompter_PromptPassword_Call) Run(run func()) *MockAuthPrompter_PromptPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthPrompter_PromptPassword_Call) Return(s string, err error) *MockAuthPrompter_PromptPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthPrompter_PromptPassword_Call) RunAndReturn(run func() (string, error)) *MockAuthPrompter_PromptPassword_Call {
	_c.Call.Return(run)
	return _c
}

// PromptString provides a mock function for the type MockAuthPrompter
func (_mock *MockAuthPrompter) PromptString(label string) (string, error) {
	ret := _mock.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for PromptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(label)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(label)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthPrompter_PromptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptString'
type MockAuthPrompter_PromptString_Call struct {
	*mock.Call
}

// PromptString is a helper method to define mock.On call
//   - label string
func (_e *MockAuthPrompter_Expecter) PromptString(label interface{}) *MockAuthPrompter_PromptString_Call {
	return &MockAuthPrompter_PromptString_Call{Call: _e.mock.On("PromptString", label)}
}

func (_c *MockAuthPrompter_PromptString_Call) Run(run func(label string)) *MockAuthPrompter_PromptString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthPrompter_PromptString_Call) Return(s string, err error) *MockAuthPrompter_PromptString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthPrompter_PromptString_Call) RunAndReturn(run func(label string) (string, error)) *MockAuthPrompter_PromptString_Call {
	_c.Call.Return(run)
	return _c
}
