// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/admin"
)

// NewMockQuotaAdminService creates a new instance of MockQuotaAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaAdminService {
	mock := &MockQuotaAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuotaAdminService is an autogenerated mock type for the QuotaAdminService type
type MockQuotaAdminService struct {
	mock.Mock
}

type MockQuotaAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaAdminService) EXPECT() *MockQuotaAdminService_Expecter {
	return &MockQuotaAdminService_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) Cleanup(ctx context.Context, retentionDays int) (int, error) {
	ret := _mock.Called(ctx, retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, retentionDays)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, retentionDays)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, retentionDays)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockQuotaAdminService_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
//   - retentionDays int
func (_e *MockQuotaAdminService_Expecter) Cleanup(ctx interface{}, retentionDays interface{}) *MockQuotaAdminService_Cleanup_Call {
	return &MockQuotaAdminService_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx, retentionDays)}
}

func (_c *MockQuotaAdminService_Cleanup_Call) Run(run func(ctx context.Context, retentionDays int)) *MockQuotaAdminService_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_Cleanup_Call) Return(n int, err error) *MockQuotaAdminService_Cleanup_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuotaAdminService_Cleanup_Call) RunAndReturn(run func(ctx context.Context, retentionDays int) (int, error)) *MockQuotaAdminService_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAllowance provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) CreateAllowance(ctx context.Context, userID int, source string, allowanceType string, upload int, download int, storage int, expiryDate time.Time) (*admin.QuotaAllowance, error) {
	ret := _mock.Called(ctx, userID, source, allowanceType, upload, download, storage, expiryDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateAllowance")
	}

	var r0 *admin.QuotaAllowance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, int, int, int, time.Time) (*admin.QuotaAllowance, error)); ok {
		return returnFunc(ctx, userID, source, allowanceType, upload, download, storage, expiryDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, int, int, int, time.Time) *admin.QuotaAllowance); ok {
		r0 = returnFunc(ctx, userID, source, allowanceType, upload, download, storage, expiryDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.QuotaAllowance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, string, int, int, int, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, source, allowanceType, upload, download, storage, expiryDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_CreateAllowance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAllowance'
type MockQuotaAdminService_CreateAllowance_Call struct {
	*mock.Call
}

// CreateAllowance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - source string
//   - allowanceType string
//   - upload int
//   - download int
//   - storage int
//   - expiryDate time.Time
func (_e *MockQuotaAdminService_Expecter) CreateAllowance(ctx interface{}, userID interface{}, source interface{}, allowanceType interface{}, upload interface{}, download interface{}, storage interface{}, expiryDate interface{}) *MockQuotaAdminService_CreateAllowance_Call {
	return &MockQuotaAdminService_CreateAllowance_Call{Call: _e.mock.On("CreateAllowance", ctx, userID, source, allowanceType, upload, download, storage, expiryDate)}
}

func (_c *MockQuotaAdminService_CreateAllowance_Call) Run(run func(ctx context.Context, userID int, source string, allowanceType string, upload int, download int, storage int, expiryDate time.Time)) *MockQuotaAdminService_CreateAllowance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 time.Time
		if args[7] != nil {
			arg7 = args[7].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_CreateAllowance_Call) Return(quotaAllowance *admin.QuotaAllowance, err error) *MockQuotaAdminService_CreateAllowance_Call {
	_c.Call.Return(quotaAllowance, err)
	return _c
}

func (_c *MockQuotaAdminService_CreateAllowance_Call) RunAndReturn(run func(ctx context.Context, userID int, source string, allowanceType string, upload int, download int, storage int, expiryDate time.Time) (*admin.QuotaAllowance, error)) *MockQuotaAdminService_CreateAllowance_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePlan provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) CreatePlan(ctx context.Context, plan *admin.QuotaPlan) (*admin.QuotaPlan, error) {
	ret := _mock.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlan")
	}

	var r0 *admin.QuotaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.QuotaPlan) (*admin.QuotaPlan, error)); ok {
		return returnFunc(ctx, plan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.QuotaPlan) *admin.QuotaPlan); ok {
		r0 = returnFunc(ctx, plan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.QuotaPlan) error); ok {
		r1 = returnFunc(ctx, plan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_CreatePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlan'
type MockQuotaAdminService_CreatePlan_Call struct {
	*mock.Call
}

// CreatePlan is a helper method to define mock.On call
//   - ctx context.Context
//   - plan *admin.QuotaPlan
func (_e *MockQuotaAdminService_Expecter) CreatePlan(ctx interface{}, plan interface{}) *MockQuotaAdminService_CreatePlan_Call {
	return &MockQuotaAdminService_CreatePlan_Call{Call: _e.mock.On("CreatePlan", ctx, plan)}
}

func (_c *MockQuotaAdminService_CreatePlan_Call) Run(run func(ctx context.Context, plan *admin.QuotaPlan)) *MockQuotaAdminService_CreatePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.QuotaPlan
		if args[1] != nil {
			arg1 = args[1].(*admin.QuotaPlan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_CreatePlan_Call) Return(quotaPlan *admin.QuotaPlan, err error) *MockQuotaAdminService_CreatePlan_Call {
	_c.Call.Return(quotaPlan, err)
	return _c
}

func (_c *MockQuotaAdminService_CreatePlan_Call) RunAndReturn(run func(ctx context.Context, plan *admin.QuotaPlan) (*admin.QuotaPlan, error)) *MockQuotaAdminService_CreatePlan_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllowance provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) DeleteAllowance(ctx context.Context, grantID string) error {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllowance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaAdminService_DeleteAllowance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllowance'
type MockQuotaAdminService_DeleteAllowance_Call struct {
	*mock.Call
}

// DeleteAllowance is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
func (_e *MockQuotaAdminService_Expecter) DeleteAllowance(ctx interface{}, grantID interface{}) *MockQuotaAdminService_DeleteAllowance_Call {
	return &MockQuotaAdminService_DeleteAllowance_Call{Call: _e.mock.On("DeleteAllowance", ctx, grantID)}
}

func (_c *MockQuotaAdminService_DeleteAllowance_Call) Run(run func(ctx context.Context, grantID string)) *MockQuotaAdminService_DeleteAllowance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_DeleteAllowance_Call) Return(err error) *MockQuotaAdminService_DeleteAllowance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaAdminService_DeleteAllowance_Call) RunAndReturn(run func(ctx context.Context, grantID string) error) *MockQuotaAdminService_DeleteAllowance_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlan provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) DeletePlan(ctx context.Context, planID string) error {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaAdminService_DeletePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlan'
type MockQuotaAdminService_DeletePlan_Call struct {
	*mock.Call
}

// DeletePlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
func (_e *MockQuotaAdminService_Expecter) DeletePlan(ctx interface{}, planID interface{}) *MockQuotaAdminService_DeletePlan_Call {
	return &MockQuotaAdminService_DeletePlan_Call{Call: _e.mock.On("DeletePlan", ctx, planID)}
}

func (_c *MockQuotaAdminService_DeletePlan_Call) Run(run func(ctx context.Context, planID string)) *MockQuotaAdminService_DeletePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_DeletePlan_Call) Return(err error) *MockQuotaAdminService_DeletePlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaAdminService_DeletePlan_Call) RunAndReturn(run func(ctx context.Context, planID string) error) *MockQuotaAdminService_DeletePlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlan provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) GetPlan(ctx context.Context, planID string) (*admin.QuotaPlan, error) {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlan")
	}

	var r0 *admin.QuotaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.QuotaPlan, error)); ok {
		return returnFunc(ctx, planID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.QuotaPlan); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_GetPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlan'
type MockQuotaAdminService_GetPlan_Call struct {
	*mock.Call
}

// GetPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
func (_e *MockQuotaAdminService_Expecter) GetPlan(ctx interface{}, planID interface{}) *MockQuotaAdminService_GetPlan_Call {
	return &MockQuotaAdminService_GetPlan_Call{Call: _e.mock.On("GetPlan", ctx, planID)}
}

func (_c *MockQuotaAdminService_GetPlan_Call) Run(run func(ctx context.Context, planID string)) *MockQuotaAdminService_GetPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_GetPlan_Call) Return(quotaPlan *admin.QuotaPlan, err error) *MockQuotaAdminService_GetPlan_Call {
	_c.Call.Return(quotaPlan, err)
	return _c
}

func (_c *MockQuotaAdminService_GetPlan_Call) RunAndReturn(run func(ctx context.Context, planID string) (*admin.QuotaPlan, error)) *MockQuotaAdminService_GetPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) GetStats(ctx context.Context) (*admin.SystemStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *admin.SystemStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*admin.SystemStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *admin.SystemStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.SystemStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockQuotaAdminService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuotaAdminService_Expecter) GetStats(ctx interface{}) *MockQuotaAdminService_GetStats_Call {
	return &MockQuotaAdminService_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockQuotaAdminService_GetStats_Call) Run(run func(ctx context.Context)) *MockQuotaAdminService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_GetStats_Call) Return(systemStats *admin.SystemStats, err error) *MockQuotaAdminService_GetStats_Call {
	_c.Call.Return(systemStats, err)
	return _c
}

func (_c *MockQuotaAdminService_GetStats_Call) RunAndReturn(run func(ctx context.Context) (*admin.SystemStats, error)) *MockQuotaAdminService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllowances provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) ListAllowances(ctx context.Context) ([]*admin.QuotaAllowance, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllowances")
	}

	var r0 []*admin.QuotaAllowance
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.QuotaAllowance, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.QuotaAllowance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.QuotaAllowance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQuotaAdminService_ListAllowances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllowances'
type MockQuotaAdminService_ListAllowances_Call struct {
	*mock.Call
}

// ListAllowances is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuotaAdminService_Expecter) ListAllowances(ctx interface{}) *MockQuotaAdminService_ListAllowances_Call {
	return &MockQuotaAdminService_ListAllowances_Call{Call: _e.mock.On("ListAllowances", ctx)}
}

func (_c *MockQuotaAdminService_ListAllowances_Call) Run(run func(ctx context.Context)) *MockQuotaAdminService_ListAllowances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_ListAllowances_Call) Return(quotaAllowances []*admin.QuotaAllowance, n int, err error) *MockQuotaAdminService_ListAllowances_Call {
	_c.Call.Return(quotaAllowances, n, err)
	return _c
}

func (_c *MockQuotaAdminService_ListAllowances_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.QuotaAllowance, int, error)) *MockQuotaAdminService_ListAllowances_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlans provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) ListPlans(ctx context.Context) ([]*admin.QuotaPlan, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlans")
	}

	var r0 []*admin.QuotaPlan
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.QuotaPlan, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.QuotaPlan); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQuotaAdminService_ListPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlans'
type MockQuotaAdminService_ListPlans_Call struct {
	*mock.Call
}

// ListPlans is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuotaAdminService_Expecter) ListPlans(ctx interface{}) *MockQuotaAdminService_ListPlans_Call {
	return &MockQuotaAdminService_ListPlans_Call{Call: _e.mock.On("ListPlans", ctx)}
}

func (_c *MockQuotaAdminService_ListPlans_Call) Run(run func(ctx context.Context)) *MockQuotaAdminService_ListPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_ListPlans_Call) Return(quotaPlans []*admin.QuotaPlan, n int, err error) *MockQuotaAdminService_ListPlans_Call {
	_c.Call.Return(quotaPlans, n, err)
	return _c
}

func (_c *MockQuotaAdminService_ListPlans_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.QuotaPlan, int, error)) *MockQuotaAdminService_ListPlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserConfigs provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) ListUserConfigs(ctx context.Context) ([]*admin.UserQuotaConfig, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUserConfigs")
	}

	var r0 []*admin.UserQuotaConfig
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.UserQuotaConfig, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.UserQuotaConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.UserQuotaConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQuotaAdminService_ListUserConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserConfigs'
type MockQuotaAdminService_ListUserConfigs_Call struct {
	*mock.Call
}

// ListUserConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuotaAdminService_Expecter) ListUserConfigs(ctx interface{}) *MockQuotaAdminService_ListUserConfigs_Call {
	return &MockQuotaAdminService_ListUserConfigs_Call{Call: _e.mock.On("ListUserConfigs", ctx)}
}

func (_c *MockQuotaAdminService_ListUserConfigs_Call) Run(run func(ctx context.Context)) *MockQuotaAdminService_ListUserConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_ListUserConfigs_Call) Return(userQuotaConfigs []*admin.UserQuotaConfig, n int, err error) *MockQuotaAdminService_ListUserConfigs_Call {
	_c.Call.Return(userQuotaConfigs, n, err)
	return _c
}

func (_c *MockQuotaAdminService_ListUserConfigs_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.UserQuotaConfig, int, error)) *MockQuotaAdminService_ListUserConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// Reconcile provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) Reconcile(ctx context.Context, userID *int) (string, int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 string
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int) (string, int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int) int); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *int) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQuotaAdminService_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type MockQuotaAdminService_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *int
func (_e *MockQuotaAdminService_Expecter) Reconcile(ctx interface{}, userID interface{}) *MockQuotaAdminService_Reconcile_Call {
	return &MockQuotaAdminService_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, userID)}
}

func (_c *MockQuotaAdminService_Reconcile_Call) Run(run func(ctx context.Context, userID *int)) *MockQuotaAdminService_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_Reconcile_Call) Return(s string, n int, err error) *MockQuotaAdminService_Reconcile_Call {
	_c.Call.Return(s, n, err)
	return _c
}

func (_c *MockQuotaAdminService_Reconcile_Call) RunAndReturn(run func(ctx context.Context, userID *int) (string, int, error)) *MockQuotaAdminService_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaAdminService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockQuotaAdminService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockQuotaAdminService_Expecter) RequireAuthenticated() *MockQuotaAdminService_RequireAuthenticated_Call {
	return &MockQuotaAdminService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockQuotaAdminService_RequireAuthenticated_Call) Run(run func()) *MockQuotaAdminService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuotaAdminService_RequireAuthenticated_Call) Return(err error) *MockQuotaAdminService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaAdminService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockQuotaAdminService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// ResetUserPlan provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) ResetUserPlan(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetUserPlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaAdminService_ResetUserPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetUserPlan'
type MockQuotaAdminService_ResetUserPlan_Call struct {
	*mock.Call
}

// ResetUserPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockQuotaAdminService_Expecter) ResetUserPlan(ctx interface{}, userID interface{}) *MockQuotaAdminService_ResetUserPlan_Call {
	return &MockQuotaAdminService_ResetUserPlan_Call{Call: _e.mock.On("ResetUserPlan", ctx, userID)}
}

func (_c *MockQuotaAdminService_ResetUserPlan_Call) Run(run func(ctx context.Context, userID int)) *MockQuotaAdminService_ResetUserPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_ResetUserPlan_Call) Return(err error) *MockQuotaAdminService_ResetUserPlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaAdminService_ResetUserPlan_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockQuotaAdminService_ResetUserPlan_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultPlan provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) SetDefaultPlan(ctx context.Context, planID string) error {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultPlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaAdminService_SetDefaultPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultPlan'
type MockQuotaAdminService_SetDefaultPlan_Call struct {
	*mock.Call
}

// SetDefaultPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
func (_e *MockQuotaAdminService_Expecter) SetDefaultPlan(ctx interface{}, planID interface{}) *MockQuotaAdminService_SetDefaultPlan_Call {
	return &MockQuotaAdminService_SetDefaultPlan_Call{Call: _e.mock.On("SetDefaultPlan", ctx, planID)}
}

func (_c *MockQuotaAdminService_SetDefaultPlan_Call) Run(run func(ctx context.Context, planID string)) *MockQuotaAdminService_SetDefaultPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_SetDefaultPlan_Call) Return(err error) *MockQuotaAdminService_SetDefaultPlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaAdminService_SetDefaultPlan_Call) RunAndReturn(run func(ctx context.Context, planID string) error) *MockQuotaAdminService_SetDefaultPlan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAllowance provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) UpdateAllowance(ctx context.Context, grantID string, userID int, source string, allowanceType string, upload int, download int, storage int, expiryDate time.Time) (*admin.QuotaAllowance, error) {
	ret := _mock.Called(ctx, grantID, userID, source, allowanceType, upload, download, storage, expiryDate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllowance")
	}

	var r0 *admin.QuotaAllowance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string, string, int, int, int, time.Time) (*admin.QuotaAllowance, error)); ok {
		return returnFunc(ctx, grantID, userID, source, allowanceType, upload, download, storage, expiryDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string, string, int, int, int, time.Time) *admin.QuotaAllowance); ok {
		r0 = returnFunc(ctx, grantID, userID, source, allowanceType, upload, download, storage, expiryDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.QuotaAllowance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, string, string, int, int, int, time.Time) error); ok {
		r1 = returnFunc(ctx, grantID, userID, source, allowanceType, upload, download, storage, expiryDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_UpdateAllowance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAllowance'
type MockQuotaAdminService_UpdateAllowance_Call struct {
	*mock.Call
}

// UpdateAllowance is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
//   - userID int
//   - source string
//   - allowanceType string
//   - upload int
//   - download int
//   - storage int
//   - expiryDate time.Time
func (_e *MockQuotaAdminService_Expecter) UpdateAllowance(ctx interface{}, grantID interface{}, userID interface{}, source interface{}, allowanceType interface{}, upload interface{}, download interface{}, storage interface{}, expiryDate interface{}) *MockQuotaAdminService_UpdateAllowance_Call {
	return &MockQuotaAdminService_UpdateAllowance_Call{Call: _e.mock.On("UpdateAllowance", ctx, grantID, userID, source, allowanceType, upload, download, storage, expiryDate)}
}

func (_c *MockQuotaAdminService_UpdateAllowance_Call) Run(run func(ctx context.Context, grantID string, userID int, source string, allowanceType string, upload int, download int, storage int, expiryDate time.Time)) *MockQuotaAdminService_UpdateAllowance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		var arg8 time.Time
		if args[8] != nil {
			arg8 = args[8].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_UpdateAllowance_Call) Return(quotaAllowance *admin.QuotaAllowance, err error) *MockQuotaAdminService_UpdateAllowance_Call {
	_c.Call.Return(quotaAllowance, err)
	return _c
}

func (_c *MockQuotaAdminService_UpdateAllowance_Call) RunAndReturn(run func(ctx context.Context, grantID string, userID int, source string, allowanceType string, upload int, download int, storage int, expiryDate time.Time) (*admin.QuotaAllowance, error)) *MockQuotaAdminService_UpdateAllowance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlan provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) UpdatePlan(ctx context.Context, planID string, plan *admin.QuotaPlan) (*admin.QuotaPlan, error) {
	ret := _mock.Called(ctx, planID, plan)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlan")
	}

	var r0 *admin.QuotaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.QuotaPlan) (*admin.QuotaPlan, error)); ok {
		return returnFunc(ctx, planID, plan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.QuotaPlan) *admin.QuotaPlan); ok {
		r0 = returnFunc(ctx, planID, plan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.QuotaPlan) error); ok {
		r1 = returnFunc(ctx, planID, plan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_UpdatePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlan'
type MockQuotaAdminService_UpdatePlan_Call struct {
	*mock.Call
}

// UpdatePlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - plan *admin.QuotaPlan
func (_e *MockQuotaAdminService_Expecter) UpdatePlan(ctx interface{}, planID interface{}, plan interface{}) *MockQuotaAdminService_UpdatePlan_Call {
	return &MockQuotaAdminService_UpdatePlan_Call{Call: _e.mock.On("UpdatePlan", ctx, planID, plan)}
}

func (_c *MockQuotaAdminService_UpdatePlan_Call) Run(run func(ctx context.Context, planID string, plan *admin.QuotaPlan)) *MockQuotaAdminService_UpdatePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.QuotaPlan
		if args[2] != nil {
			arg2 = args[2].(*admin.QuotaPlan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_UpdatePlan_Call) Return(quotaPlan *admin.QuotaPlan, err error) *MockQuotaAdminService_UpdatePlan_Call {
	_c.Call.Return(quotaPlan, err)
	return _c
}

func (_c *MockQuotaAdminService_UpdatePlan_Call) RunAndReturn(run func(ctx context.Context, planID string, plan *admin.QuotaPlan) (*admin.QuotaPlan, error)) *MockQuotaAdminService_UpdatePlan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserConfig provides a mock function for the type MockQuotaAdminService
func (_mock *MockQuotaAdminService) UpdateUserConfig(ctx context.Context, userID int, config *admin.UserQuotaConfigUpdate) (*admin.UserQuotaConfig, error) {
	ret := _mock.Called(ctx, userID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserConfig")
	}

	var r0 *admin.UserQuotaConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *admin.UserQuotaConfigUpdate) (*admin.UserQuotaConfig, error)); ok {
		return returnFunc(ctx, userID, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *admin.UserQuotaConfigUpdate) *admin.UserQuotaConfig); ok {
		r0 = returnFunc(ctx, userID, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.UserQuotaConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *admin.UserQuotaConfigUpdate) error); ok {
		r1 = returnFunc(ctx, userID, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaAdminService_UpdateUserConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserConfig'
type MockQuotaAdminService_UpdateUserConfig_Call struct {
	*mock.Call
}

// UpdateUserConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - config *admin.UserQuotaConfigUpdate
func (_e *MockQuotaAdminService_Expecter) UpdateUserConfig(ctx interface{}, userID interface{}, config interface{}) *MockQuotaAdminService_UpdateUserConfig_Call {
	return &MockQuotaAdminService_UpdateUserConfig_Call{Call: _e.mock.On("UpdateUserConfig", ctx, userID, config)}
}

func (_c *MockQuotaAdminService_UpdateUserConfig_Call) Run(run func(ctx context.Context, userID int, config *admin.UserQuotaConfigUpdate)) *MockQuotaAdminService_UpdateUserConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *admin.UserQuotaConfigUpdate
		if args[2] != nil {
			arg2 = args[2].(*admin.UserQuotaConfigUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuotaAdminService_UpdateUserConfig_Call) Return(userQuotaConfig *admin.UserQuotaConfig, err error) *MockQuotaAdminService_UpdateUserConfig_Call {
	_c.Call.Return(userQuotaConfig, err)
	return _c
}

func (_c *MockQuotaAdminService_UpdateUserConfig_Call) RunAndReturn(run func(ctx context.Context, userID int, config *admin.UserQuotaConfigUpdate) (*admin.UserQuotaConfig, error)) *MockQuotaAdminService_UpdateUserConfig_Call {
	_c.Call.Return(run)
	return _c
}
