// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/admin"
)

// NewMockPlatformDomainAdminService creates a new instance of MockPlatformDomainAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatformDomainAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatformDomainAdminService {
	mock := &MockPlatformDomainAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlatformDomainAdminService is an autogenerated mock type for the PlatformDomainAdminService type
type MockPlatformDomainAdminService struct {
	mock.Mock
}

type MockPlatformDomainAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatformDomainAdminService) EXPECT() *MockPlatformDomainAdminService_Expecter {
	return &MockPlatformDomainAdminService_Expecter{mock: &_m.Mock}
}

// DeletePlatformDomain provides a mock function for the type MockPlatformDomainAdminService
func (_mock *MockPlatformDomainAdminService) DeletePlatformDomain(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlatformDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatformDomainAdminService_DeletePlatformDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlatformDomain'
type MockPlatformDomainAdminService_DeletePlatformDomain_Call struct {
	*mock.Call
}

// DeletePlatformDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPlatformDomainAdminService_Expecter) DeletePlatformDomain(ctx any, id any) *MockPlatformDomainAdminService_DeletePlatformDomain_Call {
	return &MockPlatformDomainAdminService_DeletePlatformDomain_Call{Call: _e.mock.On("DeletePlatformDomain", ctx, id)}
}

func (_c *MockPlatformDomainAdminService_DeletePlatformDomain_Call) Run(run func(ctx context.Context, id string)) *MockPlatformDomainAdminService_DeletePlatformDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformDomainAdminService_DeletePlatformDomain_Call) Return(err error) *MockPlatformDomainAdminService_DeletePlatformDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatformDomainAdminService_DeletePlatformDomain_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockPlatformDomainAdminService_DeletePlatformDomain_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlatformDomains provides a mock function for the type MockPlatformDomainAdminService
func (_mock *MockPlatformDomainAdminService) ListPlatformDomains(ctx context.Context) ([]*admin.PlatformDomain, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlatformDomains")
	}

	var r0 []*admin.PlatformDomain
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.PlatformDomain, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.PlatformDomain); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.PlatformDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPlatformDomainAdminService_ListPlatformDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlatformDomains'
type MockPlatformDomainAdminService_ListPlatformDomains_Call struct {
	*mock.Call
}

// ListPlatformDomains is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPlatformDomainAdminService_Expecter) ListPlatformDomains(ctx any) *MockPlatformDomainAdminService_ListPlatformDomains_Call {
	return &MockPlatformDomainAdminService_ListPlatformDomains_Call{Call: _e.mock.On("ListPlatformDomains", ctx)}
}

func (_c *MockPlatformDomainAdminService_ListPlatformDomains_Call) Run(run func(ctx context.Context)) *MockPlatformDomainAdminService_ListPlatformDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatformDomainAdminService_ListPlatformDomains_Call) Return(platformDomains []*admin.PlatformDomain, n int, err error) *MockPlatformDomainAdminService_ListPlatformDomains_Call {
	_c.Call.Return(platformDomains, n, err)
	return _c
}

func (_c *MockPlatformDomainAdminService_ListPlatformDomains_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.PlatformDomain, int, error)) *MockPlatformDomainAdminService_ListPlatformDomains_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPlatformDomain provides a mock function for the type MockPlatformDomainAdminService
func (_mock *MockPlatformDomainAdminService) RegisterPlatformDomain(ctx context.Context, req *admin.PlatformDomainRequest) (*admin.PlatformDomain, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterPlatformDomain")
	}

	var r0 *admin.PlatformDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PlatformDomainRequest) (*admin.PlatformDomain, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PlatformDomainRequest) *admin.PlatformDomain); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PlatformDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.PlatformDomainRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformDomainAdminService_RegisterPlatformDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPlatformDomain'
type MockPlatformDomainAdminService_RegisterPlatformDomain_Call struct {
	*mock.Call
}

// RegisterPlatformDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - req *admin.PlatformDomainRequest
func (_e *MockPlatformDomainAdminService_Expecter) RegisterPlatformDomain(ctx any, req any) *MockPlatformDomainAdminService_RegisterPlatformDomain_Call {
	return &MockPlatformDomainAdminService_RegisterPlatformDomain_Call{Call: _e.mock.On("RegisterPlatformDomain", ctx, req)}
}

func (_c *MockPlatformDomainAdminService_RegisterPlatformDomain_Call) Run(run func(ctx context.Context, req *admin.PlatformDomainRequest)) *MockPlatformDomainAdminService_RegisterPlatformDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.PlatformDomainRequest
		if args[1] != nil {
			arg1 = args[1].(*admin.PlatformDomainRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformDomainAdminService_RegisterPlatformDomain_Call) Return(platformDomain *admin.PlatformDomain, err error) *MockPlatformDomainAdminService_RegisterPlatformDomain_Call {
	_c.Call.Return(platformDomain, err)
	return _c
}

func (_c *MockPlatformDomainAdminService_RegisterPlatformDomain_Call) RunAndReturn(run func(ctx context.Context, req *admin.PlatformDomainRequest) (*admin.PlatformDomain, error)) *MockPlatformDomainAdminService_RegisterPlatformDomain_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockPlatformDomainAdminService
func (_mock *MockPlatformDomainAdminService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatformDomainAdminService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockPlatformDomainAdminService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockPlatformDomainAdminService_Expecter) RequireAuthenticated() *MockPlatformDomainAdminService_RequireAuthenticated_Call {
	return &MockPlatformDomainAdminService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockPlatformDomainAdminService_RequireAuthenticated_Call) Run(run func()) *MockPlatformDomainAdminService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatformDomainAdminService_RequireAuthenticated_Call) Return(err error) *MockPlatformDomainAdminService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatformDomainAdminService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockPlatformDomainAdminService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlatformDomain provides a mock function for the type MockPlatformDomainAdminService
func (_mock *MockPlatformDomainAdminService) UpdatePlatformDomain(ctx context.Context, id string, req *admin.PlatformDomainUpdateRequest) (*admin.PlatformDomain, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlatformDomain")
	}

	var r0 *admin.PlatformDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PlatformDomainUpdateRequest) (*admin.PlatformDomain, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PlatformDomainUpdateRequest) *admin.PlatformDomain); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PlatformDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.PlatformDomainUpdateRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformDomainAdminService_UpdatePlatformDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlatformDomain'
type MockPlatformDomainAdminService_UpdatePlatformDomain_Call struct {
	*mock.Call
}

// UpdatePlatformDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *admin.PlatformDomainUpdateRequest
func (_e *MockPlatformDomainAdminService_Expecter) UpdatePlatformDomain(ctx any, id any, req any) *MockPlatformDomainAdminService_UpdatePlatformDomain_Call {
	return &MockPlatformDomainAdminService_UpdatePlatformDomain_Call{Call: _e.mock.On("UpdatePlatformDomain", ctx, id, req)}
}

func (_c *MockPlatformDomainAdminService_UpdatePlatformDomain_Call) Run(run func(ctx context.Context, id string, req *admin.PlatformDomainUpdateRequest)) *MockPlatformDomainAdminService_UpdatePlatformDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.PlatformDomainUpdateRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.PlatformDomainUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlatformDomainAdminService_UpdatePlatformDomain_Call) Return(platformDomain *admin.PlatformDomain, err error) *MockPlatformDomainAdminService_UpdatePlatformDomain_Call {
	_c.Call.Return(platformDomain, err)
	return _c
}

func (_c *MockPlatformDomainAdminService_UpdatePlatformDomain_Call) RunAndReturn(run func(ctx context.Context, id string, req *admin.PlatformDomainUpdateRequest) (*admin.PlatformDomain, error)) *MockPlatformDomainAdminService_UpdatePlatformDomain_Call {
	_c.Call.Return(run)
	return _c
}
