// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/admin"
)

// NewMockProfilingAdminService creates a new instance of MockProfilingAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfilingAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfilingAdminService {
	mock := &MockProfilingAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfilingAdminService is an autogenerated mock type for the ProfilingAdminService type
type MockProfilingAdminService struct {
	mock.Mock
}

type MockProfilingAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfilingAdminService) EXPECT() *MockProfilingAdminService_Expecter {
	return &MockProfilingAdminService_Expecter{mock: &_m.Mock}
}

// GetBlockProfile provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetBlockProfile(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockProfile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetBlockProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockProfile'
type MockProfilingAdminService_GetBlockProfile_Call struct {
	*mock.Call
}

// GetBlockProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetBlockProfile(ctx interface{}) *MockProfilingAdminService_GetBlockProfile_Call {
	return &MockProfilingAdminService_GetBlockProfile_Call{Call: _e.mock.On("GetBlockProfile", ctx)}
}

func (_c *MockProfilingAdminService_GetBlockProfile_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetBlockProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetBlockProfile_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetBlockProfile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetBlockProfile_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetBlockProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetCPUProfile provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetCPUProfile(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCPUProfile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetCPUProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCPUProfile'
type MockProfilingAdminService_GetCPUProfile_Call struct {
	*mock.Call
}

// GetCPUProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetCPUProfile(ctx interface{}) *MockProfilingAdminService_GetCPUProfile_Call {
	return &MockProfilingAdminService_GetCPUProfile_Call{Call: _e.mock.On("GetCPUProfile", ctx)}
}

func (_c *MockProfilingAdminService_GetCPUProfile_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetCPUProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetCPUProfile_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetCPUProfile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetCPUProfile_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetCPUProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetCmdline provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetCmdline(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCmdline")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetCmdline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCmdline'
type MockProfilingAdminService_GetCmdline_Call struct {
	*mock.Call
}

// GetCmdline is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetCmdline(ctx interface{}) *MockProfilingAdminService_GetCmdline_Call {
	return &MockProfilingAdminService_GetCmdline_Call{Call: _e.mock.On("GetCmdline", ctx)}
}

func (_c *MockProfilingAdminService_GetCmdline_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetCmdline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetCmdline_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetCmdline_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetCmdline_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetCmdline_Call {
	_c.Call.Return(run)
	return _c
}

// GetGoroutineProfile provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetGoroutineProfile(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGoroutineProfile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetGoroutineProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoroutineProfile'
type MockProfilingAdminService_GetGoroutineProfile_Call struct {
	*mock.Call
}

// GetGoroutineProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetGoroutineProfile(ctx interface{}) *MockProfilingAdminService_GetGoroutineProfile_Call {
	return &MockProfilingAdminService_GetGoroutineProfile_Call{Call: _e.mock.On("GetGoroutineProfile", ctx)}
}

func (_c *MockProfilingAdminService_GetGoroutineProfile_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetGoroutineProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetGoroutineProfile_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetGoroutineProfile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetGoroutineProfile_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetGoroutineProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeapProfile provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetHeapProfile(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHeapProfile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetHeapProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeapProfile'
type MockProfilingAdminService_GetHeapProfile_Call struct {
	*mock.Call
}

// GetHeapProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetHeapProfile(ctx interface{}) *MockProfilingAdminService_GetHeapProfile_Call {
	return &MockProfilingAdminService_GetHeapProfile_Call{Call: _e.mock.On("GetHeapProfile", ctx)}
}

func (_c *MockProfilingAdminService_GetHeapProfile_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetHeapProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetHeapProfile_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetHeapProfile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetHeapProfile_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetHeapProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetMutexProfile provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetMutexProfile(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMutexProfile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetMutexProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMutexProfile'
type MockProfilingAdminService_GetMutexProfile_Call struct {
	*mock.Call
}

// GetMutexProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetMutexProfile(ctx interface{}) *MockProfilingAdminService_GetMutexProfile_Call {
	return &MockProfilingAdminService_GetMutexProfile_Call{Call: _e.mock.On("GetMutexProfile", ctx)}
}

func (_c *MockProfilingAdminService_GetMutexProfile_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetMutexProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetMutexProfile_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetMutexProfile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetMutexProfile_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetMutexProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileIndex provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetProfileIndex(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileIndex")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetProfileIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileIndex'
type MockProfilingAdminService_GetProfileIndex_Call struct {
	*mock.Call
}

// GetProfileIndex is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetProfileIndex(ctx interface{}) *MockProfilingAdminService_GetProfileIndex_Call {
	return &MockProfilingAdminService_GetProfileIndex_Call{Call: _e.mock.On("GetProfileIndex", ctx)}
}

func (_c *MockProfilingAdminService_GetProfileIndex_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetProfileIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetProfileIndex_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetProfileIndex_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetProfileIndex_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetProfileIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetStatus(ctx context.Context) (*admin.ProfilingStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *admin.ProfilingStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*admin.ProfilingStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *admin.ProfilingStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ProfilingStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockProfilingAdminService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetStatus(ctx interface{}) *MockProfilingAdminService_GetStatus_Call {
	return &MockProfilingAdminService_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *MockProfilingAdminService_GetStatus_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetStatus_Call) Return(profilingStatus *admin.ProfilingStatus, err error) *MockProfilingAdminService_GetStatus_Call {
	_c.Call.Return(profilingStatus, err)
	return _c
}

func (_c *MockProfilingAdminService_GetStatus_Call) RunAndReturn(run func(ctx context.Context) (*admin.ProfilingStatus, error)) *MockProfilingAdminService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetSymbol provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetSymbol(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSymbol")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSymbol'
type MockProfilingAdminService_GetSymbol_Call struct {
	*mock.Call
}

// GetSymbol is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetSymbol(ctx interface{}) *MockProfilingAdminService_GetSymbol_Call {
	return &MockProfilingAdminService_GetSymbol_Call{Call: _e.mock.On("GetSymbol", ctx)}
}

func (_c *MockProfilingAdminService_GetSymbol_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetSymbol_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetSymbol_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetSymbol_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// GetThreadcreate provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetThreadcreate(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetThreadcreate")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetThreadcreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThreadcreate'
type MockProfilingAdminService_GetThreadcreate_Call struct {
	*mock.Call
}

// GetThreadcreate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetThreadcreate(ctx interface{}) *MockProfilingAdminService_GetThreadcreate_Call {
	return &MockProfilingAdminService_GetThreadcreate_Call{Call: _e.mock.On("GetThreadcreate", ctx)}
}

func (_c *MockProfilingAdminService_GetThreadcreate_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetThreadcreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetThreadcreate_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetThreadcreate_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetThreadcreate_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetThreadcreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrace provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) GetTrace(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTrace")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilingAdminService_GetTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrace'
type MockProfilingAdminService_GetTrace_Call struct {
	*mock.Call
}

// GetTrace is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfilingAdminService_Expecter) GetTrace(ctx interface{}) *MockProfilingAdminService_GetTrace_Call {
	return &MockProfilingAdminService_GetTrace_Call{Call: _e.mock.On("GetTrace", ctx)}
}

func (_c *MockProfilingAdminService_GetTrace_Call) Run(run func(ctx context.Context)) *MockProfilingAdminService_GetTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_GetTrace_Call) Return(bytes []byte, err error) *MockProfilingAdminService_GetTrace_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProfilingAdminService_GetTrace_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockProfilingAdminService_GetTrace_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfilingAdminService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockProfilingAdminService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockProfilingAdminService_Expecter) RequireAuthenticated() *MockProfilingAdminService_RequireAuthenticated_Call {
	return &MockProfilingAdminService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockProfilingAdminService_RequireAuthenticated_Call) Run(run func()) *MockProfilingAdminService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProfilingAdminService_RequireAuthenticated_Call) Return(err error) *MockProfilingAdminService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfilingAdminService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockProfilingAdminService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// SetBlockProfileRate provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) SetBlockProfileRate(ctx context.Context, rate int) error {
	ret := _mock.Called(ctx, rate)

	if len(ret) == 0 {
		panic("no return value specified for SetBlockProfileRate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, rate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfilingAdminService_SetBlockProfileRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBlockProfileRate'
type MockProfilingAdminService_SetBlockProfileRate_Call struct {
	*mock.Call
}

// SetBlockProfileRate is a helper method to define mock.On call
//   - ctx context.Context
//   - rate int
func (_e *MockProfilingAdminService_Expecter) SetBlockProfileRate(ctx interface{}, rate interface{}) *MockProfilingAdminService_SetBlockProfileRate_Call {
	return &MockProfilingAdminService_SetBlockProfileRate_Call{Call: _e.mock.On("SetBlockProfileRate", ctx, rate)}
}

func (_c *MockProfilingAdminService_SetBlockProfileRate_Call) Run(run func(ctx context.Context, rate int)) *MockProfilingAdminService_SetBlockProfileRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_SetBlockProfileRate_Call) Return(err error) *MockProfilingAdminService_SetBlockProfileRate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfilingAdminService_SetBlockProfileRate_Call) RunAndReturn(run func(ctx context.Context, rate int) error) *MockProfilingAdminService_SetBlockProfileRate_Call {
	_c.Call.Return(run)
	return _c
}

// SetMutexProfileFraction provides a mock function for the type MockProfilingAdminService
func (_mock *MockProfilingAdminService) SetMutexProfileFraction(ctx context.Context, fraction int) error {
	ret := _mock.Called(ctx, fraction)

	if len(ret) == 0 {
		panic("no return value specified for SetMutexProfileFraction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, fraction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfilingAdminService_SetMutexProfileFraction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMutexProfileFraction'
type MockProfilingAdminService_SetMutexProfileFraction_Call struct {
	*mock.Call
}

// SetMutexProfileFraction is a helper method to define mock.On call
//   - ctx context.Context
//   - fraction int
func (_e *MockProfilingAdminService_Expecter) SetMutexProfileFraction(ctx interface{}, fraction interface{}) *MockProfilingAdminService_SetMutexProfileFraction_Call {
	return &MockProfilingAdminService_SetMutexProfileFraction_Call{Call: _e.mock.On("SetMutexProfileFraction", ctx, fraction)}
}

func (_c *MockProfilingAdminService_SetMutexProfileFraction_Call) Run(run func(ctx context.Context, fraction int)) *MockProfilingAdminService_SetMutexProfileFraction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfilingAdminService_SetMutexProfileFraction_Call) Return(err error) *MockProfilingAdminService_SetMutexProfileFraction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfilingAdminService_SetMutexProfileFraction_Call) RunAndReturn(run func(ctx context.Context, fraction int) error) *MockProfilingAdminService_SetMutexProfileFraction_Call {
	_c.Call.Return(run)
	return _c
}
