// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/pinner-cli/internal/core/uploads"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the Service type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Upload(ctx context.Context, filesystem fs.FS, name string, wait bool, wrap bool) (*uploads.UploadResult, error) {
	ret := _mock.Called(ctx, filesystem, name, wait, wrap)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *uploads.UploadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, fs.FS, string, bool, bool) (*uploads.UploadResult, error)); ok {
		return returnFunc(ctx, filesystem, name, wait, wrap)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, fs.FS, string, bool, bool) *uploads.UploadResult); ok {
		r0 = returnFunc(ctx, filesystem, name, wait, wrap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uploads.UploadResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, fs.FS, string, bool, bool) error); ok {
		r1 = returnFunc(ctx, filesystem, name, wait, wrap)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockUploadService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - filesystem fs.FS
//   - name string
//   - wait bool
//   - wrap bool
func (_e *MockUploadService_Expecter) Upload(ctx interface{}, filesystem interface{}, name interface{}, wait interface{}, wrap interface{}) *MockUploadService_Upload_Call {
	return &MockUploadService_Upload_Call{Call: _e.mock.On("Upload", ctx, filesystem, name, wait, wrap)}
}

func (_c *MockUploadService_Upload_Call) Run(run func(ctx context.Context, filesystem fs.FS, name string, wait bool, wrap bool)) *MockUploadService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fs.FS
		if args[1] != nil {
			arg1 = args[1].(fs.FS)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUploadService_Upload_Call) Return(uploadResult *uploads.UploadResult, err error) *MockUploadService_Upload_Call {
	_c.Call.Return(uploadResult, err)
	return _c
}

func (_c *MockUploadService_Upload_Call) RunAndReturn(run func(ctx context.Context, filesystem fs.FS, name string, wait bool, wrap bool) (*uploads.UploadResult, error)) *MockUploadService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
