// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/pinner-cli/internal/core/operations"
)

// NewMockOperationsService creates a new instance of MockOperationsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationsService {
	mock := &MockOperationsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationsService is an autogenerated mock type for the Service type
type MockOperationsService struct {
	mock.Mock
}

type MockOperationsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationsService) EXPECT() *MockOperationsService_Expecter {
	return &MockOperationsService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockOperationsService
func (_mock *MockOperationsService) Get(ctx context.Context, id int64) (*operations.OperationDetail, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *operations.OperationDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*operations.OperationDetail, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *operations.OperationDetail); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.OperationDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOperationsService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockOperationsService_Expecter) Get(ctx interface{}, id interface{}) *MockOperationsService_Get_Call {
	return &MockOperationsService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOperationsService_Get_Call) Run(run func(ctx context.Context, id int64)) *MockOperationsService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationsService_Get_Call) Return(operationDetail *operations.OperationDetail, err error) *MockOperationsService_Get_Call {
	_c.Call.Return(operationDetail, err)
	return _c
}

func (_c *MockOperationsService_Get_Call) RunAndReturn(run func(ctx context.Context, id int64) (*operations.OperationDetail, error)) *MockOperationsService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOperationsService
func (_mock *MockOperationsService) List(ctx context.Context, opts operations.ListOptions) (*operations.OperationsListResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *operations.OperationsListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListOptions) (*operations.OperationsListResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListOptions) *operations.OperationsListResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.OperationsListResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOperationsService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts operations.ListOptions
func (_e *MockOperationsService_Expecter) List(ctx interface{}, opts interface{}) *MockOperationsService_List_Call {
	return &MockOperationsService_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockOperationsService_List_Call) Run(run func(ctx context.Context, opts operations.ListOptions)) *MockOperationsService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListOptions
		if args[1] != nil {
			arg1 = args[1].(operations.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationsService_List_Call) Return(operationsListResult *operations.OperationsListResult, err error) *MockOperationsService_List_Call {
	_c.Call.Return(operationsListResult, err)
	return _c
}

func (_c *MockOperationsService_List_Call) RunAndReturn(run func(ctx context.Context, opts operations.ListOptions) (*operations.OperationsListResult, error)) *MockOperationsService_List_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockOperationsService
func (_mock *MockOperationsService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockOperationsService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockOperationsService_Expecter) RequireAuthenticated() *MockOperationsService_RequireAuthenticated_Call {
	return &MockOperationsService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockOperationsService_RequireAuthenticated_Call) Run(run func()) *MockOperationsService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperationsService_RequireAuthenticated_Call) Return(err error) *MockOperationsService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockOperationsService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockOperationsService
func (_mock *MockOperationsService) Watch(ctx context.Context, id int64) (*operations.OperationDetail, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 *operations.OperationDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*operations.OperationDetail, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *operations.OperationDetail); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.OperationDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsService_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockOperationsService_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockOperationsService_Expecter) Watch(ctx interface{}, id interface{}) *MockOperationsService_Watch_Call {
	return &MockOperationsService_Watch_Call{Call: _e.mock.On("Watch", ctx, id)}
}

func (_c *MockOperationsService_Watch_Call) Run(run func(ctx context.Context, id int64)) *MockOperationsService_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationsService_Watch_Call) Return(operationDetail *operations.OperationDetail, err error) *MockOperationsService_Watch_Call {
	_c.Call.Return(operationDetail, err)
	return _c
}

func (_c *MockOperationsService_Watch_Call) RunAndReturn(run func(ctx context.Context, id int64) (*operations.OperationDetail, error)) *MockOperationsService_Watch_Call {
	_c.Call.Return(run)
	return _c
}
