// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusService creates a new instance of MockStatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusService {
	mock := &MockStatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusService is an autogenerated mock type for the StatusService type
type MockStatusService struct {
	mock.Mock
}

type MockStatusService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusService) EXPECT() *MockStatusService_Expecter {
	return &MockStatusService_Expecter{mock: &_m.Mock}
}

// RequireAuthenticated provides a mock function for the type MockStatusService
func (_mock *MockStatusService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatusService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockStatusService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockStatusService_Expecter) RequireAuthenticated() *MockStatusService_RequireAuthenticated_Call {
	return &MockStatusService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockStatusService_RequireAuthenticated_Call) Run(run func()) *MockStatusService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatusService_RequireAuthenticated_Call) Return(err error) *MockStatusService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatusService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockStatusService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockStatusService
func (_mock *MockStatusService) Status(ctx context.Context, cid string, watch bool) (*PinStatus, *OperationStatusResult, error) {
	ret := _mock.Called(ctx, cid, watch)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *PinStatus
	var r1 *OperationStatusResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*PinStatus, *OperationStatusResult, error)); ok {
		return returnFunc(ctx, cid, watch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *PinStatus); ok {
		r0 = returnFunc(ctx, cid, watch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PinStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) *OperationStatusResult); ok {
		r1 = returnFunc(ctx, cid, watch)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*OperationStatusResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, bool) error); ok {
		r2 = returnFunc(ctx, cid, watch)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStatusService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockStatusService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - watch bool
func (_e *MockStatusService_Expecter) Status(ctx interface{}, cid interface{}, watch interface{}) *MockStatusService_Status_Call {
	return &MockStatusService_Status_Call{Call: _e.mock.On("Status", ctx, cid, watch)}
}

func (_c *MockStatusService_Status_Call) Run(run func(ctx context.Context, cid string, watch bool)) *MockStatusService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStatusService_Status_Call) Return(pinStatus *PinStatus, operationStatusResult *OperationStatusResult, err error) *MockStatusService_Status_Call {
	_c.Call.Return(pinStatus, operationStatusResult, err)
	return _c
}

func (_c *MockStatusService_Status_Call) RunAndReturn(run func(ctx context.Context, cid string, watch bool) (*PinStatus, *OperationStatusResult, error)) *MockStatusService_Status_Call {
	_c.Call.Return(run)
	return _c
}
