// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDownloadService creates a new instance of MockDownloadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDownloadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDownloadService {
	mock := &MockDownloadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDownloadService is an autogenerated mock type for the DownloadService type
type MockDownloadService struct {
	mock.Mock
}

type MockDownloadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDownloadService) EXPECT() *MockDownloadService_Expecter {
	return &MockDownloadService_Expecter{mock: &_m.Mock}
}

// Cat provides a mock function for the type MockDownloadService
func (_mock *MockDownloadService) Cat(ctx context.Context, ipfsPath string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, ipfsPath)

	if len(ret) == 0 {
		panic("no return value specified for Cat")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, ipfsPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, ipfsPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ipfsPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDownloadService_Cat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cat'
type MockDownloadService_Cat_Call struct {
	*mock.Call
}

// Cat is a helper method to define mock.On call
//   - ctx context.Context
//   - ipfsPath string
func (_e *MockDownloadService_Expecter) Cat(ctx interface{}, ipfsPath interface{}) *MockDownloadService_Cat_Call {
	return &MockDownloadService_Cat_Call{Call: _e.mock.On("Cat", ctx, ipfsPath)}
}

func (_c *MockDownloadService_Cat_Call) Run(run func(ctx context.Context, ipfsPath string)) *MockDownloadService_Cat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDownloadService_Cat_Call) Return(readCloser io.ReadCloser, err error) *MockDownloadService_Cat_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockDownloadService_Cat_Call) RunAndReturn(run func(ctx context.Context, ipfsPath string) (io.ReadCloser, error)) *MockDownloadService_Cat_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type MockDownloadService
func (_mock *MockDownloadService) Download(ctx context.Context, ipfsPath string, outputPath string, force bool) (*DownloadResult, error) {
	ret := _mock.Called(ctx, ipfsPath, outputPath, force)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *DownloadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*DownloadResult, error)); ok {
		return returnFunc(ctx, ipfsPath, outputPath, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *DownloadResult); ok {
		r0 = returnFunc(ctx, ipfsPath, outputPath, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DownloadResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, ipfsPath, outputPath, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDownloadService_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockDownloadService_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - ipfsPath string
//   - outputPath string
//   - force bool
func (_e *MockDownloadService_Expecter) Download(ctx interface{}, ipfsPath interface{}, outputPath interface{}, force interface{}) *MockDownloadService_Download_Call {
	return &MockDownloadService_Download_Call{Call: _e.mock.On("Download", ctx, ipfsPath, outputPath, force)}
}

func (_c *MockDownloadService_Download_Call) Run(run func(ctx context.Context, ipfsPath string, outputPath string, force bool)) *MockDownloadService_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDownloadService_Download_Call) Return(downloadResult *DownloadResult, err error) *MockDownloadService_Download_Call {
	_c.Call.Return(downloadResult, err)
	return _c
}

func (_c *MockDownloadService_Download_Call) RunAndReturn(run func(ctx context.Context, ipfsPath string, outputPath string, force bool) (*DownloadResult, error)) *MockDownloadService_Download_Call {
	_c.Call.Return(run)
	return _c
}

// FileSize provides a mock function for the type MockDownloadService
func (_mock *MockDownloadService) FileSize(ctx context.Context, ipfsPath string) (int64, error) {
	ret := _mock.Called(ctx, ipfsPath)

	if len(ret) == 0 {
		panic("no return value specified for FileSize")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, ipfsPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, ipfsPath)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ipfsPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDownloadService_FileSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileSize'
type MockDownloadService_FileSize_Call struct {
	*mock.Call
}

// FileSize is a helper method to define mock.On call
//   - ctx context.Context
//   - ipfsPath string
func (_e *MockDownloadService_Expecter) FileSize(ctx interface{}, ipfsPath interface{}) *MockDownloadService_FileSize_Call {
	return &MockDownloadService_FileSize_Call{Call: _e.mock.On("FileSize", ctx, ipfsPath)}
}

func (_c *MockDownloadService_FileSize_Call) Run(run func(ctx context.Context, ipfsPath string)) *MockDownloadService_FileSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDownloadService_FileSize_Call) Return(n int64, err error) *MockDownloadService_FileSize_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDownloadService_FileSize_Call) RunAndReturn(run func(ctx context.Context, ipfsPath string) (int64, error)) *MockDownloadService_FileSize_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirectory provides a mock function for the type MockDownloadService
func (_mock *MockDownloadService) ListDirectory(ctx context.Context, ipfsPath string) ([]DirEntry, error) {
	ret := _mock.Called(ctx, ipfsPath)

	if len(ret) == 0 {
		panic("no return value specified for ListDirectory")
	}

	var r0 []DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]DirEntry, error)); ok {
		return returnFunc(ctx, ipfsPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []DirEntry); ok {
		r0 = returnFunc(ctx, ipfsPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ipfsPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDownloadService_ListDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirectory'
type MockDownloadService_ListDirectory_Call struct {
	*mock.Call
}

// ListDirectory is a helper method to define mock.On call
//   - ctx context.Context
//   - ipfsPath string
func (_e *MockDownloadService_Expecter) ListDirectory(ctx interface{}, ipfsPath interface{}) *MockDownloadService_ListDirectory_Call {
	return &MockDownloadService_ListDirectory_Call{Call: _e.mock.On("ListDirectory", ctx, ipfsPath)}
}

func (_c *MockDownloadService_ListDirectory_Call) Run(run func(ctx context.Context, ipfsPath string)) *MockDownloadService_ListDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDownloadService_ListDirectory_Call) Return(dirEntrys []DirEntry, err error) *MockDownloadService_ListDirectory_Call {
	_c.Call.Return(dirEntrys, err)
	return _c
}

func (_c *MockDownloadService_ListDirectory_Call) RunAndReturn(run func(ctx context.Context, ipfsPath string) ([]DirEntry, error)) *MockDownloadService_ListDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockDownloadService
func (_mock *MockDownloadService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDownloadService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockDownloadService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockDownloadService_Expecter) RequireAuthenticated() *MockDownloadService_RequireAuthenticated_Call {
	return &MockDownloadService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockDownloadService_RequireAuthenticated_Call) Run(run func()) *MockDownloadService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadService_RequireAuthenticated_Call) Return(err error) *MockDownloadService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDownloadService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockDownloadService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}
