// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/pinner-cli/internal/core/auth"
	"go.lumeweb.com/portal-sdk"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// CompleteLogin provides a mock function for the type MockAuthService
func (_mock *MockAuthService) CompleteLogin(ctx context.Context, token string, keyName string, noCreateKey bool) (*auth.LoginCompleteResult, error) {
	ret := _mock.Called(ctx, token, keyName, noCreateKey)

	if len(ret) == 0 {
		panic("no return value specified for CompleteLogin")
	}

	var r0 *auth.LoginCompleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*auth.LoginCompleteResult, error)); ok {
		return returnFunc(ctx, token, keyName, noCreateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *auth.LoginCompleteResult); ok {
		r0 = returnFunc(ctx, token, keyName, noCreateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginCompleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, token, keyName, noCreateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_CompleteLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteLogin'
type MockAuthService_CompleteLogin_Call struct {
	*mock.Call
}

// CompleteLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - keyName string
//   - noCreateKey bool
func (_e *MockAuthService_Expecter) CompleteLogin(ctx interface{}, token interface{}, keyName interface{}, noCreateKey interface{}) *MockAuthService_CompleteLogin_Call {
	return &MockAuthService_CompleteLogin_Call{Call: _e.mock.On("CompleteLogin", ctx, token, keyName, noCreateKey)}
}

func (_c *MockAuthService_CompleteLogin_Call) Run(run func(ctx context.Context, token string, keyName string, noCreateKey bool)) *MockAuthService_CompleteLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthService_CompleteLogin_Call) Return(loginCompleteResult *auth.LoginCompleteResult, err error) *MockAuthService_CompleteLogin_Call {
	_c.Call.Return(loginCompleteResult, err)
	return _c
}

func (_c *MockAuthService_CompleteLogin_Call) RunAndReturn(run func(ctx context.Context, token string, keyName string, noCreateKey bool) (*auth.LoginCompleteResult, error)) *MockAuthService_CompleteLogin_Call {
	_c.Call.Return(run)
	return _c
}

// DisableOTP provides a mock function for the type MockAuthService
func (_mock *MockAuthService) DisableOTP(ctx context.Context, password string) (*auth.DisableOTPResult, error) {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for DisableOTP")
	}

	var r0 *auth.DisableOTPResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.DisableOTPResult, error)); ok {
		return returnFunc(ctx, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.DisableOTPResult); ok {
		r0 = returnFunc(ctx, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.DisableOTPResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_DisableOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableOTP'
type MockAuthService_DisableOTP_Call struct {
	*mock.Call
}

// DisableOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *MockAuthService_Expecter) DisableOTP(ctx interface{}, password interface{}) *MockAuthService_DisableOTP_Call {
	return &MockAuthService_DisableOTP_Call{Call: _e.mock.On("DisableOTP", ctx, password)}
}

func (_c *MockAuthService_DisableOTP_Call) Run(run func(ctx context.Context, password string)) *MockAuthService_DisableOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_DisableOTP_Call) Return(disableOTPResult *auth.DisableOTPResult, err error) *MockAuthService_DisableOTP_Call {
	_c.Call.Return(disableOTPResult, err)
	return _c
}

func (_c *MockAuthService_DisableOTP_Call) RunAndReturn(run func(ctx context.Context, password string) (*auth.DisableOTPResult, error)) *MockAuthService_DisableOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateOTPSecret provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GenerateOTPSecret(ctx context.Context) (*auth.OTPSecretResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTPSecret")
	}

	var r0 *auth.OTPSecretResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*auth.OTPSecretResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *auth.OTPSecretResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.OTPSecretResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GenerateOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTPSecret'
type MockAuthService_GenerateOTPSecret_Call struct {
	*mock.Call
}

// GenerateOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthService_Expecter) GenerateOTPSecret(ctx interface{}) *MockAuthService_GenerateOTPSecret_Call {
	return &MockAuthService_GenerateOTPSecret_Call{Call: _e.mock.On("GenerateOTPSecret", ctx)}
}

func (_c *MockAuthService_GenerateOTPSecret_Call) Run(run func(ctx context.Context)) *MockAuthService_GenerateOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GenerateOTPSecret_Call) Return(oTPSecretResult *auth.OTPSecretResult, err error) *MockAuthService_GenerateOTPSecret_Call {
	_c.Call.Return(oTPSecretResult, err)
	return _c
}

func (_c *MockAuthService_GenerateOTPSecret_Call) RunAndReturn(run func(ctx context.Context) (*auth.OTPSecretResult, error)) *MockAuthService_GenerateOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIEndpoint provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetAPIEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAPIEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthService_GetAPIEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIEndpoint'
type MockAuthService_GetAPIEndpoint_Call struct {
	*mock.Call
}

// GetAPIEndpoint is a helper method to define mock.On call
func (_e *MockAuthService_Expecter) GetAPIEndpoint() *MockAuthService_GetAPIEndpoint_Call {
	return &MockAuthService_GetAPIEndpoint_Call{Call: _e.mock.On("GetAPIEndpoint")}
}

func (_c *MockAuthService_GetAPIEndpoint_Call) Run(run func()) *MockAuthService_GetAPIEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthService_GetAPIEndpoint_Call) Return(s string) *MockAuthService_GetAPIEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthService_GetAPIEndpoint_Call) RunAndReturn(run func() string) *MockAuthService_GetAPIEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthenticatedClient provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetAuthenticatedClient(ctx context.Context) (account.AccountAPI, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticatedClient")
	}

	var r0 account.AccountAPI
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (account.AccountAPI, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) account.AccountAPI); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(account.AccountAPI)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetAuthenticatedClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthenticatedClient'
type MockAuthService_GetAuthenticatedClient_Call struct {
	*mock.Call
}

// GetAuthenticatedClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthService_Expecter) GetAuthenticatedClient(ctx interface{}) *MockAuthService_GetAuthenticatedClient_Call {
	return &MockAuthService_GetAuthenticatedClient_Call{Call: _e.mock.On("GetAuthenticatedClient", ctx)}
}

func (_c *MockAuthService_GetAuthenticatedClient_Call) Run(run func(ctx context.Context)) *MockAuthService_GetAuthenticatedClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GetAuthenticatedClient_Call) Return(accountAPI account.AccountAPI, err error) *MockAuthService_GetAuthenticatedClient_Call {
	_c.Call.Return(accountAPI, err)
	return _c
}

func (_c *MockAuthService_GetAuthenticatedClient_Call) RunAndReturn(run func(ctx context.Context) (account.AccountAPI, error)) *MockAuthService_GetAuthenticatedClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoginToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetLoginToken(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLoginToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetLoginToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoginToken'
type MockAuthService_GetLoginToken_Call struct {
	*mock.Call
}

// GetLoginToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthService_Expecter) GetLoginToken(ctx interface{}) *MockAuthService_GetLoginToken_Call {
	return &MockAuthService_GetLoginToken_Call{Call: _e.mock.On("GetLoginToken", ctx)}
}

func (_c *MockAuthService_GetLoginToken_Call) Run(run func(ctx context.Context)) *MockAuthService_GetLoginToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GetLoginToken_Call) Return(s string, err error) *MockAuthService_GetLoginToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_GetLoginToken_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockAuthService_GetLoginToken_Call {
	_c.Call.Return(run)
	return _c
}

// LoginCheck provides a mock function for the type MockAuthService
func (_mock *MockAuthService) LoginCheck(ctx context.Context, email string, password string) (*account.LoginResult, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginCheck")
	}

	var r0 *account.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*account.LoginResult, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *account.LoginResult); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.LoginResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_LoginCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginCheck'
type MockAuthService_LoginCheck_Call struct {
	*mock.Call
}

// LoginCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) LoginCheck(ctx interface{}, email interface{}, password interface{}) *MockAuthService_LoginCheck_Call {
	return &MockAuthService_LoginCheck_Call{Call: _e.mock.On("LoginCheck", ctx, email, password)}
}

func (_c *MockAuthService_LoginCheck_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_LoginCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_LoginCheck_Call) Return(loginResult *account.LoginResult, err error) *MockAuthService_LoginCheck_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *MockAuthService_LoginCheck_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*account.LoginResult, error)) *MockAuthService_LoginCheck_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithOTP provides a mock function for the type MockAuthService
func (_mock *MockAuthService) LoginWithOTP(ctx context.Context, intermediateJWT string, otp string, keyName string, noCreateKey bool) (*auth.LoginCompleteResult, error) {
	ret := _mock.Called(ctx, intermediateJWT, otp, keyName, noCreateKey)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithOTP")
	}

	var r0 *auth.LoginCompleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (*auth.LoginCompleteResult, error)); ok {
		return returnFunc(ctx, intermediateJWT, otp, keyName, noCreateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool) *auth.LoginCompleteResult); ok {
		r0 = returnFunc(ctx, intermediateJWT, otp, keyName, noCreateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginCompleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = returnFunc(ctx, intermediateJWT, otp, keyName, noCreateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_LoginWithOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithOTP'
type MockAuthService_LoginWithOTP_Call struct {
	*mock.Call
}

// LoginWithOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - intermediateJWT string
//   - otp string
//   - keyName string
//   - noCreateKey bool
func (_e *MockAuthService_Expecter) LoginWithOTP(ctx interface{}, intermediateJWT interface{}, otp interface{}, keyName interface{}, noCreateKey interface{}) *MockAuthService_LoginWithOTP_Call {
	return &MockAuthService_LoginWithOTP_Call{Call: _e.mock.On("LoginWithOTP", ctx, intermediateJWT, otp, keyName, noCreateKey)}
}

func (_c *MockAuthService_LoginWithOTP_Call) Run(run func(ctx context.Context, intermediateJWT string, otp string, keyName string, noCreateKey bool)) *MockAuthService_LoginWithOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthService_LoginWithOTP_Call) Return(loginCompleteResult *auth.LoginCompleteResult, err error) *MockAuthService_LoginWithOTP_Call {
	_c.Call.Return(loginCompleteResult, err)
	return _c
}

func (_c *MockAuthService_LoginWithOTP_Call) RunAndReturn(run func(ctx context.Context, intermediateJWT string, otp string, keyName string, noCreateKey bool) (*auth.LoginCompleteResult, error)) *MockAuthService_LoginWithOTP_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, email string, firstName string, lastName string, password string) (*auth.RegisterResult, error) {
	ret := _mock.Called(ctx, email, firstName, lastName, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.RegisterResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*auth.RegisterResult, error)); ok {
		return returnFunc(ctx, email, firstName, lastName, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *auth.RegisterResult); ok {
		r0 = returnFunc(ctx, email, firstName, lastName, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RegisterResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, firstName, lastName, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - firstName string
//   - lastName string
//   - password string
func (_e *MockAuthService_Expecter) Register(ctx interface{}, email interface{}, firstName interface{}, lastName interface{}, password interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, firstName, lastName, password)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, firstName string, lastName string, password string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(registerResult *auth.RegisterResult, err error) *MockAuthService_Register_Call {
	_c.Call.Return(registerResult, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, firstName string, lastName string, password string) (*auth.RegisterResult, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) SaveToken(token string) (*auth.SaveTokenResult, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 *auth.SaveTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.SaveTokenResult, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.SaveTokenResult); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SaveTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockAuthService_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - token string
func (_e *MockAuthService_Expecter) SaveToken(token interface{}) *MockAuthService_SaveToken_Call {
	return &MockAuthService_SaveToken_Call{Call: _e.mock.On("SaveToken", token)}
}

func (_c *MockAuthService_SaveToken_Call) Run(run func(token string)) *MockAuthService_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_SaveToken_Call) Return(saveTokenResult *auth.SaveTokenResult, err error) *MockAuthService_SaveToken_Call {
	_c.Call.Return(saveTokenResult, err)
	return _c
}

func (_c *MockAuthService_SaveToken_Call) RunAndReturn(run func(token string) (*auth.SaveTokenResult, error)) *MockAuthService_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Status(ctx context.Context) (*auth.StatusResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *auth.StatusResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*auth.StatusResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *auth.StatusResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.StatusResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockAuthService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthService_Expecter) Status(ctx interface{}) *MockAuthService_Status_Call {
	return &MockAuthService_Status_Call{Call: _e.mock.On("Status", ctx)}
}

func (_c *MockAuthService_Status_Call) Run(run func(ctx context.Context)) *MockAuthService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Status_Call) Return(statusResult *auth.StatusResult, err error) *MockAuthService_Status_Call {
	_c.Call.Return(statusResult, err)
	return _c
}

func (_c *MockAuthService_Status_Call) RunAndReturn(run func(ctx context.Context) (*auth.StatusResult, error)) *MockAuthService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyOTP(ctx context.Context, otpCode string) error {
	ret := _mock.Called(ctx, otpCode)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, otpCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockAuthService_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - otpCode string
func (_e *MockAuthService_Expecter) VerifyOTP(ctx interface{}, otpCode interface{}) *MockAuthService_VerifyOTP_Call {
	return &MockAuthService_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, otpCode)}
}

func (_c *MockAuthService_VerifyOTP_Call) Run(run func(ctx context.Context, otpCode string)) *MockAuthService_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyOTP_Call) Return(err error) *MockAuthService_VerifyOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, otpCode string) error) *MockAuthService_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
