// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/pinner-cli/internal/core/pinning"
)

// NewMockPinningService creates a new instance of MockPinningService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinningService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinningService {
	mock := &MockPinningService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPinningService is an autogenerated mock type for the PinningService type
type MockPinningService struct {
	mock.Mock
}

type MockPinningService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinningService) EXPECT() *MockPinningService_Expecter {
	return &MockPinningService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockPinningService
func (_mock *MockPinningService) List(ctx context.Context, opts pinning.ListOptions) ([]pinning.Pin, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []pinning.Pin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pinning.ListOptions) ([]pinning.Pin, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pinning.ListOptions) []pinning.Pin); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pinning.Pin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pinning.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPinningService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts pinning.ListOptions
func (_e *MockPinningService_Expecter) List(ctx interface{}, opts interface{}) *MockPinningService_List_Call {
	return &MockPinningService_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockPinningService_List_Call) Run(run func(ctx context.Context, opts pinning.ListOptions)) *MockPinningService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pinning.ListOptions
		if args[1] != nil {
			arg1 = args[1].(pinning.ListOptions)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockPinningService_List_Call) Return(pins []pinning.Pin, err error) *MockPinningService_List_Call {
	_c.Call.Return(pins, err)
	return _c
}

func (_c *MockPinningService_List_Call) RunAndReturn(run func(ctx context.Context, opts pinning.ListOptions) ([]pinning.Pin, error)) *MockPinningService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Pin provides a mock function for the type MockPinningService
func (_mock *MockPinningService) Pin(ctx context.Context, cid string, name string, wait bool) (*pinning.PinResult, error) {
	ret := _mock.Called(ctx, cid, name, wait)

	if len(ret) == 0 {
		panic("no return value specified for Pin")
	}

	var r0 *pinning.PinResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*pinning.PinResult, error)); ok {
		return returnFunc(ctx, cid, name, wait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *pinning.PinResult); ok {
		r0 = returnFunc(ctx, cid, name, wait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.PinResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, cid, name, wait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_Pin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pin'
type MockPinningService_Pin_Call struct {
	*mock.Call
}

// Pin is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - name string
//   - wait bool
func (_e *MockPinningService_Expecter) Pin(ctx interface{}, cid interface{}, name interface{}, wait interface{}) *MockPinningService_Pin_Call {
	return &MockPinningService_Pin_Call{Call: _e.mock.On("Pin", ctx, cid, name, wait)}
}

func (_c *MockPinningService_Pin_Call) Run(run func(ctx context.Context, cid string, name string, wait bool)) *MockPinningService_Pin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPinningService_Pin_Call) Return(pinResult *pinning.PinResult, err error) *MockPinningService_Pin_Call {
	_c.Call.Return(pinResult, err)
	return _c
}

func (_c *MockPinningService_Pin_Call) RunAndReturn(run func(ctx context.Context, cid string, name string, wait bool) (*pinning.PinResult, error)) *MockPinningService_Pin_Call {
	_c.Call.Return(run)
	return _c
}

// PinBatch provides a mock function for the type MockPinningService
func (_mock *MockPinningService) PinBatch(ctx context.Context, cids []string, name string, opts pinning.BatchOptions) (*pinning.BatchResult, error) {
	ret := _mock.Called(ctx, cids, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for PinBatch")
	}

	var r0 *pinning.BatchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, pinning.BatchOptions) (*pinning.BatchResult, error)); ok {
		return returnFunc(ctx, cids, name, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, pinning.BatchOptions) *pinning.BatchResult); ok {
		r0 = returnFunc(ctx, cids, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.BatchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, pinning.BatchOptions) error); ok {
		r1 = returnFunc(ctx, cids, name, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_PinBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PinBatch'
type MockPinningService_PinBatch_Call struct {
	*mock.Call
}

// PinBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []string
//   - name string
//   - opts pinning.BatchOptions
func (_e *MockPinningService_Expecter) PinBatch(ctx interface{}, cids interface{}, name interface{}, opts interface{}) *MockPinningService_PinBatch_Call {
	return &MockPinningService_PinBatch_Call{Call: _e.mock.On("PinBatch", ctx, cids, name, opts)}
}

func (_c *MockPinningService_PinBatch_Call) Run(run func(ctx context.Context, cids []string, name string, opts pinning.BatchOptions)) *MockPinningService_PinBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 pinning.BatchOptions
		if args[3] != nil {
			arg3 = args[3].(pinning.BatchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPinningService_PinBatch_Call) Return(batchResult *pinning.BatchResult, err error) *MockPinningService_PinBatch_Call {
	_c.Call.Return(batchResult, err)
	return _c
}

func (_c *MockPinningService_PinBatch_Call) RunAndReturn(run func(ctx context.Context, cids []string, name string, opts pinning.BatchOptions) (*pinning.BatchResult, error)) *MockPinningService_PinBatch_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockPinningService
func (_mock *MockPinningService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinningService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockPinningService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockPinningService_Expecter) RequireAuthenticated() *MockPinningService_RequireAuthenticated_Call {
	return &MockPinningService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockPinningService_RequireAuthenticated_Call) Run(run func()) *MockPinningService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPinningService_RequireAuthenticated_Call) Return(err error) *MockPinningService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinningService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockPinningService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockPinningService
func (_mock *MockPinningService) Status(ctx context.Context, cid string, watch bool) (*pinning.PinStatus, error) {
	ret := _mock.Called(ctx, cid, watch)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *pinning.PinStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*pinning.PinStatus, error)); ok {
		return returnFunc(ctx, cid, watch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *pinning.PinStatus); ok {
		r0 = returnFunc(ctx, cid, watch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.PinStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, cid, watch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockPinningService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - watch bool
func (_e *MockPinningService_Expecter) Status(ctx interface{}, cid interface{}, watch interface{}) *MockPinningService_Status_Call {
	return &MockPinningService_Status_Call{Call: _e.mock.On("Status", ctx, cid, watch)}
}

func (_c *MockPinningService_Status_Call) Run(run func(ctx context.Context, cid string, watch bool)) *MockPinningService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPinningService_Status_Call) Return(pinStatus *pinning.PinStatus, err error) *MockPinningService_Status_Call {
	_c.Call.Return(pinStatus, err)
	return _c
}

func (_c *MockPinningService_Status_Call) RunAndReturn(run func(ctx context.Context, cid string, watch bool) (*pinning.PinStatus, error)) *MockPinningService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Unpin provides a mock function for the type MockPinningService
func (_mock *MockPinningService) Unpin(ctx context.Context, cid string, confirm bool) (*pinning.UnpinResult, error) {
	ret := _mock.Called(ctx, cid, confirm)

	if len(ret) == 0 {
		panic("no return value specified for Unpin")
	}

	var r0 *pinning.UnpinResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*pinning.UnpinResult, error)); ok {
		return returnFunc(ctx, cid, confirm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *pinning.UnpinResult); ok {
		r0 = returnFunc(ctx, cid, confirm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.UnpinResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, cid, confirm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_Unpin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpin'
type MockPinningService_Unpin_Call struct {
	*mock.Call
}

// Unpin is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - confirm bool
func (_e *MockPinningService_Expecter) Unpin(ctx interface{}, cid interface{}, confirm interface{}) *MockPinningService_Unpin_Call {
	return &MockPinningService_Unpin_Call{Call: _e.mock.On("Unpin", ctx, cid, confirm)}
}

func (_c *MockPinningService_Unpin_Call) Run(run func(ctx context.Context, cid string, confirm bool)) *MockPinningService_Unpin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPinningService_Unpin_Call) Return(unpinResult *pinning.UnpinResult, err error) *MockPinningService_Unpin_Call {
	_c.Call.Return(unpinResult, err)
	return _c
}

func (_c *MockPinningService_Unpin_Call) RunAndReturn(run func(ctx context.Context, cid string, confirm bool) (*pinning.UnpinResult, error)) *MockPinningService_Unpin_Call {
	_c.Call.Return(run)
	return _c
}

// UnpinAll provides a mock function for the type MockPinningService
func (_mock *MockPinningService) UnpinAll(ctx context.Context, statusFilter string, opts pinning.BatchOptions) (*pinning.BatchResult, error) {
	ret := _mock.Called(ctx, statusFilter, opts)

	if len(ret) == 0 {
		panic("no return value specified for UnpinAll")
	}

	var r0 *pinning.BatchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, pinning.BatchOptions) (*pinning.BatchResult, error)); ok {
		return returnFunc(ctx, statusFilter, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, pinning.BatchOptions) *pinning.BatchResult); ok {
		r0 = returnFunc(ctx, statusFilter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.BatchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, pinning.BatchOptions) error); ok {
		r1 = returnFunc(ctx, statusFilter, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_UnpinAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpinAll'
type MockPinningService_UnpinAll_Call struct {
	*mock.Call
}

// UnpinAll is a helper method to define mock.On call
//   - ctx context.Context
//   - statusFilter string
//   - opts pinning.BatchOptions
func (_e *MockPinningService_Expecter) UnpinAll(ctx interface{}, statusFilter interface{}, opts interface{}) *MockPinningService_UnpinAll_Call {
	return &MockPinningService_UnpinAll_Call{Call: _e.mock.On("UnpinAll", ctx, statusFilter, opts)}
}

func (_c *MockPinningService_UnpinAll_Call) Run(run func(ctx context.Context, statusFilter string, opts pinning.BatchOptions)) *MockPinningService_UnpinAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 pinning.BatchOptions
		if args[2] != nil {
			arg2 = args[2].(pinning.BatchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPinningService_UnpinAll_Call) Return(batchResult *pinning.BatchResult, err error) *MockPinningService_UnpinAll_Call {
	_c.Call.Return(batchResult, err)
	return _c
}

func (_c *MockPinningService_UnpinAll_Call) RunAndReturn(run func(ctx context.Context, statusFilter string, opts pinning.BatchOptions) (*pinning.BatchResult, error)) *MockPinningService_UnpinAll_Call {
	_c.Call.Return(run)
	return _c
}

// UnpinBatch provides a mock function for the type MockPinningService
func (_mock *MockPinningService) UnpinBatch(ctx context.Context, cids []string, opts pinning.BatchOptions) (*pinning.BatchResult, error) {
	ret := _mock.Called(ctx, cids, opts)

	if len(ret) == 0 {
		panic("no return value specified for UnpinBatch")
	}

	var r0 *pinning.BatchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, pinning.BatchOptions) (*pinning.BatchResult, error)); ok {
		return returnFunc(ctx, cids, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, pinning.BatchOptions) *pinning.BatchResult); ok {
		r0 = returnFunc(ctx, cids, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pinning.BatchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, pinning.BatchOptions) error); ok {
		r1 = returnFunc(ctx, cids, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningService_UnpinBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpinBatch'
type MockPinningService_UnpinBatch_Call struct {
	*mock.Call
}

// UnpinBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []string
//   - opts pinning.BatchOptions
func (_e *MockPinningService_Expecter) UnpinBatch(ctx interface{}, cids interface{}, opts interface{}) *MockPinningService_UnpinBatch_Call {
	return &MockPinningService_UnpinBatch_Call{Call: _e.mock.On("UnpinBatch", ctx, cids, opts)}
}

func (_c *MockPinningService_UnpinBatch_Call) Run(run func(ctx context.Context, cids []string, opts pinning.BatchOptions)) *MockPinningService_UnpinBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 pinning.BatchOptions
		if args[2] != nil {
			arg2 = args[2].(pinning.BatchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPinningService_UnpinBatch_Call) Return(batchResult *pinning.BatchResult, err error) *MockPinningService_UnpinBatch_Call {
	_c.Call.Return(batchResult, err)
	return _c
}

func (_c *MockPinningService_UnpinBatch_Call) RunAndReturn(run func(ctx context.Context, cids []string, opts pinning.BatchOptions) (*pinning.BatchResult, error)) *MockPinningService_UnpinBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetadata provides a mock function for the type MockPinningService
func (_mock *MockPinningService) UpdateMetadata(ctx context.Context, cid string, set []string, clear bool) error {
	ret := _mock.Called(ctx, cid, set, clear)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, bool) error); ok {
		r0 = returnFunc(ctx, cid, set, clear)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinningService_UpdateMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetadata'
type MockPinningService_UpdateMetadata_Call struct {
	*mock.Call
}

// UpdateMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - set []string
//   - clear bool
func (_e *MockPinningService_Expecter) UpdateMetadata(ctx interface{}, cid interface{}, set interface{}, clear interface{}) *MockPinningService_UpdateMetadata_Call {
	return &MockPinningService_UpdateMetadata_Call{Call: _e.mock.On("UpdateMetadata", ctx, cid, set, clear)}
}

func (_c *MockPinningService_UpdateMetadata_Call) Run(run func(ctx context.Context, cid string, set []string, clear bool)) *MockPinningService_UpdateMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPinningService_UpdateMetadata_Call) Return(err error) *MockPinningService_UpdateMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinningService_UpdateMetadata_Call) RunAndReturn(run func(ctx context.Context, cid string, set []string, clear bool) error) *MockPinningService_UpdateMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePin provides a mock function for the type MockPinningService
func (_mock *MockPinningService) UpdatePin(ctx context.Context, cid string, name string, meta []string, clearMeta bool) error {
	ret := _mock.Called(ctx, cid, name, meta, clearMeta)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string, bool) error); ok {
		r0 = returnFunc(ctx, cid, name, meta, clearMeta)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinningService_UpdatePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePin'
type MockPinningService_UpdatePin_Call struct {
	*mock.Call
}

// UpdatePin is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - name string
//   - meta []string
//   - clearMeta bool
func (_e *MockPinningService_Expecter) UpdatePin(ctx interface{}, cid interface{}, name interface{}, meta interface{}, clearMeta interface{}) *MockPinningService_UpdatePin_Call {
	return &MockPinningService_UpdatePin_Call{Call: _e.mock.On("UpdatePin", ctx, cid, name, meta, clearMeta)}
}

func (_c *MockPinningService_UpdatePin_Call) Run(run func(ctx context.Context, cid string, name string, meta []string, clearMeta bool)) *MockPinningService_UpdatePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPinningService_UpdatePin_Call) Return(err error) *MockPinningService_UpdatePin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinningService_UpdatePin_Call) RunAndReturn(run func(ctx context.Context, cid string, name string, meta []string, clearMeta bool) error) *MockPinningService_UpdatePin_Call {
	_c.Call.Return(run)
	return _c
}
