// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/admin"
)

// NewMockBillingAdminService creates a new instance of MockBillingAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingAdminService {
	mock := &MockBillingAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBillingAdminService is an autogenerated mock type for the BillingAdminService type
type MockBillingAdminService struct {
	mock.Mock
}

type MockBillingAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingAdminService) EXPECT() *MockBillingAdminService_Expecter {
	return &MockBillingAdminService_Expecter{mock: &_m.Mock}
}

// AbortUserSubscriptionCancellation provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) AbortUserSubscriptionCancellation(ctx context.Context, userID string) (*admin.ManagementResult, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AbortUserSubscriptionCancellation")
	}

	var r0 *admin.ManagementResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.ManagementResult, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.ManagementResult); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ManagementResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_AbortUserSubscriptionCancellation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortUserSubscriptionCancellation'
type MockBillingAdminService_AbortUserSubscriptionCancellation_Call struct {
	*mock.Call
}

// AbortUserSubscriptionCancellation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBillingAdminService_Expecter) AbortUserSubscriptionCancellation(ctx interface{}, userID interface{}) *MockBillingAdminService_AbortUserSubscriptionCancellation_Call {
	return &MockBillingAdminService_AbortUserSubscriptionCancellation_Call{Call: _e.mock.On("AbortUserSubscriptionCancellation", ctx, userID)}
}

func (_c *MockBillingAdminService_AbortUserSubscriptionCancellation_Call) Run(run func(ctx context.Context, userID string)) *MockBillingAdminService_AbortUserSubscriptionCancellation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_AbortUserSubscriptionCancellation_Call) Return(managementResult *admin.ManagementResult, err error) *MockBillingAdminService_AbortUserSubscriptionCancellation_Call {
	_c.Call.Return(managementResult, err)
	return _c
}

func (_c *MockBillingAdminService_AbortUserSubscriptionCancellation_Call) RunAndReturn(run func(ctx context.Context, userID string) (*admin.ManagementResult, error)) *MockBillingAdminService_AbortUserSubscriptionCancellation_Call {
	_c.Call.Return(run)
	return _c
}

// AddPlanToPriceLine provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) AddPlanToPriceLine(ctx context.Context, priceLineID string, req *admin.AddPlanToPriceLineRequest) (*admin.PriceLineDetailResponse, error) {
	ret := _mock.Called(ctx, priceLineID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddPlanToPriceLine")
	}

	var r0 *admin.PriceLineDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.AddPlanToPriceLineRequest) (*admin.PriceLineDetailResponse, error)); ok {
		return returnFunc(ctx, priceLineID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.AddPlanToPriceLineRequest) *admin.PriceLineDetailResponse); ok {
		r0 = returnFunc(ctx, priceLineID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PriceLineDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.AddPlanToPriceLineRequest) error); ok {
		r1 = returnFunc(ctx, priceLineID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_AddPlanToPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlanToPriceLine'
type MockBillingAdminService_AddPlanToPriceLine_Call struct {
	*mock.Call
}

// AddPlanToPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID string
//   - req *admin.AddPlanToPriceLineRequest
func (_e *MockBillingAdminService_Expecter) AddPlanToPriceLine(ctx interface{}, priceLineID interface{}, req interface{}) *MockBillingAdminService_AddPlanToPriceLine_Call {
	return &MockBillingAdminService_AddPlanToPriceLine_Call{Call: _e.mock.On("AddPlanToPriceLine", ctx, priceLineID, req)}
}

func (_c *MockBillingAdminService_AddPlanToPriceLine_Call) Run(run func(ctx context.Context, priceLineID string, req *admin.AddPlanToPriceLineRequest)) *MockBillingAdminService_AddPlanToPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.AddPlanToPriceLineRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.AddPlanToPriceLineRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_AddPlanToPriceLine_Call) Return(priceLineDetailResponse *admin.PriceLineDetailResponse, err error) *MockBillingAdminService_AddPlanToPriceLine_Call {
	_c.Call.Return(priceLineDetailResponse, err)
	return _c
}

func (_c *MockBillingAdminService_AddPlanToPriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID string, req *admin.AddPlanToPriceLineRequest) (*admin.PriceLineDetailResponse, error)) *MockBillingAdminService_AddPlanToPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// CancelUserSubscription provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) CancelUserSubscription(ctx context.Context, userID string, req *admin.CancelSubscriptionRequest) (*admin.ManagementResult, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CancelUserSubscription")
	}

	var r0 *admin.ManagementResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.CancelSubscriptionRequest) (*admin.ManagementResult, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.CancelSubscriptionRequest) *admin.ManagementResult); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ManagementResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.CancelSubscriptionRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_CancelUserSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelUserSubscription'
type MockBillingAdminService_CancelUserSubscription_Call struct {
	*mock.Call
}

// CancelUserSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *admin.CancelSubscriptionRequest
func (_e *MockBillingAdminService_Expecter) CancelUserSubscription(ctx interface{}, userID interface{}, req interface{}) *MockBillingAdminService_CancelUserSubscription_Call {
	return &MockBillingAdminService_CancelUserSubscription_Call{Call: _e.mock.On("CancelUserSubscription", ctx, userID, req)}
}

func (_c *MockBillingAdminService_CancelUserSubscription_Call) Run(run func(ctx context.Context, userID string, req *admin.CancelSubscriptionRequest)) *MockBillingAdminService_CancelUserSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.CancelSubscriptionRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.CancelSubscriptionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_CancelUserSubscription_Call) Return(managementResult *admin.ManagementResult, err error) *MockBillingAdminService_CancelUserSubscription_Call {
	_c.Call.Return(managementResult, err)
	return _c
}

func (_c *MockBillingAdminService_CancelUserSubscription_Call) RunAndReturn(run func(ctx context.Context, userID string, req *admin.CancelSubscriptionRequest) (*admin.ManagementResult, error)) *MockBillingAdminService_CancelUserSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeUserPlan provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ChangeUserPlan(ctx context.Context, userID string, req *admin.ChangePlanRequest) (*admin.PlanChangeResult, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUserPlan")
	}

	var r0 *admin.PlanChangeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.ChangePlanRequest) (*admin.PlanChangeResult, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.ChangePlanRequest) *admin.PlanChangeResult); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PlanChangeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.ChangePlanRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_ChangeUserPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeUserPlan'
type MockBillingAdminService_ChangeUserPlan_Call struct {
	*mock.Call
}

// ChangeUserPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *admin.ChangePlanRequest
func (_e *MockBillingAdminService_Expecter) ChangeUserPlan(ctx interface{}, userID interface{}, req interface{}) *MockBillingAdminService_ChangeUserPlan_Call {
	return &MockBillingAdminService_ChangeUserPlan_Call{Call: _e.mock.On("ChangeUserPlan", ctx, userID, req)}
}

func (_c *MockBillingAdminService_ChangeUserPlan_Call) Run(run func(ctx context.Context, userID string, req *admin.ChangePlanRequest)) *MockBillingAdminService_ChangeUserPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.ChangePlanRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.ChangePlanRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ChangeUserPlan_Call) Return(planChangeResult *admin.PlanChangeResult, err error) *MockBillingAdminService_ChangeUserPlan_Call {
	_c.Call.Return(planChangeResult, err)
	return _c
}

func (_c *MockBillingAdminService_ChangeUserPlan_Call) RunAndReturn(run func(ctx context.Context, userID string, req *admin.ChangePlanRequest) (*admin.PlanChangeResult, error)) *MockBillingAdminService_ChangeUserPlan_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCredit provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) CreateCredit(ctx context.Context, req *admin.CreditCreateRequest) (*admin.Credit, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredit")
	}

	var r0 *admin.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.CreditCreateRequest) (*admin.Credit, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.CreditCreateRequest) *admin.Credit); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.CreditCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_CreateCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredit'
type MockBillingAdminService_CreateCredit_Call struct {
	*mock.Call
}

// CreateCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - req *admin.CreditCreateRequest
func (_e *MockBillingAdminService_Expecter) CreateCredit(ctx interface{}, req interface{}) *MockBillingAdminService_CreateCredit_Call {
	return &MockBillingAdminService_CreateCredit_Call{Call: _e.mock.On("CreateCredit", ctx, req)}
}

func (_c *MockBillingAdminService_CreateCredit_Call) Run(run func(ctx context.Context, req *admin.CreditCreateRequest)) *MockBillingAdminService_CreateCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.CreditCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*admin.CreditCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_CreateCredit_Call) Return(credit *admin.Credit, err error) *MockBillingAdminService_CreateCredit_Call {
	_c.Call.Return(credit, err)
	return _c
}

func (_c *MockBillingAdminService_CreateCredit_Call) RunAndReturn(run func(ctx context.Context, req *admin.CreditCreateRequest) (*admin.Credit, error)) *MockBillingAdminService_CreateCredit_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePriceLine provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) CreatePriceLine(ctx context.Context, req *admin.PriceLineCreateRequest) (*admin.PriceLine, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePriceLine")
	}

	var r0 *admin.PriceLine
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PriceLineCreateRequest) (*admin.PriceLine, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PriceLineCreateRequest) *admin.PriceLine); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.PriceLineCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_CreatePriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePriceLine'
type MockBillingAdminService_CreatePriceLine_Call struct {
	*mock.Call
}

// CreatePriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - req *admin.PriceLineCreateRequest
func (_e *MockBillingAdminService_Expecter) CreatePriceLine(ctx interface{}, req interface{}) *MockBillingAdminService_CreatePriceLine_Call {
	return &MockBillingAdminService_CreatePriceLine_Call{Call: _e.mock.On("CreatePriceLine", ctx, req)}
}

func (_c *MockBillingAdminService_CreatePriceLine_Call) Run(run func(ctx context.Context, req *admin.PriceLineCreateRequest)) *MockBillingAdminService_CreatePriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.PriceLineCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*admin.PriceLineCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_CreatePriceLine_Call) Return(priceLine *admin.PriceLine, err error) *MockBillingAdminService_CreatePriceLine_Call {
	_c.Call.Return(priceLine, err)
	return _c
}

func (_c *MockBillingAdminService_CreatePriceLine_Call) RunAndReturn(run func(ctx context.Context, req *admin.PriceLineCreateRequest) (*admin.PriceLine, error)) *MockBillingAdminService_CreatePriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePricingPlan provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) CreatePricingPlan(ctx context.Context, req *admin.PricingPlanCreateRequest) (*admin.PricingPlan, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePricingPlan")
	}

	var r0 *admin.PricingPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PricingPlanCreateRequest) (*admin.PricingPlan, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PricingPlanCreateRequest) *admin.PricingPlan); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PricingPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.PricingPlanCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_CreatePricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePricingPlan'
type MockBillingAdminService_CreatePricingPlan_Call struct {
	*mock.Call
}

// CreatePricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - req *admin.PricingPlanCreateRequest
func (_e *MockBillingAdminService_Expecter) CreatePricingPlan(ctx interface{}, req interface{}) *MockBillingAdminService_CreatePricingPlan_Call {
	return &MockBillingAdminService_CreatePricingPlan_Call{Call: _e.mock.On("CreatePricingPlan", ctx, req)}
}

func (_c *MockBillingAdminService_CreatePricingPlan_Call) Run(run func(ctx context.Context, req *admin.PricingPlanCreateRequest)) *MockBillingAdminService_CreatePricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.PricingPlanCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*admin.PricingPlanCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_CreatePricingPlan_Call) Return(pricingPlan *admin.PricingPlan, err error) *MockBillingAdminService_CreatePricingPlan_Call {
	_c.Call.Return(pricingPlan, err)
	return _c
}

func (_c *MockBillingAdminService_CreatePricingPlan_Call) RunAndReturn(run func(ctx context.Context, req *admin.PricingPlanCreateRequest) (*admin.PricingPlan, error)) *MockBillingAdminService_CreatePricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePricingPlanPeriod provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) CreatePricingPlanPeriod(ctx context.Context, req *admin.PricingPlanPeriodCreateRequest) (*admin.PricingPlanPeriod, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePricingPlanPeriod")
	}

	var r0 *admin.PricingPlanPeriod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PricingPlanPeriodCreateRequest) (*admin.PricingPlanPeriod, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.PricingPlanPeriodCreateRequest) *admin.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.PricingPlanPeriodCreateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_CreatePricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePricingPlanPeriod'
type MockBillingAdminService_CreatePricingPlanPeriod_Call struct {
	*mock.Call
}

// CreatePricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - req *admin.PricingPlanPeriodCreateRequest
func (_e *MockBillingAdminService_Expecter) CreatePricingPlanPeriod(ctx interface{}, req interface{}) *MockBillingAdminService_CreatePricingPlanPeriod_Call {
	return &MockBillingAdminService_CreatePricingPlanPeriod_Call{Call: _e.mock.On("CreatePricingPlanPeriod", ctx, req)}
}

func (_c *MockBillingAdminService_CreatePricingPlanPeriod_Call) Run(run func(ctx context.Context, req *admin.PricingPlanPeriodCreateRequest)) *MockBillingAdminService_CreatePricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.PricingPlanPeriodCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*admin.PricingPlanPeriodCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_CreatePricingPlanPeriod_Call) Return(pricingPlanPeriod *admin.PricingPlanPeriod, err error) *MockBillingAdminService_CreatePricingPlanPeriod_Call {
	_c.Call.Return(pricingPlanPeriod, err)
	return _c
}

func (_c *MockBillingAdminService_CreatePricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, req *admin.PricingPlanPeriodCreateRequest) (*admin.PricingPlanPeriod, error)) *MockBillingAdminService_CreatePricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCredit provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) DeleteCredit(ctx context.Context, creditID string) error {
	ret := _mock.Called(ctx, creditID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, creditID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingAdminService_DeleteCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredit'
type MockBillingAdminService_DeleteCredit_Call struct {
	*mock.Call
}

// DeleteCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - creditID string
func (_e *MockBillingAdminService_Expecter) DeleteCredit(ctx interface{}, creditID interface{}) *MockBillingAdminService_DeleteCredit_Call {
	return &MockBillingAdminService_DeleteCredit_Call{Call: _e.mock.On("DeleteCredit", ctx, creditID)}
}

func (_c *MockBillingAdminService_DeleteCredit_Call) Run(run func(ctx context.Context, creditID string)) *MockBillingAdminService_DeleteCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_DeleteCredit_Call) Return(err error) *MockBillingAdminService_DeleteCredit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingAdminService_DeleteCredit_Call) RunAndReturn(run func(ctx context.Context, creditID string) error) *MockBillingAdminService_DeleteCredit_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlanFromPriceLine provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) DeletePlanFromPriceLine(ctx context.Context, priceLineID string, planID string) error {
	ret := _mock.Called(ctx, priceLineID, planID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlanFromPriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, priceLineID, planID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingAdminService_DeletePlanFromPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlanFromPriceLine'
type MockBillingAdminService_DeletePlanFromPriceLine_Call struct {
	*mock.Call
}

// DeletePlanFromPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID string
//   - planID string
func (_e *MockBillingAdminService_Expecter) DeletePlanFromPriceLine(ctx interface{}, priceLineID interface{}, planID interface{}) *MockBillingAdminService_DeletePlanFromPriceLine_Call {
	return &MockBillingAdminService_DeletePlanFromPriceLine_Call{Call: _e.mock.On("DeletePlanFromPriceLine", ctx, priceLineID, planID)}
}

func (_c *MockBillingAdminService_DeletePlanFromPriceLine_Call) Run(run func(ctx context.Context, priceLineID string, planID string)) *MockBillingAdminService_DeletePlanFromPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_DeletePlanFromPriceLine_Call) Return(err error) *MockBillingAdminService_DeletePlanFromPriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingAdminService_DeletePlanFromPriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID string, planID string) error) *MockBillingAdminService_DeletePlanFromPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePriceLine provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) DeletePriceLine(ctx context.Context, priceLineID string) error {
	ret := _mock.Called(ctx, priceLineID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePriceLine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, priceLineID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingAdminService_DeletePriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePriceLine'
type MockBillingAdminService_DeletePriceLine_Call struct {
	*mock.Call
}

// DeletePriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID string
func (_e *MockBillingAdminService_Expecter) DeletePriceLine(ctx interface{}, priceLineID interface{}) *MockBillingAdminService_DeletePriceLine_Call {
	return &MockBillingAdminService_DeletePriceLine_Call{Call: _e.mock.On("DeletePriceLine", ctx, priceLineID)}
}

func (_c *MockBillingAdminService_DeletePriceLine_Call) Run(run func(ctx context.Context, priceLineID string)) *MockBillingAdminService_DeletePriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_DeletePriceLine_Call) Return(err error) *MockBillingAdminService_DeletePriceLine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingAdminService_DeletePriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID string) error) *MockBillingAdminService_DeletePriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePricingPlan provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) DeletePricingPlan(ctx context.Context, planID string) error {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePricingPlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingAdminService_DeletePricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePricingPlan'
type MockBillingAdminService_DeletePricingPlan_Call struct {
	*mock.Call
}

// DeletePricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
func (_e *MockBillingAdminService_Expecter) DeletePricingPlan(ctx interface{}, planID interface{}) *MockBillingAdminService_DeletePricingPlan_Call {
	return &MockBillingAdminService_DeletePricingPlan_Call{Call: _e.mock.On("DeletePricingPlan", ctx, planID)}
}

func (_c *MockBillingAdminService_DeletePricingPlan_Call) Run(run func(ctx context.Context, planID string)) *MockBillingAdminService_DeletePricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_DeletePricingPlan_Call) Return(err error) *MockBillingAdminService_DeletePricingPlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingAdminService_DeletePricingPlan_Call) RunAndReturn(run func(ctx context.Context, planID string) error) *MockBillingAdminService_DeletePricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePricingPlanPeriod provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) DeletePricingPlanPeriod(ctx context.Context, periodID string) error {
	ret := _mock.Called(ctx, periodID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePricingPlanPeriod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, periodID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingAdminService_DeletePricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePricingPlanPeriod'
type MockBillingAdminService_DeletePricingPlanPeriod_Call struct {
	*mock.Call
}

// DeletePricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - periodID string
func (_e *MockBillingAdminService_Expecter) DeletePricingPlanPeriod(ctx interface{}, periodID interface{}) *MockBillingAdminService_DeletePricingPlanPeriod_Call {
	return &MockBillingAdminService_DeletePricingPlanPeriod_Call{Call: _e.mock.On("DeletePricingPlanPeriod", ctx, periodID)}
}

func (_c *MockBillingAdminService_DeletePricingPlanPeriod_Call) Run(run func(ctx context.Context, periodID string)) *MockBillingAdminService_DeletePricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_DeletePricingPlanPeriod_Call) Return(err error) *MockBillingAdminService_DeletePricingPlanPeriod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingAdminService_DeletePricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, periodID string) error) *MockBillingAdminService_DeletePricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredit provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetCredit(ctx context.Context, creditID string) (*admin.Credit, error) {
	ret := _mock.Called(ctx, creditID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredit")
	}

	var r0 *admin.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.Credit, error)); ok {
		return returnFunc(ctx, creditID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.Credit); ok {
		r0 = returnFunc(ctx, creditID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, creditID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_GetCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredit'
type MockBillingAdminService_GetCredit_Call struct {
	*mock.Call
}

// GetCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - creditID string
func (_e *MockBillingAdminService_Expecter) GetCredit(ctx interface{}, creditID interface{}) *MockBillingAdminService_GetCredit_Call {
	return &MockBillingAdminService_GetCredit_Call{Call: _e.mock.On("GetCredit", ctx, creditID)}
}

func (_c *MockBillingAdminService_GetCredit_Call) Run(run func(ctx context.Context, creditID string)) *MockBillingAdminService_GetCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetCredit_Call) Return(credit *admin.Credit, err error) *MockBillingAdminService_GetCredit_Call {
	_c.Call.Return(credit, err)
	return _c
}

func (_c *MockBillingAdminService_GetCredit_Call) RunAndReturn(run func(ctx context.Context, creditID string) (*admin.Credit, error)) *MockBillingAdminService_GetCredit_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceLine provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetPriceLine(ctx context.Context, priceLineID string) (*admin.PriceLineDetailResponse, error) {
	ret := _mock.Called(ctx, priceLineID)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceLine")
	}

	var r0 *admin.PriceLineDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.PriceLineDetailResponse, error)); ok {
		return returnFunc(ctx, priceLineID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.PriceLineDetailResponse); ok {
		r0 = returnFunc(ctx, priceLineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PriceLineDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, priceLineID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_GetPriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceLine'
type MockBillingAdminService_GetPriceLine_Call struct {
	*mock.Call
}

// GetPriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID string
func (_e *MockBillingAdminService_Expecter) GetPriceLine(ctx interface{}, priceLineID interface{}) *MockBillingAdminService_GetPriceLine_Call {
	return &MockBillingAdminService_GetPriceLine_Call{Call: _e.mock.On("GetPriceLine", ctx, priceLineID)}
}

func (_c *MockBillingAdminService_GetPriceLine_Call) Run(run func(ctx context.Context, priceLineID string)) *MockBillingAdminService_GetPriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetPriceLine_Call) Return(priceLineDetailResponse *admin.PriceLineDetailResponse, err error) *MockBillingAdminService_GetPriceLine_Call {
	_c.Call.Return(priceLineDetailResponse, err)
	return _c
}

func (_c *MockBillingAdminService_GetPriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID string) (*admin.PriceLineDetailResponse, error)) *MockBillingAdminService_GetPriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlan provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetPricingPlan(ctx context.Context, planID string) (*admin.PricingPlan, error) {
	ret := _mock.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlan")
	}

	var r0 *admin.PricingPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.PricingPlan, error)); ok {
		return returnFunc(ctx, planID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.PricingPlan); ok {
		r0 = returnFunc(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PricingPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_GetPricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlan'
type MockBillingAdminService_GetPricingPlan_Call struct {
	*mock.Call
}

// GetPricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
func (_e *MockBillingAdminService_Expecter) GetPricingPlan(ctx interface{}, planID interface{}) *MockBillingAdminService_GetPricingPlan_Call {
	return &MockBillingAdminService_GetPricingPlan_Call{Call: _e.mock.On("GetPricingPlan", ctx, planID)}
}

func (_c *MockBillingAdminService_GetPricingPlan_Call) Run(run func(ctx context.Context, planID string)) *MockBillingAdminService_GetPricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetPricingPlan_Call) Return(pricingPlan *admin.PricingPlan, err error) *MockBillingAdminService_GetPricingPlan_Call {
	_c.Call.Return(pricingPlan, err)
	return _c
}

func (_c *MockBillingAdminService_GetPricingPlan_Call) RunAndReturn(run func(ctx context.Context, planID string) (*admin.PricingPlan, error)) *MockBillingAdminService_GetPricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingPlanPeriod provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetPricingPlanPeriod(ctx context.Context, periodID string) (*admin.PricingPlanPeriod, error) {
	ret := _mock.Called(ctx, periodID)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingPlanPeriod")
	}

	var r0 *admin.PricingPlanPeriod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.PricingPlanPeriod, error)); ok {
		return returnFunc(ctx, periodID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx, periodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, periodID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_GetPricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingPlanPeriod'
type MockBillingAdminService_GetPricingPlanPeriod_Call struct {
	*mock.Call
}

// GetPricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - periodID string
func (_e *MockBillingAdminService_Expecter) GetPricingPlanPeriod(ctx interface{}, periodID interface{}) *MockBillingAdminService_GetPricingPlanPeriod_Call {
	return &MockBillingAdminService_GetPricingPlanPeriod_Call{Call: _e.mock.On("GetPricingPlanPeriod", ctx, periodID)}
}

func (_c *MockBillingAdminService_GetPricingPlanPeriod_Call) Run(run func(ctx context.Context, periodID string)) *MockBillingAdminService_GetPricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetPricingPlanPeriod_Call) Return(pricingPlanPeriod *admin.PricingPlanPeriod, err error) *MockBillingAdminService_GetPricingPlanPeriod_Call {
	_c.Call.Return(pricingPlanPeriod, err)
	return _c
}

func (_c *MockBillingAdminService_GetPricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, periodID string) (*admin.PricingPlanPeriod, error)) *MockBillingAdminService_GetPricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriber provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetSubscriber(ctx context.Context, subscriberID string) (*admin.Subscriber, error) {
	ret := _mock.Called(ctx, subscriberID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriber")
	}

	var r0 *admin.Subscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.Subscriber, error)); ok {
		return returnFunc(ctx, subscriberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.Subscriber); ok {
		r0 = returnFunc(ctx, subscriberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_GetSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriber'
type MockBillingAdminService_GetSubscriber_Call struct {
	*mock.Call
}

// GetSubscriber is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriberID string
func (_e *MockBillingAdminService_Expecter) GetSubscriber(ctx interface{}, subscriberID interface{}) *MockBillingAdminService_GetSubscriber_Call {
	return &MockBillingAdminService_GetSubscriber_Call{Call: _e.mock.On("GetSubscriber", ctx, subscriberID)}
}

func (_c *MockBillingAdminService_GetSubscriber_Call) Run(run func(ctx context.Context, subscriberID string)) *MockBillingAdminService_GetSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetSubscriber_Call) Return(subscriber *admin.Subscriber, err error) *MockBillingAdminService_GetSubscriber_Call {
	_c.Call.Return(subscriber, err)
	return _c
}

func (_c *MockBillingAdminService_GetSubscriber_Call) RunAndReturn(run func(ctx context.Context, subscriberID string) (*admin.Subscriber, error)) *MockBillingAdminService_GetSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetUserBalance(ctx context.Context, userID string) (*admin.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 *admin.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.UserBalance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockBillingAdminService_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBillingAdminService_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *MockBillingAdminService_GetUserBalance_Call {
	return &MockBillingAdminService_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *MockBillingAdminService_GetUserBalance_Call) Run(run func(ctx context.Context, userID string)) *MockBillingAdminService_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetUserBalance_Call) Return(userBalance *admin.UserBalance, err error) *MockBillingAdminService_GetUserBalance_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *MockBillingAdminService_GetUserBalance_Call) RunAndReturn(run func(ctx context.Context, userID string) (*admin.UserBalance, error)) *MockBillingAdminService_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDeletedCredits provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetUserDeletedCredits(ctx context.Context, userID string, params *admin.GetApiBillingUsersUserIdDeletedCreditsParams) ([]*admin.CreditItem, int, error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDeletedCredits")
	}

	var r0 []*admin.CreditItem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.GetApiBillingUsersUserIdDeletedCreditsParams) ([]*admin.CreditItem, int, error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.GetApiBillingUsersUserIdDeletedCreditsParams) []*admin.CreditItem); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.CreditItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.GetApiBillingUsersUserIdDeletedCreditsParams) int); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *admin.GetApiBillingUsersUserIdDeletedCreditsParams) error); ok {
		r2 = returnFunc(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_GetUserDeletedCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDeletedCredits'
type MockBillingAdminService_GetUserDeletedCredits_Call struct {
	*mock.Call
}

// GetUserDeletedCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - params *admin.GetApiBillingUsersUserIdDeletedCreditsParams
func (_e *MockBillingAdminService_Expecter) GetUserDeletedCredits(ctx interface{}, userID interface{}, params interface{}) *MockBillingAdminService_GetUserDeletedCredits_Call {
	return &MockBillingAdminService_GetUserDeletedCredits_Call{Call: _e.mock.On("GetUserDeletedCredits", ctx, userID, params)}
}

func (_c *MockBillingAdminService_GetUserDeletedCredits_Call) Run(run func(ctx context.Context, userID string, params *admin.GetApiBillingUsersUserIdDeletedCreditsParams)) *MockBillingAdminService_GetUserDeletedCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.GetApiBillingUsersUserIdDeletedCreditsParams
		if args[2] != nil {
			arg2 = args[2].(*admin.GetApiBillingUsersUserIdDeletedCreditsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetUserDeletedCredits_Call) Return(creditItems []*admin.CreditItem, n int, err error) *MockBillingAdminService_GetUserDeletedCredits_Call {
	_c.Call.Return(creditItems, n, err)
	return _c
}

func (_c *MockBillingAdminService_GetUserDeletedCredits_Call) RunAndReturn(run func(ctx context.Context, userID string, params *admin.GetApiBillingUsersUserIdDeletedCreditsParams) ([]*admin.CreditItem, int, error)) *MockBillingAdminService_GetUserDeletedCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSubscribers provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) GetUserSubscribers(ctx context.Context, userID string) ([]*admin.Subscriber, int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSubscribers")
	}

	var r0 []*admin.Subscriber
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*admin.Subscriber, int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*admin.Subscriber); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_GetUserSubscribers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSubscribers'
type MockBillingAdminService_GetUserSubscribers_Call struct {
	*mock.Call
}

// GetUserSubscribers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBillingAdminService_Expecter) GetUserSubscribers(ctx interface{}, userID interface{}) *MockBillingAdminService_GetUserSubscribers_Call {
	return &MockBillingAdminService_GetUserSubscribers_Call{Call: _e.mock.On("GetUserSubscribers", ctx, userID)}
}

func (_c *MockBillingAdminService_GetUserSubscribers_Call) Run(run func(ctx context.Context, userID string)) *MockBillingAdminService_GetUserSubscribers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_GetUserSubscribers_Call) Return(subscribers []*admin.Subscriber, n int, err error) *MockBillingAdminService_GetUserSubscribers_Call {
	_c.Call.Return(subscribers, n, err)
	return _c
}

func (_c *MockBillingAdminService_GetUserSubscribers_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*admin.Subscriber, int, error)) *MockBillingAdminService_GetUserSubscribers_Call {
	_c.Call.Return(run)
	return _c
}

// ListCredits provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ListCredits(ctx context.Context, params *admin.GetApiBillingCreditsParams) ([]*admin.CreditItem, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListCredits")
	}

	var r0 []*admin.CreditItem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.GetApiBillingCreditsParams) ([]*admin.CreditItem, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.GetApiBillingCreditsParams) []*admin.CreditItem); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.CreditItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.GetApiBillingCreditsParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *admin.GetApiBillingCreditsParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_ListCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCredits'
type MockBillingAdminService_ListCredits_Call struct {
	*mock.Call
}

// ListCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - params *admin.GetApiBillingCreditsParams
func (_e *MockBillingAdminService_Expecter) ListCredits(ctx interface{}, params interface{}) *MockBillingAdminService_ListCredits_Call {
	return &MockBillingAdminService_ListCredits_Call{Call: _e.mock.On("ListCredits", ctx, params)}
}

func (_c *MockBillingAdminService_ListCredits_Call) Run(run func(ctx context.Context, params *admin.GetApiBillingCreditsParams)) *MockBillingAdminService_ListCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.GetApiBillingCreditsParams
		if args[1] != nil {
			arg1 = args[1].(*admin.GetApiBillingCreditsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ListCredits_Call) Return(creditItems []*admin.CreditItem, n int, err error) *MockBillingAdminService_ListCredits_Call {
	_c.Call.Return(creditItems, n, err)
	return _c
}

func (_c *MockBillingAdminService_ListCredits_Call) RunAndReturn(run func(ctx context.Context, params *admin.GetApiBillingCreditsParams) ([]*admin.CreditItem, int, error)) *MockBillingAdminService_ListCredits_Call {
	_c.Call.Return(run)
	return _c
}

// ListGatewaySubscribers provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ListGatewaySubscribers(ctx context.Context, gatewayID string) ([]*admin.Subscriber, int, error) {
	ret := _mock.Called(ctx, gatewayID)

	if len(ret) == 0 {
		panic("no return value specified for ListGatewaySubscribers")
	}

	var r0 []*admin.Subscriber
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*admin.Subscriber, int, error)); ok {
		return returnFunc(ctx, gatewayID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*admin.Subscriber); ok {
		r0 = returnFunc(ctx, gatewayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(ctx, gatewayID)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, gatewayID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_ListGatewaySubscribers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGatewaySubscribers'
type MockBillingAdminService_ListGatewaySubscribers_Call struct {
	*mock.Call
}

// ListGatewaySubscribers is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
func (_e *MockBillingAdminService_Expecter) ListGatewaySubscribers(ctx interface{}, gatewayID interface{}) *MockBillingAdminService_ListGatewaySubscribers_Call {
	return &MockBillingAdminService_ListGatewaySubscribers_Call{Call: _e.mock.On("ListGatewaySubscribers", ctx, gatewayID)}
}

func (_c *MockBillingAdminService_ListGatewaySubscribers_Call) Run(run func(ctx context.Context, gatewayID string)) *MockBillingAdminService_ListGatewaySubscribers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ListGatewaySubscribers_Call) Return(subscribers []*admin.Subscriber, n int, err error) *MockBillingAdminService_ListGatewaySubscribers_Call {
	_c.Call.Return(subscribers, n, err)
	return _c
}

func (_c *MockBillingAdminService_ListGatewaySubscribers_Call) RunAndReturn(run func(ctx context.Context, gatewayID string) ([]*admin.Subscriber, int, error)) *MockBillingAdminService_ListGatewaySubscribers_Call {
	_c.Call.Return(run)
	return _c
}

// ListPriceLines provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ListPriceLines(ctx context.Context) ([]*admin.PriceLine, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPriceLines")
	}

	var r0 []*admin.PriceLine
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.PriceLine, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.PriceLine); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_ListPriceLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPriceLines'
type MockBillingAdminService_ListPriceLines_Call struct {
	*mock.Call
}

// ListPriceLines is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillingAdminService_Expecter) ListPriceLines(ctx interface{}) *MockBillingAdminService_ListPriceLines_Call {
	return &MockBillingAdminService_ListPriceLines_Call{Call: _e.mock.On("ListPriceLines", ctx)}
}

func (_c *MockBillingAdminService_ListPriceLines_Call) Run(run func(ctx context.Context)) *MockBillingAdminService_ListPriceLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ListPriceLines_Call) Return(priceLines []*admin.PriceLine, n int, err error) *MockBillingAdminService_ListPriceLines_Call {
	_c.Call.Return(priceLines, n, err)
	return _c
}

func (_c *MockBillingAdminService_ListPriceLines_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.PriceLine, int, error)) *MockBillingAdminService_ListPriceLines_Call {
	_c.Call.Return(run)
	return _c
}

// ListPricingPlanPeriods provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ListPricingPlanPeriods(ctx context.Context) ([]*admin.PricingPlanPeriod, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPricingPlanPeriods")
	}

	var r0 []*admin.PricingPlanPeriod
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.PricingPlanPeriod, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_ListPricingPlanPeriods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPricingPlanPeriods'
type MockBillingAdminService_ListPricingPlanPeriods_Call struct {
	*mock.Call
}

// ListPricingPlanPeriods is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillingAdminService_Expecter) ListPricingPlanPeriods(ctx interface{}) *MockBillingAdminService_ListPricingPlanPeriods_Call {
	return &MockBillingAdminService_ListPricingPlanPeriods_Call{Call: _e.mock.On("ListPricingPlanPeriods", ctx)}
}

func (_c *MockBillingAdminService_ListPricingPlanPeriods_Call) Run(run func(ctx context.Context)) *MockBillingAdminService_ListPricingPlanPeriods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ListPricingPlanPeriods_Call) Return(pricingPlanPeriods []*admin.PricingPlanPeriod, n int, err error) *MockBillingAdminService_ListPricingPlanPeriods_Call {
	_c.Call.Return(pricingPlanPeriods, n, err)
	return _c
}

func (_c *MockBillingAdminService_ListPricingPlanPeriods_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.PricingPlanPeriod, int, error)) *MockBillingAdminService_ListPricingPlanPeriods_Call {
	_c.Call.Return(run)
	return _c
}

// ListPricingPlans provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ListPricingPlans(ctx context.Context) ([]*admin.PricingPlanItem, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPricingPlans")
	}

	var r0 []*admin.PricingPlanItem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.PricingPlanItem, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.PricingPlanItem); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.PricingPlanItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_ListPricingPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPricingPlans'
type MockBillingAdminService_ListPricingPlans_Call struct {
	*mock.Call
}

// ListPricingPlans is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillingAdminService_Expecter) ListPricingPlans(ctx interface{}) *MockBillingAdminService_ListPricingPlans_Call {
	return &MockBillingAdminService_ListPricingPlans_Call{Call: _e.mock.On("ListPricingPlans", ctx)}
}

func (_c *MockBillingAdminService_ListPricingPlans_Call) Run(run func(ctx context.Context)) *MockBillingAdminService_ListPricingPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ListPricingPlans_Call) Return(pricingPlanItems []*admin.PricingPlanItem, n int, err error) *MockBillingAdminService_ListPricingPlans_Call {
	_c.Call.Return(pricingPlanItems, n, err)
	return _c
}

func (_c *MockBillingAdminService_ListPricingPlans_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.PricingPlanItem, int, error)) *MockBillingAdminService_ListPricingPlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubscribers provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ListSubscribers(ctx context.Context) ([]*admin.Subscriber, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSubscribers")
	}

	var r0 []*admin.Subscriber
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*admin.Subscriber, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*admin.Subscriber); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*admin.Subscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBillingAdminService_ListSubscribers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubscribers'
type MockBillingAdminService_ListSubscribers_Call struct {
	*mock.Call
}

// ListSubscribers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillingAdminService_Expecter) ListSubscribers(ctx interface{}) *MockBillingAdminService_ListSubscribers_Call {
	return &MockBillingAdminService_ListSubscribers_Call{Call: _e.mock.On("ListSubscribers", ctx)}
}

func (_c *MockBillingAdminService_ListSubscribers_Call) Run(run func(ctx context.Context)) *MockBillingAdminService_ListSubscribers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ListSubscribers_Call) Return(subscribers []*admin.Subscriber, n int, err error) *MockBillingAdminService_ListSubscribers_Call {
	_c.Call.Return(subscribers, n, err)
	return _c
}

func (_c *MockBillingAdminService_ListSubscribers_Call) RunAndReturn(run func(ctx context.Context) ([]*admin.Subscriber, int, error)) *MockBillingAdminService_ListSubscribers_Call {
	_c.Call.Return(run)
	return _c
}

// PauseUserSubscription provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) PauseUserSubscription(ctx context.Context, userID string) (*admin.ManagementResult, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for PauseUserSubscription")
	}

	var r0 *admin.ManagementResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.ManagementResult, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.ManagementResult); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ManagementResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_PauseUserSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseUserSubscription'
type MockBillingAdminService_PauseUserSubscription_Call struct {
	*mock.Call
}

// PauseUserSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBillingAdminService_Expecter) PauseUserSubscription(ctx interface{}, userID interface{}) *MockBillingAdminService_PauseUserSubscription_Call {
	return &MockBillingAdminService_PauseUserSubscription_Call{Call: _e.mock.On("PauseUserSubscription", ctx, userID)}
}

func (_c *MockBillingAdminService_PauseUserSubscription_Call) Run(run func(ctx context.Context, userID string)) *MockBillingAdminService_PauseUserSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_PauseUserSubscription_Call) Return(managementResult *admin.ManagementResult, err error) *MockBillingAdminService_PauseUserSubscription_Call {
	_c.Call.Return(managementResult, err)
	return _c
}

func (_c *MockBillingAdminService_PauseUserSubscription_Call) RunAndReturn(run func(ctx context.Context, userID string) (*admin.ManagementResult, error)) *MockBillingAdminService_PauseUserSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeCredits provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) PurgeCredits(ctx context.Context, req *admin.CreditPurgeRequest) (int, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PurgeCredits")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.CreditPurgeRequest) (int, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *admin.CreditPurgeRequest) int); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *admin.CreditPurgeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_PurgeCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeCredits'
type MockBillingAdminService_PurgeCredits_Call struct {
	*mock.Call
}

// PurgeCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - req *admin.CreditPurgeRequest
func (_e *MockBillingAdminService_Expecter) PurgeCredits(ctx interface{}, req interface{}) *MockBillingAdminService_PurgeCredits_Call {
	return &MockBillingAdminService_PurgeCredits_Call{Call: _e.mock.On("PurgeCredits", ctx, req)}
}

func (_c *MockBillingAdminService_PurgeCredits_Call) Run(run func(ctx context.Context, req *admin.CreditPurgeRequest)) *MockBillingAdminService_PurgeCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *admin.CreditPurgeRequest
		if args[1] != nil {
			arg1 = args[1].(*admin.CreditPurgeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_PurgeCredits_Call) Return(n int, err error) *MockBillingAdminService_PurgeCredits_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBillingAdminService_PurgeCredits_Call) RunAndReturn(run func(ctx context.Context, req *admin.CreditPurgeRequest) (int, error)) *MockBillingAdminService_PurgeCredits_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBillingAdminService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockBillingAdminService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockBillingAdminService_Expecter) RequireAuthenticated() *MockBillingAdminService_RequireAuthenticated_Call {
	return &MockBillingAdminService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockBillingAdminService_RequireAuthenticated_Call) Run(run func()) *MockBillingAdminService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBillingAdminService_RequireAuthenticated_Call) Return(err error) *MockBillingAdminService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBillingAdminService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockBillingAdminService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCredit provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) RestoreCredit(ctx context.Context, creditID string) (*admin.Credit, error) {
	ret := _mock.Called(ctx, creditID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCredit")
	}

	var r0 *admin.Credit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.Credit, error)); ok {
		return returnFunc(ctx, creditID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.Credit); ok {
		r0 = returnFunc(ctx, creditID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Credit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, creditID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_RestoreCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCredit'
type MockBillingAdminService_RestoreCredit_Call struct {
	*mock.Call
}

// RestoreCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - creditID string
func (_e *MockBillingAdminService_Expecter) RestoreCredit(ctx interface{}, creditID interface{}) *MockBillingAdminService_RestoreCredit_Call {
	return &MockBillingAdminService_RestoreCredit_Call{Call: _e.mock.On("RestoreCredit", ctx, creditID)}
}

func (_c *MockBillingAdminService_RestoreCredit_Call) Run(run func(ctx context.Context, creditID string)) *MockBillingAdminService_RestoreCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_RestoreCredit_Call) Return(credit *admin.Credit, err error) *MockBillingAdminService_RestoreCredit_Call {
	_c.Call.Return(credit, err)
	return _c
}

func (_c *MockBillingAdminService_RestoreCredit_Call) RunAndReturn(run func(ctx context.Context, creditID string) (*admin.Credit, error)) *MockBillingAdminService_RestoreCredit_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeUserSubscription provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) ResumeUserSubscription(ctx context.Context, userID string) (*admin.ManagementResult, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResumeUserSubscription")
	}

	var r0 *admin.ManagementResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.ManagementResult, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.ManagementResult); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ManagementResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_ResumeUserSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeUserSubscription'
type MockBillingAdminService_ResumeUserSubscription_Call struct {
	*mock.Call
}

// ResumeUserSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBillingAdminService_Expecter) ResumeUserSubscription(ctx interface{}, userID interface{}) *MockBillingAdminService_ResumeUserSubscription_Call {
	return &MockBillingAdminService_ResumeUserSubscription_Call{Call: _e.mock.On("ResumeUserSubscription", ctx, userID)}
}

func (_c *MockBillingAdminService_ResumeUserSubscription_Call) Run(run func(ctx context.Context, userID string)) *MockBillingAdminService_ResumeUserSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_ResumeUserSubscription_Call) Return(managementResult *admin.ManagementResult, err error) *MockBillingAdminService_ResumeUserSubscription_Call {
	_c.Call.Return(managementResult, err)
	return _c
}

func (_c *MockBillingAdminService_ResumeUserSubscription_Call) RunAndReturn(run func(ctx context.Context, userID string) (*admin.ManagementResult, error)) *MockBillingAdminService_ResumeUserSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlanPosition provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) UpdatePlanPosition(ctx context.Context, priceLineID string, planID string, req *admin.UpdatePlanPositionRequest) (*admin.PriceLineDetailResponse, error) {
	ret := _mock.Called(ctx, priceLineID, planID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlanPosition")
	}

	var r0 *admin.PriceLineDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *admin.UpdatePlanPositionRequest) (*admin.PriceLineDetailResponse, error)); ok {
		return returnFunc(ctx, priceLineID, planID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *admin.UpdatePlanPositionRequest) *admin.PriceLineDetailResponse); ok {
		r0 = returnFunc(ctx, priceLineID, planID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PriceLineDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *admin.UpdatePlanPositionRequest) error); ok {
		r1 = returnFunc(ctx, priceLineID, planID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_UpdatePlanPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlanPosition'
type MockBillingAdminService_UpdatePlanPosition_Call struct {
	*mock.Call
}

// UpdatePlanPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID string
//   - planID string
//   - req *admin.UpdatePlanPositionRequest
func (_e *MockBillingAdminService_Expecter) UpdatePlanPosition(ctx interface{}, priceLineID interface{}, planID interface{}, req interface{}) *MockBillingAdminService_UpdatePlanPosition_Call {
	return &MockBillingAdminService_UpdatePlanPosition_Call{Call: _e.mock.On("UpdatePlanPosition", ctx, priceLineID, planID, req)}
}

func (_c *MockBillingAdminService_UpdatePlanPosition_Call) Run(run func(ctx context.Context, priceLineID string, planID string, req *admin.UpdatePlanPositionRequest)) *MockBillingAdminService_UpdatePlanPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *admin.UpdatePlanPositionRequest
		if args[3] != nil {
			arg3 = args[3].(*admin.UpdatePlanPositionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_UpdatePlanPosition_Call) Return(priceLineDetailResponse *admin.PriceLineDetailResponse, err error) *MockBillingAdminService_UpdatePlanPosition_Call {
	_c.Call.Return(priceLineDetailResponse, err)
	return _c
}

func (_c *MockBillingAdminService_UpdatePlanPosition_Call) RunAndReturn(run func(ctx context.Context, priceLineID string, planID string, req *admin.UpdatePlanPositionRequest) (*admin.PriceLineDetailResponse, error)) *MockBillingAdminService_UpdatePlanPosition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriceLine provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) UpdatePriceLine(ctx context.Context, priceLineID string, req *admin.PriceLineUpdateRequest) (*admin.PriceLine, error) {
	ret := _mock.Called(ctx, priceLineID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriceLine")
	}

	var r0 *admin.PriceLine
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PriceLineUpdateRequest) (*admin.PriceLine, error)); ok {
		return returnFunc(ctx, priceLineID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PriceLineUpdateRequest) *admin.PriceLine); ok {
		r0 = returnFunc(ctx, priceLineID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PriceLine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.PriceLineUpdateRequest) error); ok {
		r1 = returnFunc(ctx, priceLineID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_UpdatePriceLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriceLine'
type MockBillingAdminService_UpdatePriceLine_Call struct {
	*mock.Call
}

// UpdatePriceLine is a helper method to define mock.On call
//   - ctx context.Context
//   - priceLineID string
//   - req *admin.PriceLineUpdateRequest
func (_e *MockBillingAdminService_Expecter) UpdatePriceLine(ctx interface{}, priceLineID interface{}, req interface{}) *MockBillingAdminService_UpdatePriceLine_Call {
	return &MockBillingAdminService_UpdatePriceLine_Call{Call: _e.mock.On("UpdatePriceLine", ctx, priceLineID, req)}
}

func (_c *MockBillingAdminService_UpdatePriceLine_Call) Run(run func(ctx context.Context, priceLineID string, req *admin.PriceLineUpdateRequest)) *MockBillingAdminService_UpdatePriceLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.PriceLineUpdateRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.PriceLineUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_UpdatePriceLine_Call) Return(priceLine *admin.PriceLine, err error) *MockBillingAdminService_UpdatePriceLine_Call {
	_c.Call.Return(priceLine, err)
	return _c
}

func (_c *MockBillingAdminService_UpdatePriceLine_Call) RunAndReturn(run func(ctx context.Context, priceLineID string, req *admin.PriceLineUpdateRequest) (*admin.PriceLine, error)) *MockBillingAdminService_UpdatePriceLine_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePricingPlan provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) UpdatePricingPlan(ctx context.Context, planID string, req *admin.PricingPlanUpdateRequest) (*admin.PricingPlan, error) {
	ret := _mock.Called(ctx, planID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePricingPlan")
	}

	var r0 *admin.PricingPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PricingPlanUpdateRequest) (*admin.PricingPlan, error)); ok {
		return returnFunc(ctx, planID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PricingPlanUpdateRequest) *admin.PricingPlan); ok {
		r0 = returnFunc(ctx, planID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PricingPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.PricingPlanUpdateRequest) error); ok {
		r1 = returnFunc(ctx, planID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_UpdatePricingPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePricingPlan'
type MockBillingAdminService_UpdatePricingPlan_Call struct {
	*mock.Call
}

// UpdatePricingPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - req *admin.PricingPlanUpdateRequest
func (_e *MockBillingAdminService_Expecter) UpdatePricingPlan(ctx interface{}, planID interface{}, req interface{}) *MockBillingAdminService_UpdatePricingPlan_Call {
	return &MockBillingAdminService_UpdatePricingPlan_Call{Call: _e.mock.On("UpdatePricingPlan", ctx, planID, req)}
}

func (_c *MockBillingAdminService_UpdatePricingPlan_Call) Run(run func(ctx context.Context, planID string, req *admin.PricingPlanUpdateRequest)) *MockBillingAdminService_UpdatePricingPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.PricingPlanUpdateRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.PricingPlanUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_UpdatePricingPlan_Call) Return(pricingPlan *admin.PricingPlan, err error) *MockBillingAdminService_UpdatePricingPlan_Call {
	_c.Call.Return(pricingPlan, err)
	return _c
}

func (_c *MockBillingAdminService_UpdatePricingPlan_Call) RunAndReturn(run func(ctx context.Context, planID string, req *admin.PricingPlanUpdateRequest) (*admin.PricingPlan, error)) *MockBillingAdminService_UpdatePricingPlan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePricingPlanPeriod provides a mock function for the type MockBillingAdminService
func (_mock *MockBillingAdminService) UpdatePricingPlanPeriod(ctx context.Context, periodID string, req *admin.PricingPlanPeriodUpdateRequest) (*admin.PricingPlanPeriod, error) {
	ret := _mock.Called(ctx, periodID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePricingPlanPeriod")
	}

	var r0 *admin.PricingPlanPeriod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PricingPlanPeriodUpdateRequest) (*admin.PricingPlanPeriod, error)); ok {
		return returnFunc(ctx, periodID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *admin.PricingPlanPeriodUpdateRequest) *admin.PricingPlanPeriod); ok {
		r0 = returnFunc(ctx, periodID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PricingPlanPeriod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *admin.PricingPlanPeriodUpdateRequest) error); ok {
		r1 = returnFunc(ctx, periodID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBillingAdminService_UpdatePricingPlanPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePricingPlanPeriod'
type MockBillingAdminService_UpdatePricingPlanPeriod_Call struct {
	*mock.Call
}

// UpdatePricingPlanPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - periodID string
//   - req *admin.PricingPlanPeriodUpdateRequest
func (_e *MockBillingAdminService_Expecter) UpdatePricingPlanPeriod(ctx interface{}, periodID interface{}, req interface{}) *MockBillingAdminService_UpdatePricingPlanPeriod_Call {
	return &MockBillingAdminService_UpdatePricingPlanPeriod_Call{Call: _e.mock.On("UpdatePricingPlanPeriod", ctx, periodID, req)}
}

func (_c *MockBillingAdminService_UpdatePricingPlanPeriod_Call) Run(run func(ctx context.Context, periodID string, req *admin.PricingPlanPeriodUpdateRequest)) *MockBillingAdminService_UpdatePricingPlanPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *admin.PricingPlanPeriodUpdateRequest
		if args[2] != nil {
			arg2 = args[2].(*admin.PricingPlanPeriodUpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBillingAdminService_UpdatePricingPlanPeriod_Call) Return(pricingPlanPeriod *admin.PricingPlanPeriod, err error) *MockBillingAdminService_UpdatePricingPlanPeriod_Call {
	_c.Call.Return(pricingPlanPeriod, err)
	return _c
}

func (_c *MockBillingAdminService_UpdatePricingPlanPeriod_Call) RunAndReturn(run func(ctx context.Context, periodID string, req *admin.PricingPlanPeriodUpdateRequest) (*admin.PricingPlanPeriod, error)) *MockBillingAdminService_UpdatePricingPlanPeriod_Call {
	_c.Call.Return(run)
	return _c
}
