// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk"
)

// NewMockAPIKeyService creates a new instance of MockAPIKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyService {
	mock := &MockAPIKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyService is an autogenerated mock type for the APIKeyService type
type MockAPIKeyService struct {
	mock.Mock
}

type MockAPIKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyService) EXPECT() *MockAPIKeyService_Expecter {
	return &MockAPIKeyService_Expecter{mock: &_m.Mock}
}

// CreateAPIKey provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) CreateAPIKey(ctx context.Context, name string) (*account.APIKey, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIKey")
	}

	var r0 *account.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.APIKey, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.APIKey); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyService_CreateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIKey'
type MockAPIKeyService_CreateAPIKey_Call struct {
	*mock.Call
}

// CreateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAPIKeyService_Expecter) CreateAPIKey(ctx interface{}, name interface{}) *MockAPIKeyService_CreateAPIKey_Call {
	return &MockAPIKeyService_CreateAPIKey_Call{Call: _e.mock.On("CreateAPIKey", ctx, name)}
}

func (_c *MockAPIKeyService_CreateAPIKey_Call) Run(run func(ctx context.Context, name string)) *MockAPIKeyService_CreateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_CreateAPIKey_Call) Return(aPIKey *account.APIKey, err error) *MockAPIKeyService_CreateAPIKey_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyService_CreateAPIKey_Call) RunAndReturn(run func(ctx context.Context, name string) (*account.APIKey, error)) *MockAPIKeyService_CreateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAPIKey provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) DeleteAPIKey(ctx context.Context, idOrName string, force bool) error {
	ret := _mock.Called(ctx, idOrName, force)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAPIKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, idOrName, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyService_DeleteAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAPIKey'
type MockAPIKeyService_DeleteAPIKey_Call struct {
	*mock.Call
}

// DeleteAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - idOrName string
//   - force bool
func (_e *MockAPIKeyService_Expecter) DeleteAPIKey(ctx interface{}, idOrName interface{}, force interface{}) *MockAPIKeyService_DeleteAPIKey_Call {
	return &MockAPIKeyService_DeleteAPIKey_Call{Call: _e.mock.On("DeleteAPIKey", ctx, idOrName, force)}
}

func (_c *MockAPIKeyService_DeleteAPIKey_Call) Run(run func(ctx context.Context, idOrName string, force bool)) *MockAPIKeyService_DeleteAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_DeleteAPIKey_Call) Return(err error) *MockAPIKeyService_DeleteAPIKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyService_DeleteAPIKey_Call) RunAndReturn(run func(ctx context.Context, idOrName string, force bool) error) *MockAPIKeyService_DeleteAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentAPIKeyUUID provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) GetCurrentAPIKeyUUID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentAPIKeyUUID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPIKeyService_GetCurrentAPIKeyUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentAPIKeyUUID'
type MockAPIKeyService_GetCurrentAPIKeyUUID_Call struct {
	*mock.Call
}

// GetCurrentAPIKeyUUID is a helper method to define mock.On call
func (_e *MockAPIKeyService_Expecter) GetCurrentAPIKeyUUID() *MockAPIKeyService_GetCurrentAPIKeyUUID_Call {
	return &MockAPIKeyService_GetCurrentAPIKeyUUID_Call{Call: _e.mock.On("GetCurrentAPIKeyUUID")}
}

func (_c *MockAPIKeyService_GetCurrentAPIKeyUUID_Call) Run(run func()) *MockAPIKeyService_GetCurrentAPIKeyUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIKeyService_GetCurrentAPIKeyUUID_Call) Return(s string) *MockAPIKeyService_GetCurrentAPIKeyUUID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPIKeyService_GetCurrentAPIKeyUUID_Call) RunAndReturn(run func() string) *MockAPIKeyService_GetCurrentAPIKeyUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAPIKeys provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) ListAPIKeys(ctx context.Context, search string) ([]*account.APIKey, int, error) {
	ret := _mock.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for ListAPIKeys")
	}

	var r0 []*account.APIKey
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*account.APIKey, int, error)); ok {
		return returnFunc(ctx, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*account.APIKey); ok {
		r0 = returnFunc(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(ctx, search)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIKeyService_ListAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAPIKeys'
type MockAPIKeyService_ListAPIKeys_Call struct {
	*mock.Call
}

// ListAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
func (_e *MockAPIKeyService_Expecter) ListAPIKeys(ctx interface{}, search interface{}) *MockAPIKeyService_ListAPIKeys_Call {
	return &MockAPIKeyService_ListAPIKeys_Call{Call: _e.mock.On("ListAPIKeys", ctx, search)}
}

func (_c *MockAPIKeyService_ListAPIKeys_Call) Run(run func(ctx context.Context, search string)) *MockAPIKeyService_ListAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_ListAPIKeys_Call) Return(aPIKeys []*account.APIKey, n int, err error) *MockAPIKeyService_ListAPIKeys_Call {
	_c.Call.Return(aPIKeys, n, err)
	return _c
}

func (_c *MockAPIKeyService_ListAPIKeys_Call) RunAndReturn(run func(ctx context.Context, search string) ([]*account.APIKey, int, error)) *MockAPIKeyService_ListAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockAPIKeyService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockAPIKeyService_Expecter) RequireAuthenticated() *MockAPIKeyService_RequireAuthenticated_Call {
	return &MockAPIKeyService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockAPIKeyService_RequireAuthenticated_Call) Run(run func()) *MockAPIKeyService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIKeyService_RequireAuthenticated_Call) Return(err error) *MockAPIKeyService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockAPIKeyService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}
