// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/admin"
)

// NewMockWebsiteAdminService creates a new instance of MockWebsiteAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsiteAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsiteAdminService {
	mock := &MockWebsiteAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebsiteAdminService is an autogenerated mock type for the WebsiteAdminService type
type MockWebsiteAdminService struct {
	mock.Mock
}

type MockWebsiteAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsiteAdminService) EXPECT() *MockWebsiteAdminService_Expecter {
	return &MockWebsiteAdminService_Expecter{mock: &_m.Mock}
}

// BlockWebsite provides a mock function for the type MockWebsiteAdminService
func (_mock *MockWebsiteAdminService) BlockWebsite(ctx context.Context, id string) (*admin.Website, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BlockWebsite")
	}

	var r0 *admin.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.Website, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.Website); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteAdminService_BlockWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockWebsite'
type MockWebsiteAdminService_BlockWebsite_Call struct {
	*mock.Call
}

// BlockWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsiteAdminService_Expecter) BlockWebsite(ctx interface{}, id interface{}) *MockWebsiteAdminService_BlockWebsite_Call {
	return &MockWebsiteAdminService_BlockWebsite_Call{Call: _e.mock.On("BlockWebsite", ctx, id)}
}

func (_c *MockWebsiteAdminService_BlockWebsite_Call) Run(run func(ctx context.Context, id string)) *MockWebsiteAdminService_BlockWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteAdminService_BlockWebsite_Call) Return(website *admin.Website, err error) *MockWebsiteAdminService_BlockWebsite_Call {
	_c.Call.Return(website, err)
	return _c
}

func (_c *MockWebsiteAdminService_BlockWebsite_Call) RunAndReturn(run func(ctx context.Context, id string) (*admin.Website, error)) *MockWebsiteAdminService_BlockWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuthenticated provides a mock function for the type MockWebsiteAdminService
func (_mock *MockWebsiteAdminService) RequireAuthenticated() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuthenticated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsiteAdminService_RequireAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuthenticated'
type MockWebsiteAdminService_RequireAuthenticated_Call struct {
	*mock.Call
}

// RequireAuthenticated is a helper method to define mock.On call
func (_e *MockWebsiteAdminService_Expecter) RequireAuthenticated() *MockWebsiteAdminService_RequireAuthenticated_Call {
	return &MockWebsiteAdminService_RequireAuthenticated_Call{Call: _e.mock.On("RequireAuthenticated")}
}

func (_c *MockWebsiteAdminService_RequireAuthenticated_Call) Run(run func()) *MockWebsiteAdminService_RequireAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteAdminService_RequireAuthenticated_Call) Return(err error) *MockWebsiteAdminService_RequireAuthenticated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsiteAdminService_RequireAuthenticated_Call) RunAndReturn(run func() error) *MockWebsiteAdminService_RequireAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockWebsite provides a mock function for the type MockWebsiteAdminService
func (_mock *MockWebsiteAdminService) UnblockWebsite(ctx context.Context, id string) (*admin.Website, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnblockWebsite")
	}

	var r0 *admin.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.Website, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.Website); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteAdminService_UnblockWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockWebsite'
type MockWebsiteAdminService_UnblockWebsite_Call struct {
	*mock.Call
}

// UnblockWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsiteAdminService_Expecter) UnblockWebsite(ctx interface{}, id interface{}) *MockWebsiteAdminService_UnblockWebsite_Call {
	return &MockWebsiteAdminService_UnblockWebsite_Call{Call: _e.mock.On("UnblockWebsite", ctx, id)}
}

func (_c *MockWebsiteAdminService_UnblockWebsite_Call) Run(run func(ctx context.Context, id string)) *MockWebsiteAdminService_UnblockWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteAdminService_UnblockWebsite_Call) Return(website *admin.Website, err error) *MockWebsiteAdminService_UnblockWebsite_Call {
	_c.Call.Return(website, err)
	return _c
}

func (_c *MockWebsiteAdminService_UnblockWebsite_Call) RunAndReturn(run func(ctx context.Context, id string) (*admin.Website, error)) *MockWebsiteAdminService_UnblockWebsite_Call {
	_c.Call.Return(run)
	return _c
}
