#!/usr/bin/env python3
"""
gen_server_stub.py — generate a 501-default implementation of an
oapi-codegen ServerInterface so a swagger-derived test double can serve a
contract-complete HTTP surface without nil-interface panics.

Reads a generated server file (server.gen.go), finds `type ServerInterface
interface {...}`, and emits `<out>.stub.go` implementing every method to
return HTTP 501. The fake-data implementation embeds this stub and overrides
only the endpoints it actually serves.

Usage:
  gen_server_stub.py <server.gen.go> <pkgname> <out>.stub.go
"""

import re
import sys


def parse_methods(text: str):
    """Extract (name, params, results) tuples from the ServerInterface block."""
    m = re.search(r"type ServerInterface interface \{(.*?)\n\}", text, re.S)
    if not m:
        raise SystemExit("ERROR: could not find 'type ServerInterface interface' block")
    body = m.group(1)
    methods = []
    # Each method: Name(param1, param2) (result1, result2)  (possibly multi-line)
    # Strip comment lines.
    for raw in body.split("\n"):
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("/*"):
            continue
        # Accumulate multi-line signatures until a line's parens balance.
        if "(" not in line:
            # Might be a continuation; safety: join with previous if imbalanced.
            continue
        # Find name before first '('
        name = line.split("(")[0].split()[0]
        # Parse params: everything between first '(' and its matching ')'.
        depth = 0
        start = line.index("(")
        params = ""
        i = start
        while i < len(line):
            c = line[i]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            params += c
            i += 1
        params = params[1:]  # drop leading '('
        rest = line[i + 1 :].strip()
        methods.append((name, params, rest))
    return methods


def render(pkg: str, methods):
    lines = []
    lines.append("// Code generated by gen_server_stub.py; DO NOT EDIT.")
    lines.append("")
    lines.append(f"package {pkg}")
    lines.append("")
    lines.append('import (')
    lines.append('\t"net/http"')
    lines.append(')')
    lines.append("")
    lines.append(
        "// serverStub implements every ServerInterface method, returning HTTP 501"
    )
    lines.append(
        "// for endpoints that are not overridden by the fake-data implementation."
    )
    lines.append("// Embedding this gives a clean 501 (not a nil-interface panic) for")
    lines.append("// any endpoint the client reaches that the fake does not explicitly serve.")
    lines.append("type serverStub struct{}")
    lines.append("")
    for name, params, rest in methods:
        # Normalize whitespace in params. The interface methods already include
        # (w http.ResponseWriter, r *http.Request, ...) as their full signature,
        # so copy them verbatim — do NOT prepend w/r again.
        p = " ".join(params.split())
        r = " ".join(rest.split())
        sig = f"func (serverStub) {name}({p})"
        if r:
            sig += " " + r
        lines.append(sig + " {")
        lines.append('\thttp.Error(w, "not implemented", http.StatusNotImplemented)')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    src, pkg, out = sys.argv[1], sys.argv[2], sys.argv[3]
    text = open(src).read()
    methods = parse_methods(text)
    code = render(pkg, methods)
    with open(out, "w") as f:
        f.write(code)
    print(f"wrote {out}: {len(methods)} stub methods")


if __name__ == "__main__":
    main()
