// Command gen-server-stub generates a 501-default implementation of an
// oapi-codegen ServerInterface so a swagger-derived test double can serve a
// contract-complete HTTP surface without nil-interface panics.
//
// It parses a generated server file (server.gen.go) with go/ast, finds the
// `type ServerInterface interface` declaration, and emits a serverStub type
// implementing every method to return HTTP 501. The fake-data implementation
// (server.go) embeds this stub and overrides only the endpoints it serves.
// Regenerate via go:generate:
//
//	go run ./cmd/gen-server-stub <server.gen.go> <pkgname> <out>.stub.go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"strings"
	"text/template"
)

// method is one ServerInterface method to stub out.
type method struct {
	Name    string
	Params  string // full parenthesized parameter list, as source
	Results string // full result list (may be empty), as source
	// W is the name of the http.ResponseWriter parameter, used for the 501
	// body. Picked from the actual signature so the generated code compiles
	// even when oapi-codegen names it something other than w.
	W string
	// HasResults is true when the method declares result values, in which case
	// the stub must return zero values rather than falling off the end.
	HasResults bool
}

const tmpl = `// Code generated by gen-server-stub (go/ast + text/template); DO NOT EDIT.

package {{.Pkg}}

import (
	"net/http"
)

// {{.StubName}} implements every ServerInterface method, returning HTTP 501
// for endpoints that are not overridden by the fake-data implementation.
// Embedding this gives a clean 501 (not a nil-interface panic) for
// any endpoint the client reaches that the fake does not explicitly serve.
type {{.StubName}} struct{}

{{range .Methods}}func ({{$.StubName}}) {{.Name}}({{.Params}}){{if .Results}} {{.Results}}{{end}} {
	http.Error({{.W}}, "not implemented", http.StatusNotImplemented){{if .HasResults}}
	return{{end}}
}

{{end}}`

type data struct {
	Pkg      string
	StubName string
	Methods  []method
}

// renderField renders one field (possibly several comma-separated names of one
// type) as Go source, e.g. "w http.ResponseWriter" or "id string, name string".
func renderField(f *ast.Field) string {
	n := len(f.Names)
	t := types.ExprString(f.Type)
	if n == 0 {
		// anonymous/embedded field type
		return t
	}
	names := make([]string, n)
	for i, nm := range f.Names {
		names[i] = nm.Name
	}
	return strings.Join(names, ", ") + " " + t
}

// renderFieldList renders an entire parameter or result list.
func renderFieldList(lst *ast.FieldList) string {
	if lst == nil {
		return ""
	}
	parts := make([]string, 0, len(lst.List))
	for _, f := range lst.List {
		if s := renderField(f); s != "" {
			parts = append(parts, s)
		}
	}
	return strings.Join(parts, ", ")
}

// extractMethods pulls every method out of the ServerInterface type.
func extractMethods(fset *token.FileSet, src *ast.File) ([]method, error) {
	var it *ast.InterfaceType
	ast.Inspect(src, func(n ast.Node) bool {
		if ts, ok := n.(*ast.TypeSpec); ok && ts.Name.Name == "ServerInterface" {
			if it2, ok := ts.Type.(*ast.InterfaceType); ok {
				it = it2
				return false
			}
		}
		return true
	})
	if it == nil {
		return nil, fmt.Errorf("could not find 'type ServerInterface interface' in %s", fset.Position(src.Pos()))
	}

	var methods []method
	for _, f := range it.Methods.List {
		// embedded interface? oapi-codegen emits concrete methods only, but be
		// safe: a field with no names and type ident is an embed.
		if len(f.Names) == 0 {
			continue
		}
		fn, ok := f.Type.(*ast.FuncType)
		if !ok {
			continue
		}
		methods = append(methods, method{
			Name:       f.Names[0].Name,
			Params:     renderFieldList(fn.Params), // parens are added by the template
			Results:    renderResults(fn.Results),
			W:          writerParamName(fn.Params),
			HasResults: fn.Results != nil && len(fn.Results.List) > 0,
		})
	}
	return methods, nil
}

// writerParamName returns the name of the http.ResponseWriter parameter, which
// the stub body uses to write the 501. Falls back to "w" (oapi-codegen's
// convention) when none is found.
func writerParamName(lst *ast.FieldList) string {
	if lst == nil {
		return "w"
	}
	for _, f := range lst.List {
		t := types.ExprString(f.Type)
		if t == "http.ResponseWriter" && len(f.Names) > 0 {
			return f.Names[0].Name
		}
	}
	return "w"
}

func renderResults(lst *ast.FieldList) string {
	if lst == nil || len(lst.List) == 0 {
		return ""
	}
	s := renderFieldList(lst)
	// single unnamed result stays bare; multiple or named results need parens
	if strings.Contains(s, ",") || strings.Contains(s, " ") {
		return "(" + s + ")"
	}
	return s
}

func main() {
	if len(os.Args) != 4 {
		fmt.Fprintln(os.Stderr, "usage: gen-server-stub <server.gen.go> <pkgname> <out>.stub.go")
		os.Exit(2)
	}
	srcPath, pkg, outPath := os.Args[1], os.Args[2], os.Args[3]

	fset := token.NewFileSet()
	parsed, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", srcPath, err)
		os.Exit(1)
	}

	methods, err := extractMethods(fset, parsed)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	d := data{Pkg: pkg, StubName: "serverStub", Methods: methods}
	t, err := template.New("stub").Parse(tmpl)
	if err != nil {
		fmt.Fprintf(os.Stderr, "template: %v\n", err)
		os.Exit(1)
	}

	var sb strings.Builder
	if err := t.Execute(&sb, d); err != nil {
		fmt.Fprintf(os.Stderr, "render: %v\n", err)
		os.Exit(1)
	}
	out := strings.TrimRight(sb.String(), "\n") + "\n"
	if err := os.WriteFile(outPath, []byte(out), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s: %d stub methods\n", outPath, len(methods))
}
