// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/boxo/pinning/remote/client"
	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPinningClient creates a new instance of MockPinningClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinningClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinningClient {
	mock := &MockPinningClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPinningClient is an autogenerated mock type for the PinningClient type
type MockPinningClient struct {
	mock.Mock
}

type MockPinningClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinningClient) EXPECT() *MockPinningClient_Expecter {
	return &MockPinningClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockPinningClient
func (_mock *MockPinningClient) Add(ctx context.Context, cid1 cid.Cid, opts ...go_pinning_service_http_client.AddOption) (go_pinning_service_http_client.PinStatusGetter, error) {
	// go_pinning_service_http_client.AddOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 go_pinning_service_http_client.PinStatusGetter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, ...go_pinning_service_http_client.AddOption) (go_pinning_service_http_client.PinStatusGetter, error)); ok {
		return returnFunc(ctx, cid1, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, ...go_pinning_service_http_client.AddOption) go_pinning_service_http_client.PinStatusGetter); ok {
		r0 = returnFunc(ctx, cid1, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(go_pinning_service_http_client.PinStatusGetter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, ...go_pinning_service_http_client.AddOption) error); ok {
		r1 = returnFunc(ctx, cid1, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockPinningClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - cid1 cid.Cid
//   - opts ...go_pinning_service_http_client.AddOption
func (_e *MockPinningClient_Expecter) Add(ctx interface{}, cid1 interface{}, opts ...interface{}) *MockPinningClient_Add_Call {
	return &MockPinningClient_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx, cid1}, opts...)...)}
}

func (_c *MockPinningClient_Add_Call) Run(run func(ctx context.Context, cid1 cid.Cid, opts ...go_pinning_service_http_client.AddOption)) *MockPinningClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 []go_pinning_service_http_client.AddOption
		variadicArgs := make([]go_pinning_service_http_client.AddOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(go_pinning_service_http_client.AddOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPinningClient_Add_Call) Return(pinStatusGetter go_pinning_service_http_client.PinStatusGetter, err error) *MockPinningClient_Add_Call {
	_c.Call.Return(pinStatusGetter, err)
	return _c
}

func (_c *MockPinningClient_Add_Call) RunAndReturn(run func(ctx context.Context, cid1 cid.Cid, opts ...go_pinning_service_http_client.AddOption) (go_pinning_service_http_client.PinStatusGetter, error)) *MockPinningClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockPinningClient
func (_mock *MockPinningClient) DeleteByID(ctx context.Context, pinID string) error {
	ret := _mock.Called(ctx, pinID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pinID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinningClient_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockPinningClient_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - pinID string
func (_e *MockPinningClient_Expecter) DeleteByID(ctx interface{}, pinID interface{}) *MockPinningClient_DeleteByID_Call {
	return &MockPinningClient_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, pinID)}
}

func (_c *MockPinningClient_DeleteByID_Call) Run(run func(ctx context.Context, pinID string)) *MockPinningClient_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPinningClient_DeleteByID_Call) Return(err error) *MockPinningClient_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinningClient_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, pinID string) error) *MockPinningClient_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusByID provides a mock function for the type MockPinningClient
func (_mock *MockPinningClient) GetStatusByID(ctx context.Context, pinID string) (go_pinning_service_http_client.PinStatusGetter, error) {
	ret := _mock.Called(ctx, pinID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusByID")
	}

	var r0 go_pinning_service_http_client.PinStatusGetter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (go_pinning_service_http_client.PinStatusGetter, error)); ok {
		return returnFunc(ctx, pinID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) go_pinning_service_http_client.PinStatusGetter); ok {
		r0 = returnFunc(ctx, pinID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(go_pinning_service_http_client.PinStatusGetter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pinID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningClient_GetStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusByID'
type MockPinningClient_GetStatusByID_Call struct {
	*mock.Call
}

// GetStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - pinID string
func (_e *MockPinningClient_Expecter) GetStatusByID(ctx interface{}, pinID interface{}) *MockPinningClient_GetStatusByID_Call {
	return &MockPinningClient_GetStatusByID_Call{Call: _e.mock.On("GetStatusByID", ctx, pinID)}
}

func (_c *MockPinningClient_GetStatusByID_Call) Run(run func(ctx context.Context, pinID string)) *MockPinningClient_GetStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPinningClient_GetStatusByID_Call) Return(pinStatusGetter go_pinning_service_http_client.PinStatusGetter, err error) *MockPinningClient_GetStatusByID_Call {
	_c.Call.Return(pinStatusGetter, err)
	return _c
}

func (_c *MockPinningClient_GetStatusByID_Call) RunAndReturn(run func(ctx context.Context, pinID string) (go_pinning_service_http_client.PinStatusGetter, error)) *MockPinningClient_GetStatusByID_Call {
	_c.Call.Return(run)
	return _c
}

// LsSync provides a mock function for the type MockPinningClient
func (_mock *MockPinningClient) LsSync(ctx context.Context, opts ...go_pinning_service_http_client.LsOption) ([]go_pinning_service_http_client.PinStatusGetter, error) {
	// go_pinning_service_http_client.LsOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LsSync")
	}

	var r0 []go_pinning_service_http_client.PinStatusGetter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...go_pinning_service_http_client.LsOption) ([]go_pinning_service_http_client.PinStatusGetter, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...go_pinning_service_http_client.LsOption) []go_pinning_service_http_client.PinStatusGetter); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]go_pinning_service_http_client.PinStatusGetter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...go_pinning_service_http_client.LsOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningClient_LsSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LsSync'
type MockPinningClient_LsSync_Call struct {
	*mock.Call
}

// LsSync is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...go_pinning_service_http_client.LsOption
func (_e *MockPinningClient_Expecter) LsSync(ctx interface{}, opts ...interface{}) *MockPinningClient_LsSync_Call {
	return &MockPinningClient_LsSync_Call{Call: _e.mock.On("LsSync",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockPinningClient_LsSync_Call) Run(run func(ctx context.Context, opts ...go_pinning_service_http_client.LsOption)) *MockPinningClient_LsSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []go_pinning_service_http_client.LsOption
		variadicArgs := make([]go_pinning_service_http_client.LsOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(go_pinning_service_http_client.LsOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockPinningClient_LsSync_Call) Return(pinStatusGetters []go_pinning_service_http_client.PinStatusGetter, err error) *MockPinningClient_LsSync_Call {
	_c.Call.Return(pinStatusGetters, err)
	return _c
}

func (_c *MockPinningClient_LsSync_Call) RunAndReturn(run func(ctx context.Context, opts ...go_pinning_service_http_client.LsOption) ([]go_pinning_service_http_client.PinStatusGetter, error)) *MockPinningClient_LsSync_Call {
	_c.Call.Return(run)
	return _c
}

// LsWithLimit provides a mock function for the type MockPinningClient
func (_mock *MockPinningClient) LsWithLimit(ctx context.Context, limit int, opts ...go_pinning_service_http_client.LsOption) ([]go_pinning_service_http_client.PinStatusGetter, error) {
	// go_pinning_service_http_client.LsOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, limit)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LsWithLimit")
	}

	var r0 []go_pinning_service_http_client.PinStatusGetter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...go_pinning_service_http_client.LsOption) ([]go_pinning_service_http_client.PinStatusGetter, error)); ok {
		return returnFunc(ctx, limit, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...go_pinning_service_http_client.LsOption) []go_pinning_service_http_client.PinStatusGetter); ok {
		r0 = returnFunc(ctx, limit, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]go_pinning_service_http_client.PinStatusGetter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...go_pinning_service_http_client.LsOption) error); ok {
		r1 = returnFunc(ctx, limit, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningClient_LsWithLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LsWithLimit'
type MockPinningClient_LsWithLimit_Call struct {
	*mock.Call
}

// LsWithLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - opts ...go_pinning_service_http_client.LsOption
func (_e *MockPinningClient_Expecter) LsWithLimit(ctx interface{}, limit interface{}, opts ...interface{}) *MockPinningClient_LsWithLimit_Call {
	return &MockPinningClient_LsWithLimit_Call{Call: _e.mock.On("LsWithLimit",
		append([]interface{}{ctx, limit}, opts...)...)}
}

func (_c *MockPinningClient_LsWithLimit_Call) Run(run func(ctx context.Context, limit int, opts ...go_pinning_service_http_client.LsOption)) *MockPinningClient_LsWithLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []go_pinning_service_http_client.LsOption
		variadicArgs := make([]go_pinning_service_http_client.LsOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(go_pinning_service_http_client.LsOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPinningClient_LsWithLimit_Call) Return(pinStatusGetters []go_pinning_service_http_client.PinStatusGetter, err error) *MockPinningClient_LsWithLimit_Call {
	_c.Call.Return(pinStatusGetters, err)
	return _c
}

func (_c *MockPinningClient_LsWithLimit_Call) RunAndReturn(run func(ctx context.Context, limit int, opts ...go_pinning_service_http_client.LsOption) ([]go_pinning_service_http_client.PinStatusGetter, error)) *MockPinningClient_LsWithLimit_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockPinningClient
func (_mock *MockPinningClient) Replace(ctx context.Context, pinID string, cid1 cid.Cid, opts ...go_pinning_service_http_client.AddOption) (go_pinning_service_http_client.PinStatusGetter, error) {
	// go_pinning_service_http_client.AddOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, pinID, cid1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 go_pinning_service_http_client.PinStatusGetter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cid.Cid, ...go_pinning_service_http_client.AddOption) (go_pinning_service_http_client.PinStatusGetter, error)); ok {
		return returnFunc(ctx, pinID, cid1, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cid.Cid, ...go_pinning_service_http_client.AddOption) go_pinning_service_http_client.PinStatusGetter); ok {
		r0 = returnFunc(ctx, pinID, cid1, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(go_pinning_service_http_client.PinStatusGetter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cid.Cid, ...go_pinning_service_http_client.AddOption) error); ok {
		r1 = returnFunc(ctx, pinID, cid1, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPinningClient_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockPinningClient_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - pinID string
//   - cid1 cid.Cid
//   - opts ...go_pinning_service_http_client.AddOption
func (_e *MockPinningClient_Expecter) Replace(ctx interface{}, pinID interface{}, cid1 interface{}, opts ...interface{}) *MockPinningClient_Replace_Call {
	return &MockPinningClient_Replace_Call{Call: _e.mock.On("Replace",
		append([]interface{}{ctx, pinID, cid1}, opts...)...)}
}

func (_c *MockPinningClient_Replace_Call) Run(run func(ctx context.Context, pinID string, cid1 cid.Cid, opts ...go_pinning_service_http_client.AddOption)) *MockPinningClient_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cid.Cid
		if args[2] != nil {
			arg2 = args[2].(cid.Cid)
		}
		var arg3 []go_pinning_service_http_client.AddOption
		variadicArgs := make([]go_pinning_service_http_client.AddOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(go_pinning_service_http_client.AddOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockPinningClient_Replace_Call) Return(pinStatusGetter go_pinning_service_http_client.PinStatusGetter, err error) *MockPinningClient_Replace_Call {
	_c.Call.Return(pinStatusGetter, err)
	return _c
}

func (_c *MockPinningClient_Replace_Call) RunAndReturn(run func(ctx context.Context, pinID string, cid1 cid.Cid, opts ...go_pinning_service_http_client.AddOption) (go_pinning_service_http_client.PinStatusGetter, error)) *MockPinningClient_Replace_Call {
	_c.Call.Return(run)
	return _c
}
