// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vault

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVaultService creates a new instance of MockVaultService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultService {
	mock := &MockVaultService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVaultService is an autogenerated mock type for the VaultService type
type MockVaultService struct {
	mock.Mock
}

type MockVaultService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultService) EXPECT() *MockVaultService_Expecter {
	return &MockVaultService_Expecter{mock: &_m.Mock}
}

// Cat provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Cat(ctx context.Context, vaultPath string, w io.Writer) error {
	ret := _mock.Called(ctx, vaultPath, w)

	if len(ret) == 0 {
		panic("no return value specified for Cat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, vaultPath, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_Cat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cat'
type MockVaultService_Cat_Call struct {
	*mock.Call
}

// Cat is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - w io.Writer
func (_e *MockVaultService_Expecter) Cat(ctx any, vaultPath any, w any) *MockVaultService_Cat_Call {
	return &MockVaultService_Cat_Call{Call: _e.mock.On("Cat", ctx, vaultPath, w)}
}

func (_c *MockVaultService_Cat_Call) Run(run func(ctx context.Context, vaultPath string, w io.Writer)) *MockVaultService_Cat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultService_Cat_Call) Return(err error) *MockVaultService_Cat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_Cat_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, w io.Writer) error) *MockVaultService_Cat_Call {
	_c.Call.Return(run)
	return _c
}

// CheckReady provides a mock function for the type MockVaultService
func (_mock *MockVaultService) CheckReady(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_CheckReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckReady'
type MockVaultService_CheckReady_Call struct {
	*mock.Call
}

// CheckReady is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVaultService_Expecter) CheckReady(ctx any) *MockVaultService_CheckReady_Call {
	return &MockVaultService_CheckReady_Call{Call: _e.mock.On("CheckReady", ctx)}
}

func (_c *MockVaultService_CheckReady_Call) Run(run func(ctx context.Context)) *MockVaultService_CheckReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVaultService_CheckReady_Call) Return(err error) *MockVaultService_CheckReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_CheckReady_Call) RunAndReturn(run func(ctx context.Context) error) *MockVaultService_CheckReady_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockVaultService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockVaultService_Expecter) Close() *MockVaultService_Close_Call {
	return &MockVaultService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockVaultService_Close_Call) Run(run func()) *MockVaultService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVaultService_Close_Call) Return(err error) *MockVaultService_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_Close_Call) RunAndReturn(run func() error) *MockVaultService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Get(ctx context.Context, vaultPath string, w io.Writer) error {
	ret := _mock.Called(ctx, vaultPath, w)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, vaultPath, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVaultService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - w io.Writer
func (_e *MockVaultService_Expecter) Get(ctx any, vaultPath any, w any) *MockVaultService_Get_Call {
	return &MockVaultService_Get_Call{Call: _e.mock.On("Get", ctx, vaultPath, w)}
}

func (_c *MockVaultService_Get_Call) Run(run func(ctx context.Context, vaultPath string, w io.Writer)) *MockVaultService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultService_Get_Call) Return(err error) *MockVaultService_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_Get_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, w io.Writer) error) *MockVaultService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVaultService
func (_mock *MockVaultService) List(ctx context.Context, vaultPath string) ([]ListItem, error) {
	ret := _mock.Called(ctx, vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ListItem, error)); ok {
		return returnFunc(ctx, vaultPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ListItem); ok {
		r0 = returnFunc(ctx, vaultPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vaultPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVaultService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
func (_e *MockVaultService_Expecter) List(ctx any, vaultPath any) *MockVaultService_List_Call {
	return &MockVaultService_List_Call{Call: _e.mock.On("List", ctx, vaultPath)}
}

func (_c *MockVaultService_List_Call) Run(run func(ctx context.Context, vaultPath string)) *MockVaultService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultService_List_Call) Return(listItems []ListItem, err error) *MockVaultService_List_Call {
	_c.Call.Return(listItems, err)
	return _c
}

func (_c *MockVaultService_List_Call) RunAndReturn(run func(ctx context.Context, vaultPath string) ([]ListItem, error)) *MockVaultService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Search(ctx context.Context, filter SearchFilter) ([]SearchItem, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []SearchItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SearchFilter) ([]SearchItem, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SearchFilter) []SearchItem); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SearchFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockVaultService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter SearchFilter
func (_e *MockVaultService_Expecter) Search(ctx any, filter any) *MockVaultService_Search_Call {
	return &MockVaultService_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockVaultService_Search_Call) Run(run func(ctx context.Context, filter SearchFilter)) *MockVaultService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SearchFilter
		if args[1] != nil {
			arg1 = args[1].(SearchFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultService_Search_Call) Return(searchItems []SearchItem, err error) *MockVaultService_Search_Call {
	_c.Call.Return(searchItems, err)
	return _c
}

func (_c *MockVaultService_Search_Call) RunAndReturn(run func(ctx context.Context, filter SearchFilter) ([]SearchItem, error)) *MockVaultService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Put(ctx context.Context, r io.Reader, size int64, vaultPath string, metadata map[string]any) (*File, error) {
	ret := _mock.Called(ctx, r, size, vaultPath, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int64, string, map[string]any) (*File, error)); ok {
		return returnFunc(ctx, r, size, vaultPath, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int64, string, map[string]any) *File); ok {
		r0 = returnFunc(ctx, r, size, vaultPath, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, int64, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, r, size, vaultPath, metadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockVaultService_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - r io.Reader
//   - size int64
//   - vaultPath string
//   - metadata map[string]any
func (_e *MockVaultService_Expecter) Put(ctx any, r any, size any, vaultPath any, metadata any) *MockVaultService_Put_Call {
	return &MockVaultService_Put_Call{Call: _e.mock.On("Put", ctx, r, size, vaultPath, metadata)}
}

func (_c *MockVaultService_Put_Call) Run(run func(ctx context.Context, r io.Reader, size int64, vaultPath string, metadata map[string]any)) *MockVaultService_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]any
		if args[4] != nil {
			arg4 = args[4].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockVaultService_Put_Call) Return(file *File, err error) *MockVaultService_Put_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_Put_Call) RunAndReturn(run func(ctx context.Context, r io.Reader, size int64, vaultPath string, metadata map[string]any) (*File, error)) *MockVaultService_Put_Call {
	_c.Call.Return(run)
	return _c
}

// VersionList provides a mock function for the type MockVaultService
func (_mock *MockVaultService) VersionList(ctx context.Context, vaultPath string) ([]*File, error) {
	ret := _mock.Called(ctx, vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for VersionList")
	}

	var r0 []*File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*File, error)); ok {
		return returnFunc(ctx, vaultPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*File); ok {
		r0 = returnFunc(ctx, vaultPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vaultPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_VersionList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionList'
type MockVaultService_VersionList_Call struct {
	*mock.Call
}

// VersionList is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
func (_e *MockVaultService_Expecter) VersionList(ctx any, vaultPath any) *MockVaultService_VersionList_Call {
	return &MockVaultService_VersionList_Call{Call: _e.mock.On("VersionList", ctx, vaultPath)}
}

func (_c *MockVaultService_VersionList_Call) Run(run func(ctx context.Context, vaultPath string)) *MockVaultService_VersionList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockVaultService_VersionList_Call) Return(file []*File, err error) *MockVaultService_VersionList_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_VersionList_Call) RunAndReturn(run func(ctx context.Context, vaultPath string) ([]*File, error)) *MockVaultService_VersionList_Call {
	_c.Call.Return(run)
	return _c
}

// VersionGet provides a mock function for the type MockVaultService
func (_mock *MockVaultService) VersionGet(ctx context.Context, vaultPath string, versionID string) (*File, error) {
	ret := _mock.Called(ctx, vaultPath, versionID)

	if len(ret) == 0 {
		panic("no return value specified for VersionGet")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*File, error)); ok {
		return returnFunc(ctx, vaultPath, versionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *File); ok {
		r0 = returnFunc(ctx, vaultPath, versionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, vaultPath, versionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_VersionGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionGet'
type MockVaultService_VersionGet_Call struct {
	*mock.Call
}

// VersionGet is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - versionID string
func (_e *MockVaultService_Expecter) VersionGet(ctx any, vaultPath any, versionID any) *MockVaultService_VersionGet_Call {
	return &MockVaultService_VersionGet_Call{Call: _e.mock.On("VersionGet", ctx, vaultPath, versionID)}
}

func (_c *MockVaultService_VersionGet_Call) Run(run func(ctx context.Context, vaultPath string, versionID string)) *MockVaultService_VersionGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockVaultService_VersionGet_Call) Return(file *File, err error) *MockVaultService_VersionGet_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_VersionGet_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, versionID string) (*File, error)) *MockVaultService_VersionGet_Call {
	_c.Call.Return(run)
	return _c
}

// VersionDownload provides a mock function for the type MockVaultService
func (_mock *MockVaultService) VersionDownload(ctx context.Context, vaultPath string, versionID string, w io.Writer) error {
	ret := _mock.Called(ctx, vaultPath, versionID, w)

	if len(ret) == 0 {
		panic("no return value specified for VersionDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, vaultPath, versionID, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_VersionDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionDownload'
type MockVaultService_VersionDownload_Call struct {
	*mock.Call
}

// VersionDownload is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - versionID string
//   - w io.Writer
func (_e *MockVaultService_Expecter) VersionDownload(ctx any, vaultPath any, versionID any, w any) *MockVaultService_VersionDownload_Call {
	return &MockVaultService_VersionDownload_Call{Call: _e.mock.On("VersionDownload", ctx, vaultPath, versionID, w)}
}

func (_c *MockVaultService_VersionDownload_Call) Run(run func(ctx context.Context, vaultPath string, versionID string, w io.Writer)) *MockVaultService_VersionDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockVaultService_VersionDownload_Call) Return(err error) *MockVaultService_VersionDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_VersionDownload_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, versionID string, w io.Writer) error) *MockVaultService_VersionDownload_Call {
	_c.Call.Return(run)
	return _c
}

// VersionRestore provides a mock function for the type MockVaultService
func (_mock *MockVaultService) VersionRestore(ctx context.Context, vaultPath string, versionID string) (*File, error) {
	ret := _mock.Called(ctx, vaultPath, versionID)

	if len(ret) == 0 {
		panic("no return value specified for VersionRestore")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*File, error)); ok {
		return returnFunc(ctx, vaultPath, versionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *File); ok {
		r0 = returnFunc(ctx, vaultPath, versionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, vaultPath, versionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_VersionRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionRestore'
type MockVaultService_VersionRestore_Call struct {
	*mock.Call
}

// VersionRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - versionID string
func (_e *MockVaultService_Expecter) VersionRestore(ctx any, vaultPath any, versionID any) *MockVaultService_VersionRestore_Call {
	return &MockVaultService_VersionRestore_Call{Call: _e.mock.On("VersionRestore", ctx, vaultPath, versionID)}
}

func (_c *MockVaultService_VersionRestore_Call) Run(run func(ctx context.Context, vaultPath string, versionID string)) *MockVaultService_VersionRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockVaultService_VersionRestore_Call) Return(file *File, err error) *MockVaultService_VersionRestore_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_VersionRestore_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, versionID string) (*File, error)) *MockVaultService_VersionRestore_Call {
	_c.Call.Return(run)
	return _c
}

// AddTags provides a mock function for the type MockVaultService
func (_mock *MockVaultService) AddTags(ctx context.Context, vaultPath string, tags []string) (*File, error) {
	ret := _mock.Called(ctx, vaultPath, tags)

	if len(ret) == 0 {
		panic("no return value specified for AddTags")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*File, error)); ok {
		return returnFunc(ctx, vaultPath, tags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *File); ok {
		r0 = returnFunc(ctx, vaultPath, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, vaultPath, tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_AddTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTags'
type MockVaultService_AddTags_Call struct {
	*mock.Call
}

// AddTags is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - tags []string
func (_e *MockVaultService_Expecter) AddTags(ctx any, vaultPath any, tags any) *MockVaultService_AddTags_Call {
	return &MockVaultService_AddTags_Call{Call: _e.mock.On("AddTags", ctx, vaultPath, tags)}
}

func (_c *MockVaultService_AddTags_Call) Run(run func(ctx context.Context, vaultPath string, tags []string)) *MockVaultService_AddTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockVaultService_AddTags_Call) Return(file *File, err error) *MockVaultService_AddTags_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_AddTags_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, tags []string) (*File, error)) *MockVaultService_AddTags_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTags provides a mock function for the type MockVaultService
func (_mock *MockVaultService) RemoveTags(ctx context.Context, vaultPath string, tags []string) (*File, error) {
	ret := _mock.Called(ctx, vaultPath, tags)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTags")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*File, error)); ok {
		return returnFunc(ctx, vaultPath, tags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *File); ok {
		r0 = returnFunc(ctx, vaultPath, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, vaultPath, tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_RemoveTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTags'
type MockVaultService_RemoveTags_Call struct {
	*mock.Call
}

// RemoveTags is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - tags []string
func (_e *MockVaultService_Expecter) RemoveTags(ctx any, vaultPath any, tags any) *MockVaultService_RemoveTags_Call {
	return &MockVaultService_RemoveTags_Call{Call: _e.mock.On("RemoveTags", ctx, vaultPath, tags)}
}

func (_c *MockVaultService_RemoveTags_Call) Run(run func(ctx context.Context, vaultPath string, tags []string)) *MockVaultService_RemoveTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockVaultService_RemoveTags_Call) Return(file *File, err error) *MockVaultService_RemoveTags_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_RemoveTags_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, tags []string) (*File, error)) *MockVaultService_RemoveTags_Call {
	_c.Call.Return(run)
	return _c
}

// SetTags provides a mock function for the type MockVaultService
func (_mock *MockVaultService) SetTags(ctx context.Context, vaultPath string, tags []string) (*File, error) {
	ret := _mock.Called(ctx, vaultPath, tags)

	if len(ret) == 0 {
		panic("no return value specified for SetTags")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*File, error)); ok {
		return returnFunc(ctx, vaultPath, tags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *File); ok {
		r0 = returnFunc(ctx, vaultPath, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, vaultPath, tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_SetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTags'
type MockVaultService_SetTags_Call struct {
	*mock.Call
}

// SetTags is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - tags []string
func (_e *MockVaultService_Expecter) SetTags(ctx any, vaultPath any, tags any) *MockVaultService_SetTags_Call {
	return &MockVaultService_SetTags_Call{Call: _e.mock.On("SetTags", ctx, vaultPath, tags)}
}

func (_c *MockVaultService_SetTags_Call) Run(run func(ctx context.Context, vaultPath string, tags []string)) *MockVaultService_SetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockVaultService_SetTags_Call) Return(file *File, err error) *MockVaultService_SetTags_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_SetTags_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, tags []string) (*File, error)) *MockVaultService_SetTags_Call {
	_c.Call.Return(run)
	return _c
}

// TagList provides a mock function for the type MockVaultService
func (_mock *MockVaultService) TagList(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TagList")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_TagList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagList'
type MockVaultService_TagList_Call struct {
	*mock.Call
}

// TagList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVaultService_Expecter) TagList(ctx any) *MockVaultService_TagList_Call {
	return &MockVaultService_TagList_Call{Call: _e.mock.On("TagList", ctx)}
}

func (_c *MockVaultService_TagList_Call) Run(run func(ctx context.Context)) *MockVaultService_TagList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockVaultService_TagList_Call) Return(tags []string, err error) *MockVaultService_TagList_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockVaultService_TagList_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockVaultService_TagList_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Remove(ctx context.Context, vaultPath string) error {
	ret := _mock.Called(ctx, vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, vaultPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockVaultService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
func (_e *MockVaultService_Expecter) Remove(ctx any, vaultPath any) *MockVaultService_Remove_Call {
	return &MockVaultService_Remove_Call{Call: _e.mock.On("Remove", ctx, vaultPath)}
}

func (_c *MockVaultService_Remove_Call) Run(run func(ctx context.Context, vaultPath string)) *MockVaultService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultService_Remove_Call) Return(err error) *MockVaultService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_Remove_Call) RunAndReturn(run func(ctx context.Context, vaultPath string) error) *MockVaultService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Share provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Share(ctx context.Context, vaultPath string, validUntil time.Time) (string, error) {
	ret := _mock.Called(ctx, vaultPath, validUntil)

	if len(ret) == 0 {
		panic("no return value specified for Share")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (string, error)); ok {
		return returnFunc(ctx, vaultPath, validUntil)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) string); ok {
		r0 = returnFunc(ctx, vaultPath, validUntil)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, vaultPath, validUntil)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_Share_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Share'
type MockVaultService_Share_Call struct {
	*mock.Call
}

// Share is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - validUntil time.Time
func (_e *MockVaultService_Expecter) Share(ctx any, vaultPath any, validUntil any) *MockVaultService_Share_Call {
	return &MockVaultService_Share_Call{Call: _e.mock.On("Share", ctx, vaultPath, validUntil)}
}

func (_c *MockVaultService_Share_Call) Run(run func(ctx context.Context, vaultPath string, validUntil time.Time)) *MockVaultService_Share_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultService_Share_Call) Return(s string, err error) *MockVaultService_Share_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVaultService_Share_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, validUntil time.Time) (string, error)) *MockVaultService_Share_Call {
	_c.Call.Return(run)
	return _c
}

// ShareAccept provides a mock function for the type MockVaultService
func (_mock *MockVaultService) ShareAccept(ctx context.Context, vaultPath string, shareURL string, targetPrincipal string) (*File, error) {
	ret := _mock.Called(ctx, vaultPath, shareURL, targetPrincipal)

	if len(ret) == 0 {
		panic("no return value specified for ShareAccept")
	}

	var r0 *File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*File, error)); ok {
		return returnFunc(ctx, vaultPath, shareURL, targetPrincipal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *File); ok {
		r0 = returnFunc(ctx, vaultPath, shareURL, targetPrincipal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, vaultPath, shareURL, targetPrincipal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_ShareAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareAccept'
type MockVaultService_ShareAccept_Call struct {
	*mock.Call
}

// ShareAccept is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
//   - shareURL string
//   - targetPrincipal string
func (_e *MockVaultService_Expecter) ShareAccept(ctx any, vaultPath any, shareURL any, targetPrincipal any) *MockVaultService_ShareAccept_Call {
	return &MockVaultService_ShareAccept_Call{Call: _e.mock.On("ShareAccept", ctx, vaultPath, shareURL, targetPrincipal)}
}

func (_c *MockVaultService_ShareAccept_Call) Run(run func(ctx context.Context, vaultPath string, shareURL string, targetPrincipal string)) *MockVaultService_ShareAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockVaultService_ShareAccept_Call) Return(file *File, err error) *MockVaultService_ShareAccept_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVaultService_ShareAccept_Call) RunAndReturn(run func(ctx context.Context, vaultPath string, shareURL string, targetPrincipal string) (*File, error)) *MockVaultService_ShareAccept_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Stat(ctx context.Context, vaultPath string) (*StatResult, error) {
	ret := _mock.Called(ctx, vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 *StatResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*StatResult, error)); ok {
		return returnFunc(ctx, vaultPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *StatResult); ok {
		r0 = returnFunc(ctx, vaultPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StatResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vaultPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockVaultService_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
func (_e *MockVaultService_Expecter) Stat(ctx any, vaultPath any) *MockVaultService_Stat_Call {
	return &MockVaultService_Stat_Call{Call: _e.mock.On("Stat", ctx, vaultPath)}
}

func (_c *MockVaultService_Stat_Call) Run(run func(ctx context.Context, vaultPath string)) *MockVaultService_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultService_Stat_Call) Return(statResult *StatResult, err error) *MockVaultService_Stat_Call {
	_c.Call.Return(statResult, err)
	return _c
}

func (_c *MockVaultService_Stat_Call) RunAndReturn(run func(ctx context.Context, vaultPath string) (*StatResult, error)) *MockVaultService_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Status(ctx context.Context) (*StatusResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *StatusResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*StatusResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *StatusResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StatusResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockVaultService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVaultService_Expecter) Status(ctx any) *MockVaultService_Status_Call {
	return &MockVaultService_Status_Call{Call: _e.mock.On("Status", ctx)}
}

func (_c *MockVaultService_Status_Call) Run(run func(ctx context.Context)) *MockVaultService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVaultService_Status_Call) Return(statusResult *StatusResult, err error) *MockVaultService_Status_Call {
	_c.Call.Return(statusResult, err)
	return _c
}

func (_c *MockVaultService_Status_Call) RunAndReturn(run func(ctx context.Context) (*StatusResult, error)) *MockVaultService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Sync(ctx context.Context) (int, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 int
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVaultService_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockVaultService_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVaultService_Expecter) Sync(ctx any) *MockVaultService_Sync_Call {
	return &MockVaultService_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *MockVaultService_Sync_Call) Run(run func(ctx context.Context)) *MockVaultService_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVaultService_Sync_Call) Return(applied int, full bool, err error) *MockVaultService_Sync_Call {
	_c.Call.Return(applied, full, err)
	return _c
}

func (_c *MockVaultService_Sync_Call) RunAndReturn(run func(ctx context.Context) (int, bool, error)) *MockVaultService_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockVaultService
func (_mock *MockVaultService) Verify(ctx context.Context, vaultPath string) (*VerifyResult, error) {
	ret := _mock.Called(ctx, vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *VerifyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*VerifyResult, error)); ok {
		return returnFunc(ctx, vaultPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *VerifyResult); ok {
		r0 = returnFunc(ctx, vaultPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VerifyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vaultPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockVaultService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
func (_e *MockVaultService_Expecter) Verify(ctx any, vaultPath any) *MockVaultService_Verify_Call {
	return &MockVaultService_Verify_Call{Call: _e.mock.On("Verify", ctx, vaultPath)}
}

func (_c *MockVaultService_Verify_Call) Run(run func(ctx context.Context, vaultPath string)) *MockVaultService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultService_Verify_Call) Return(verifyResult *VerifyResult, err error) *MockVaultService_Verify_Call {
	_c.Call.Return(verifyResult, err)
	return _c
}

func (_c *MockVaultService_Verify_Call) RunAndReturn(run func(ctx context.Context, vaultPath string) (*VerifyResult, error)) *MockVaultService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDeep provides a mock function for the type MockVaultService
func (_mock *MockVaultService) VerifyDeep(ctx context.Context, vaultPath string) (*VerifyResult, error) {
	ret := _mock.Called(ctx, vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDeep")
	}

	var r0 *VerifyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*VerifyResult, error)); ok {
		return returnFunc(ctx, vaultPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *VerifyResult); ok {
		r0 = returnFunc(ctx, vaultPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VerifyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vaultPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_VerifyDeep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDeep'
type MockVaultService_VerifyDeep_Call struct {
	*mock.Call
}

// VerifyDeep is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultPath string
func (_e *MockVaultService_Expecter) VerifyDeep(ctx any, vaultPath any) *MockVaultService_VerifyDeep_Call {
	return &MockVaultService_VerifyDeep_Call{Call: _e.mock.On("VerifyDeep", ctx, vaultPath)}
}

func (_c *MockVaultService_VerifyDeep_Call) Run(run func(ctx context.Context, vaultPath string)) *MockVaultService_VerifyDeep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultService_VerifyDeep_Call) Return(verifyResult *VerifyResult, err error) *MockVaultService_VerifyDeep_Call {
	_c.Call.Return(verifyResult, err)
	return _c
}

func (_c *MockVaultService_VerifyDeep_Call) RunAndReturn(run func(ctx context.Context, vaultPath string) (*VerifyResult, error)) *MockVaultService_VerifyDeep_Call {
	_c.Call.Return(run)
	return _c
}
